Repository akuity/kargo, pull requests merged in 2023-06, with the labels that each got.

#395 use latest Bookkeeper release
  go.mod
  go.sum
Labels: chore

#394 Add lint-proto job to CI workflow
  .github/workflows/ci.yaml
  Makefile
  api/buf.yaml
  api/service/v1alpha1/service.proto
  go.mod
  pkg/api/service/v1alpha1/service.pb.go
Labels: ci process

#397 Use latest version of `akuity/gogoproto`
  go.mod
  go.sum
Labels: bug, enhancement

#396 require explicit opt-in when borrowing creds from Argo CD
  internal/credentials/credentials.go
Labels: security

#386 Log stacktrace on panic
  internal/api/option/interceptor.go
  internal/api/option/runtime.go
Labels: enhancement, go

#389 Add `PromoteEnvironment` handler to API server
  api/service/v1alpha1/service.proto
  charts/kargo/templates/api/cluster-role.yaml
  go.mod
  internal/api/handler/get_environment_v1alpha1_test.go
  internal/api/handler/handler_test.go
  internal/api/handler/list_environments_v1alpha1_test.go
  internal/api/handler/promote_environment_v1alpha1.go
  internal/api/handler/promote_environment_v1alpha1_test.go
  internal/api/handler/testdata/environment.yaml
  internal/api/handler/testdata/namespace.yaml
  internal/api/handler/types_v1alpha1.go
  internal/api/server.go
  pkg/api/service/v1alpha1/service.pb.go
  pkg/api/service/v1alpha1/svcv1alpha1connect/service.connect.go
  ui/src/gen/service/v1alpha1/service-KargoService_connectquery.ts
  ui/src/gen/service/v1alpha1/service_pb.ts
Labels: enhancement, go

#399 DRY up lint-proto step in CI by reusing make target
  .github/workflows/ci.yaml
  Makefile
Labels: chore

#398 add hack-lint-go make target and update hacking docs
  Makefile
  docs/docs/40-contributor-guide/10-hacking-on-kargo.md
Labels: documentation, chore

#400 Use the latest version of gogoproto
  go.mod
  go.sum
Labels: bug

#408 Set owner reference typemeta explicitly
  internal/api/handler/promote_environment_v1alpha1.go
Labels: bug

#410 Update `Serve` method to take listener as an argument
  cmd/controlplane/api.go
  internal/api/server.go
  internal/config/config.go
Labels: refactor, go

#404 document credential management
  docs/docs/30-how-to-guides/20-managing-credentials.md
Labels: documentation, do not merge yet

#379 update docs for v0.1.0-rc.10 release
  docs/docs/15-concepts.md
  docs/docs/20-quickstart.mdx
Labels: documentation, do not merge yet

#422 fix incorrect urls in concepts doc
  docs/docs/15-concepts.md
Labels: bug, documentation

#428 fix flaky unit test
  internal/controller/promotions/helm_test.go
Labels: bug

#411 Add promote command to CLI
  cmd/cli/main.go
  cmd/cli/root.go
  cmd/cli/version.go
  go.mod
  internal/api/option/option.go
  internal/cli/env/env.go
  internal/cli/env/promote.go
  internal/cli/option/flag.go
  internal/cli/option/option.go
  internal/config/config.go
Labels: enhancement, go

#425 update kargo-kit chart to directly manage service accounts
  charts/kargo-kit/Chart.yaml
  charts/kargo-kit/templates/cluster-role-bindings.yaml
  charts/kargo-kit/templates/cluster-roles.yaml
  charts/kargo-kit/templates/service-account.yaml
  charts/kargo-kit/values.yaml
  charts/kargo/templates/controller/cluster-role.yaml
Labels: enhancement

#429 add slack badge to README.md
  README.md
Labels: documentation, chore

#423 improve error message when admission webhook denies request
  internal/controller/promotions/webhook.go
  internal/controller/promotions/webhooks_test.go
Labels: enhancement

#409 support the possibility that the Kargo controller isn't co-located with its own data or with Argo CD
  cmd/controlplane/controller.go
  go.mod
  internal/controller/applications/applications.go
  internal/controller/environments/argocd.go
  internal/controller/environments/environments.go
  internal/controller/environments/environments_test.go
  internal/controller/promotions/argocd.go
  internal/controller/promotions/argocd_test.go
  internal/controller/promotions/promotions.go
  internal/controller/promotions/promotions_test.go
  internal/credentials/credentials.go
  internal/credentials/credentials_test.go
Labels: enhancement, devx

#433 separate webhooks server from controller
  Tiltfile
  charts/kargo/templates/_helpers.tpl
  charts/kargo/templates/common/cert-issuer.yaml
  charts/kargo/templates/controller/cluster-role.yaml
  charts/kargo/templates/controller/deployment.yaml
  charts/kargo/templates/controller/webhook-server-cert.yaml
  charts/kargo/templates/webhooks-server/cert.yaml
  charts/kargo/templates/webhooks-server/cluster-role-binding.yaml
  charts/kargo/templates/webhooks-server/cluster-role.yaml
  charts/kargo/templates/webhooks-server/deployment.yaml
  charts/kargo/templates/webhooks-server/service-account.yaml
  charts/kargo/templates/webhooks-server/service.yaml
  charts/kargo/templates/webhooks/webhooks.yaml
  charts/kargo/values.yaml
  cmd/controlplane/controller.go
  cmd/controlplane/root.go
  cmd/controlplane/webhooks.go
  internal/config/config.go
  internal/controller/environments/environments.go
  internal/webhooks/environments/webhooks.go
  internal/webhooks/environments/webhooks_test.go
  internal/webhooks/promotions/webhooks.go
  internal/webhooks/promotions/webhooks_test.go
Labels: enhancement

#430 Implement Create/Delete Environment service
  api/service/v1alpha1/service.proto
  charts/kargo/templates/api/cluster-role.yaml
  internal/api/handler/create_environment_v1alpha1.go
  internal/api/handler/delete_environment_v1alpha1.go
  internal/api/handler/types_v1alpha1.go
  internal/api/server.go
  pkg/api/service/v1alpha1/service.pb.go
  pkg/api/service/v1alpha1/svcv1alpha1connect/service.connect.go
  ui/src/gen/service/v1alpha1/service-KargoService_connectquery.ts
  ui/src/gen/service/v1alpha1/service_pb.ts
Labels: enhancement, go

#434 chart: add the option to selectively disable each component
  charts/kargo/templates/api/cluster-role-binding.yaml
  charts/kargo/templates/api/cluster-role.yaml
  charts/kargo/templates/api/deployment.yaml
  charts/kargo/templates/api/service-account.yaml
  charts/kargo/templates/api/services.yaml
  charts/kargo/templates/controller/cluster-role-binding.yaml
  charts/kargo/templates/controller/cluster-role.yaml
  charts/kargo/templates/controller/deployment.yaml
  charts/kargo/templates/controller/service-account.yaml
  charts/kargo/templates/webhooks-server/cert.yaml
  charts/kargo/templates/webhooks-server/cluster-role-binding.yaml
  charts/kargo/templates/webhooks-server/cluster-role.yaml
  charts/kargo/templates/webhooks-server/deployment.yaml
  charts/kargo/templates/webhooks-server/service-account.yaml
  charts/kargo/templates/webhooks-server/service.yaml
  charts/kargo/values.yaml
Labels: enhancement

#435 add option to opt-out of cred borrowing entirely
  charts/kargo/templates/controller/deployment.yaml
  charts/kargo/values.yaml
  cmd/controlplane/controller.go
  internal/config/config.go
  internal/credentials/credentials.go
  internal/os/env.go
  internal/os/env_test.go
Labels: enhancement, security

#436 optionally prefer in-cluster REST config for client that access Argo CD CRs
  charts/kargo/templates/controller/deployment.yaml
  charts/kargo/values.yaml
  cmd/controlplane/controller.go
  cmd/controlplane/webhooks.go
  internal/config/config.go
Labels: enhancement

#437 Sync all components to load kubeconfig in same order
  internal/config/config.go
  internal/kubeclient/config.go
Labels: enhancement, go

#440 alphabetize handles in CODEOWNERS file and add @gdsoumya
  CODEOWNERS
Labels: chore

#441 fix incorrect call for loading default rest config
  cmd/controlplane/common.go
  cmd/controlplane/controller.go
Labels: bug

#442 tame our configuration
  cmd/cli/root.go
  cmd/controlplane/api.go
  cmd/controlplane/controller.go
  cmd/controlplane/webhooks.go
  go.mod
  go.sum
  internal/api/option/option.go
  internal/api/server.go
  internal/config/config.go
  internal/config/types.go
  internal/config/types_test.go
  internal/logging/context.go
  internal/logging/context_test.go
  internal/os/env.go
  internal/os/env_test.go
  internal/types/types.go
  internal/types/types_test.go
  internal/webhooks/promotions/webhooks.go
  internal/webhooks/promotions/webhooks_test.go
Labels: chore, refactor

#444 rewrite credentials DB to not index k8s secrets
  cmd/controlplane/controller.go
  internal/credentials/credentials.go
  internal/credentials/credentials_test.go
Labels: security
