Repository akuity/kargo, pull requests merged in 2023-05, with the labels that each got.

#344 feat: bootstrap CLI
  Dockerfile
  cmd/cli/main.go
  cmd/controlplane/main.go
  internal/cmd/cli/root.go
  internal/cmd/controlplane/api.go
  internal/cmd/controlplane/api_proxy.go
  internal/cmd/controlplane/controller.go
  internal/cmd/controlplane/root.go
  internal/cmd/controlplane/version.go
Labels: enhancement, refactor

#347 refactor: move commands to cmd package
  cmd/cli/main.go
  cmd/cli/root.go
  cmd/controlplane/api.go
  cmd/controlplane/api_proxy.go
  cmd/controlplane/controller.go
  cmd/controlplane/main.go
  cmd/controlplane/root.go
  cmd/controlplane/version.go
Labels: refactor

#346 fix missing version info in official images
  .github/workflows/release.yaml
  Dockerfile
  Makefile
  Tiltfile
  internal/version/version.go
Labels: bug

#351 Update CODEOWNERS
  CODEOWNERS
Labels: chore

#355 Add linters
  .golangci.yaml
  cmd/controlplane/controller.go
  internal/api/proxy/server.go
  internal/api/server/grpc_health_v1.go
  internal/api/server/handler/grpc_health_check_v1.go
  internal/config/config.go
  internal/controller/environments/environments.go
  internal/controller/environments/environments_test.go
  internal/controller/environments/git_test.go
  internal/controller/environments/helm_test.go
  internal/controller/environments/images.go
  internal/controller/environments/images_test.go
  internal/controller/environments/webhook.go
  internal/controller/promotions/argocd_test.go
  internal/controller/promotions/bookkeeper_test.go
  internal/controller/promotions/git_test.go
  internal/controller/promotions/helm_test.go
  internal/controller/promotions/kustomize_test.go
  internal/controller/promotions/promotions.go
  internal/controller/promotions/promotions_test.go
  internal/controller/promotions/webhook.go
  internal/controller/promotions/webhooks_test.go
  internal/controller/runtime/queues.go
  internal/credentials/credentials.go
  internal/git/convenience.go
  internal/git/convenience_test.go
  internal/git/repo.go
  internal/images/image_updater.go
  internal/images/image_updater_test.go
  internal/images/images.go
  internal/images/images_test.go
  internal/kubeclient/context.go
  internal/kubeclient/transport.go
  internal/kubeclient/transport_test.go
  internal/logging/context.go
  internal/os/env.go
Labels: chore

#356 Use Connect protocol for the API server
  Tiltfile
  charts/kargo/templates/api/deployment.yaml
  charts/kargo/templates/api/services.yaml
  charts/kargo/values.yaml
  cmd/controlplane/api.go
  cmd/controlplane/api_proxy.go
  cmd/controlplane/root.go
  go.mod
  go.sum
  internal/api/grpc_health.go
  internal/api/option/interceptor.go
  internal/api/option/log.go
  internal/api/option/log_test.go
  internal/api/proxy/server.go
  internal/api/server.go
  internal/api/server/grpc_health_v1.go
  internal/api/server/handler/grpc_health_check_v1.go
  internal/api/server/handler/grpc_health_check_v1_test.go
  internal/api/server/interceptor/interceptor.go
  internal/config/config.go
Labels: enhancement

#359 Generate Connect code for the `KargoService`
  api/proto/kargo/v1alpha1/kargo.proto
  buf.gen.yaml
  buf.lock
  buf.yaml
  pkg/api/gen/kargo/v1alpha1/kargo.pb.go
  pkg/api/gen/kargo/v1alpha1/kargo.pb.gw.go
  pkg/api/gen/kargo/v1alpha1/kargo_grpc.pb.go
  pkg/api/gen/kargo/v1alpha1/kargov1alpha1connect/kargo.connect.go
  ui/.gitignore
  ui/package.json
  ui/pnpm-lock.yaml
  ui/src/gen/kargo/v1alpha1/kargo-KargoService_connectquery.ts
  ui/src/gen/kargo/v1alpha1/kargo_pb.ts
  ui/src/gen/kargo/v1alpha1/types_pb.ts
Labels: enhancement, javascript, go

#348 feat: add kubernetes credential hook for CLI
  internal/kubeclient/auth.go
  internal/kubeclient/config.go
  internal/kubeclient/context.go
  internal/kubeclient/kubeclient.go
  internal/kubeclient/transport.go
  internal/kubeclient/transport_test.go
Labels: enhancement

#360 upgrade to the latest bookkeeper
  Dockerfile
  go.mod
  go.sum
  internal/controller/promotions/bookkeeper.go
Labels: chore

#362 update CODEOWNERS
  CODEOWNERS
Labels: chore

#361 add codecov badge to readme
  README.md
Labels: chore

#365 remove unnecessary bits from CI workflow
  .github/workflows/ci.yaml
Labels: chore

#367 update docs to reflect latest release
  docs/docs/15-concepts.md
  docs/docs/20-quickstart.mdx
  docs/docs/30-how-to-guides/10-installing-kargo.md
Labels: documentation

#364 Generate proto definition from kubebuilder structs
  .github/workflows/ci.yaml
  .gitignore
  Dockerfile.dev
  Makefile
  api/buf.lock
  api/buf.yaml
  api/proto/buf.lock
  api/proto/kargo/v1alpha1/types.proto
  api/service/v1alpha1/service.proto
  api/v1alpha1/environment_types.go
  api/v1alpha1/generated.proto
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/promotion_types.go
  api/v1alpha1/promotionpolicy_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  buf.gen.yaml
  buf.work.yaml
  go.mod
  hack/generate-proto.sh
  internal/controller/environments/environments_test.go
  internal/controller/promotions/promotions_test.go
  pkg/api/gen/kargo/v1alpha1/kargo.pb.go
  pkg/api/gen/kargo/v1alpha1/types.pb.go
  pkg/api/gen/service/v1alpha1/service.pb.go
  pkg/api/gen/service/v1alpha1/svcv1alpha1connect/service.connect.go
  pkg/api/gen/v1alpha1/generated.pb.go
  ui/src/gen/kargo/v1alpha1/types_pb.ts
  ui/src/gen/service/v1alpha1/service-KargoService_connectquery.ts
  ui/src/gen/service/v1alpha1/service_pb.ts
  ui/src/gen/v1alpha1/generated_pb.ts
Labels: enhancement, go

#368 Fix generated code to import packages correctly
  api/service/v1alpha1/service.proto
  api/v1alpha1/generated.proto
  buf.gen.yaml
  hack/generate-proto.sh
  pkg/api/service/v1alpha1/service.pb.go
  pkg/api/service/v1alpha1/svcv1alpha1connect/service.connect.go
  pkg/api/v1alpha1/generated.pb.go
  tools/tools.go
  ui/src/gen/service/v1alpha1/service_pb.ts
  ui/src/gen/v1alpha1/generated_pb.ts
Labels: bug

#369 use our newer/prettier URL in CODE_OF_CONDUCT.md and CONTRIBUTING.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: documentation, chore

#371 fix git reset --hard command
  internal/git/repo.go
Labels: bug

#370 upgrade to go 1.20.4
  .github/workflows/ci.yaml
  Dockerfile
  Dockerfile.dev
Labels: chore

#372 update docs with latest version info
  docs/docs/20-quickstart.mdx
  docs/docs/30-how-to-guides/10-installing-kargo.md
Labels: documentation, chore

#375 Change default API port to 8080
  internal/config/config.go
Labels: bug

#374 simplify and otherwise improve the quickstart
  docs/docs/20-quickstart.mdx
Labels: documentation

#376 Add Get/List Environment handler
  .golangci.yaml
  Tiltfile
  charts/kargo/templates/api/cluster-role.yaml
  cmd/controlplane/api.go
  go.mod
  go.sum
  internal/api/handler/get_environment_v1alpha1.go
  internal/api/handler/get_environment_v1alpha1_test.go
  internal/api/handler/handler_test.go
  internal/api/handler/list_environments_v1alpha1.go
  internal/api/handler/list_environments_v1alpha1_test.go
  internal/api/handler/testdata/environment.yaml
  internal/api/handler/types_v1alpha1.go
  internal/api/option/codec.go
  internal/api/option/codec_test.go
  internal/api/option/interceptor.go
  internal/api/server.go
  internal/config/config.go
  internal/config/types.go
  internal/config/types_test.go
Labels: refactor, go

#378 streamline healthchecks
  api/v1alpha1/environment_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/kargo-kit/crds/kargo.akuity.io_environments.yaml
  charts/kargo/crds/kargo.akuity.io_environments.yaml
  internal/api/handler/types_v1alpha1.go
  internal/controller/environments/argocd.go
  internal/controller/environments/argocd_test.go
  internal/controller/environments/environments.go
  internal/controller/environments/environments_test.go
  internal/controller/environments/webhook.go
  internal/controller/environments/webhook_test.go
Labels: refactor

#377 Add interceptor for authentication
  internal/api/option/auth.go
  internal/api/option/auth_test.go
  internal/api/option/interceptor.go
  internal/api/option/log_test.go
  internal/api/server.go
  internal/kubeclient/context.go
  internal/kubeclient/context_test.go
  internal/kubeclient/transport.go
  internal/kubeclient/transport_test.go
Labels: enhancement

#380 Generate `k8s.io/` types for UI
  api/v1alpha1/generated.proto
  hack/generate-proto.sh
  pkg/api/v1alpha1/generated.pb.go
  ui.buf.gen.yaml
  ui/src/gen/k8s.io/api/core/v1/generated_pb.ts
  ui/src/gen/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/generated_pb.ts
  ui/src/gen/k8s.io/apimachinery/pkg/api/resource/generated_pb.ts
  ui/src/gen/k8s.io/apimachinery/pkg/apis/meta/v1/generated_pb.ts
  ui/src/gen/k8s.io/apimachinery/pkg/runtime/generated_pb.ts
  ui/src/gen/k8s.io/apimachinery/pkg/util/intstr/generated_pb.ts
  ui/src/gen/v1alpha1/generated_pb.ts
Labels: bug, javascript

#385 Allow API server to read namespaces (projects)
  charts/kargo/templates/api/cluster-role.yaml
Labels: bug

#384 Rename `namespace` to `project`
  api/service/v1alpha1/service.proto
  internal/api/handler/get_environment_v1alpha1.go
  internal/api/handler/get_environment_v1alpha1_test.go
  internal/api/handler/list_environments_v1alpha1.go
  internal/api/handler/list_environments_v1alpha1_test.go
  pkg/api/service/v1alpha1/service.pb.go
  ui/src/gen/service/v1alpha1/service_pb.ts
Labels: enhancement, go

#383 Encode/Decode JSON encoded `metav1.Time` properly
  Makefile
  hack/api/apply-patches.sh
  hack/api/patches/apimachinery_meta_v1.patch
  ui/package.json
  ui/pnpm-lock.yaml
  ui/src/gen/k8s.io/apimachinery/pkg/apis/meta/v1/generated_pb.ts
  ui/tests/api/apimachinery.spec.ts
  ui/vite.config.ts
Labels: bug, javascript

#387 Silence `proto: tag has too few fields` warning
  go.mod
  go.sum
Labels: bug, go

#388 Check subscription repos nilability before mapping
  internal/api/handler/types_v1alpha1.go
Labels: bug, go

#393 Cleanup directory before generating Kubernetes types proto
  hack/generate-proto.sh
Labels: bug
