Repository akuity/kargo, pull requests merged in 2023-07, with the labels that each got.

#452 webhooks: remove special authz logic for namespace controller
  charts/kargo/templates/webhooks-server/cluster-role-binding.yaml
  charts/kargo/templates/webhooks-server/cluster-role.yaml
  internal/webhooks/promotions/webhooks.go
  internal/webhooks/promotions/webhooks_test.go
Labels: refactor

#447 tidy the Tiltfile: categorize previously uncategorized resources
  Tiltfile
Labels: chore

#460 bring docs up to date
  README.md
  docs/docs/10-overview.md
  docs/docs/15-concepts.md
  docs/docs/20-quickstart.mdx
  docs/docs/30-how-to-guides/10-installing-kargo.md
  docs/docs/30-how-to-guides/20-managing-credentials.md
Labels: documentation

#463 removed unused rbac api from controller schema
  cmd/controlplane/controller.go
Labels: chore

#467 look for upstream stages only in a stage's own namespace
  api/v1alpha1/generated.proto
  api/v1alpha1/stage_types.go
  charts/kargo-kit/crds/kargo.akuity.io_stages.yaml
  charts/kargo/crds/kargo.akuity.io_stages.yaml
  internal/api/handler/types_v1alpha1.go
  internal/controller/stages/stages.go
  internal/controller/stages/stages_test.go
  internal/webhooks/stages/webhooks.go
  internal/webhooks/stages/webhooks_test.go
  pkg/api/v1alpha1/generated.pb.go
  ui/src/gen/v1alpha1/generated_pb.ts
Labels: enhancement

#469 fix todo in helm chart subscription tests
  internal/helm/helm_test.go
Labels: chore

#468 fix use of context.TODO() in tests
  internal/api/handler/get_stage_v1alpha1_test.go
  internal/api/handler/list_stages_v1alpha1_test.go
  internal/api/handler/promote_stage_v1alpha1_test.go
  internal/kubeclient/transport_test.go
Labels: chore

#465 Tiltfile: fix uncategorized resources
  Tiltfile
Labels: chore

#464 Generate JSON schema from CRD manifests
  .github/workflows/ci.yaml
  Makefile
  ui/hack/generate-schema.mjs
  ui/package.json
  ui/pnpm-lock.yaml
  ui/src/gen/schema/promotionpolicies.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/promotions.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
  ui/tsconfig.json
Labels: enhancement

#476 low-level sharding support in the controller
  charts/kargo/templates/controller/deployment.yaml
  charts/kargo/values.yaml
  cmd/controlplane/controller.go
  internal/controller/applications/applications.go
  internal/controller/applications/applications_test.go
  internal/controller/common.go
  internal/controller/promotions/promotions.go
  internal/controller/stages/stages.go
  internal/controller/stages/stages_test.go
Labels: enhancement

#485 make default controller work exclusively on unlabeled resources
  charts/kargo/values.yaml
  internal/controller/applications/applications.go
  internal/controller/applications/applications_test.go
  internal/controller/common.go
  internal/controller/labels.go
  internal/controller/labels_test.go
  internal/controller/promotions/promotions.go
  internal/controller/stages/stages.go
Labels: enhancement, refactor
