Repository akuity/kargo, pull requests merged in 2024-11, with the labels that each got.

#2874 feat(ui): user info page
  ui/src/app.tsx
  ui/src/config/paths.ts
  ui/src/features/auth/context/auth-context-provider.tsx
  ui/src/features/auth/context/auth-context.tsx
  ui/src/features/auth/utils.ts
  ui/src/features/common/layout/main-layout.tsx
  ui/src/pages/user.tsx
Labels: kind/enhancement, area/ui, priority/normal

#2884 fix(ui): live image matrix view
  ui/src/features/project/pipelines/images.tsx
  ui/src/features/project/pipelines/pipelines.tsx
  ui/src/features/project/pipelines/utils/watcher.ts
  ui/src/features/utils/cache/image-stage-matrix.ts
  ui/src/features/utils/cache/index.ts
Labels: kind/bug, area/ui, priority/normal

#2881 feat(controller)!: assign a default alias to promotion steps that have none
  internal/directives/simple_engine.go
  internal/webhook/stage/webhook.go
  internal/webhook/stage/webhook_test.go
Labels: kind/enhancement, priority/normal, area/controller

#2894 fix(stages): auto-promote Freight from other origins
  internal/controller/stages/stages.go
Labels: kind/bug, priority/normal, area/controller, backport/release-1.0

#2871 fix: next/prev navigation in docs
  netlify.toml
Labels: kind/bug, area/documentation, priority/normal, backport/release-1.0

#2696 docs: managing projects
  docs/docs/15-concepts.md
  docs/docs/30-how-to-guides/11-working-with-projects.md
Labels: area/documentation, kind/enhancement, priority/high, backport/release-1.0

#2896 fix(controller): fix pr already open issue with git-open-pr step
  internal/controller/git/work_tree.go
  internal/controller/promotions/promotions.go
  internal/directives/git_pr_opener.go
  internal/directives/git_pr_opener_test.go
  internal/directives/git_pr_waiter.go
  internal/directives/git_pr_waiter_test.go
  internal/gitprovider/github/github.go
  internal/gitprovider/github/github_test.go
  internal/gitprovider/gitlab/gitlab.go
  internal/gitprovider/gitlab/gitlab_test.go
  internal/gitprovider/gitprovider.go
  internal/gitprovider/registry.go
Labels: kind/bug, priority/normal, area/controller

#2899 chore: update helm chart versions
  Makefile
  hack/quickstart/install.sh
  hack/quickstart/k3d.sh
  hack/quickstart/kind.sh
Labels: area/documentation, kind/chore, area/devx, priority/normal

#2904 feat(ui): pipeline UX improvements
  ui/src/features/project/pipelines/images.tsx
  ui/src/features/project/pipelines/pipelines.tsx
  ui/src/features/project/pipelines/project-details.module.less
  ui/src/features/project/pipelines/utils/use-pipelines-infinite-canvas.ts
  ui/src/utils/use-local-storage.ts
Labels: kind/enhancement, area/ui, priority/normal

#2915 fix(ui): Links/Buttons in the Pipeline are not working
  ui/src/features/project/pipelines/utils/use-pipelines-infinite-canvas.ts
Labels: kind/bug, area/ui, priority/high

#2918 fix(ui): pipeline view issues
  ui/src/features/project/pipelines/utils/use-pipelines-infinite-canvas.ts
Labels: kind/bug, area/ui, priority/high

#2925 feat(controller): add functions to EL for finding artifacts in promo's freight collection
  docs/docs/35-references/10-promotion-steps.md
  docs/docs/35-references/20-expression-language.md
  internal/directives/argocd_revisions.go
  internal/directives/argocd_updater.go
  internal/directives/argocd_updater_test.go
  internal/directives/git_cloner.go
  internal/directives/git_cloner_test.go
  internal/directives/helm_chart_updater.go
  internal/directives/helm_chart_updater_test.go
  internal/directives/helm_common.go
  internal/directives/helm_image_updater.go
  internal/directives/helm_image_updater_test.go
  internal/directives/kustomize_image_setter.go
  internal/directives/kustomize_image_setter_test.go
  internal/directives/promotions.go
  internal/directives/promotions_test.go
  internal/directives/schemas/argocd-update-config.json
  internal/directives/schemas/git-clone-config.json
  internal/directives/schemas/helm-update-chart-config.json
  internal/directives/schemas/helm-update-image-config.json
  internal/directives/schemas/kustomize-set-image-config.json
  internal/directives/simple_engine.go
  internal/directives/zz_config_types.go
  internal/expressions/json_templates.go
  ui/src/gen/directives/argocd-update-config.json
  ui/src/gen/directives/git-clone-config.json
  ui/src/gen/directives/helm-update-chart-config.json
  ui/src/gen/directives/helm-update-image-config.json
  ui/src/gen/directives/kustomize-set-image-config.json
Labels: kind/enhancement, priority/high, area/controller

#2930 fix(docs): consistent title case
  docs/docs/30-how-to-guides/15-working-with-freight.md
  docs/docs/30-how-to-guides/20-managing-credentials.md
  docs/docs/30-how-to-guides/30-managing-user-permissions.md
  docs/docs/30-how-to-guides/_category_.json
  docs/docs/35-references/_category_.json
  docs/docs/40-contributor-guide/20-signing-commits.md
  docs/docs/40-contributor-guide/30-code-of-conduct.md
  docs/docs/40-contributor-guide/index.md
Labels: kind/bug, area/documentation, kind/chore, priority/normal, backport/release-1.0

#2932 fix(directives): log error to surface reason for ArgoCD update
  internal/directives/argocd_updater.go
Labels: kind/bug, priority/high, area/controller, backport/release-1.0

#2905 refactor: rewrite Stage reconciler
  api/v1alpha1/conditions.go
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/stage_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
  cmd/controlplane/controller.go
  internal/controller/stages/control_flow_stages.go
  internal/controller/stages/control_flow_stages_test.go
  internal/controller/stages/regular_stages.go
  internal/controller/stages/regular_stages_test.go
  internal/controller/stages/stages.go
  internal/controller/stages/stages_test.go
  internal/controller/stages/verification.go
  internal/controller/stages/verification_test.go
  internal/indexer/indexer.go
  internal/rollouts/analysis_run_builder.go
  internal/rollouts/analysis_run_builder_test.go
  internal/rollouts/analysis_template.go
  internal/rollouts/analysis_template_test.go
  internal/rollouts/options.go
  internal/rollouts/options_test.go
  ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
  ui/src/gen/v1alpha1/generated_pb.ts
Labels: kind/refactor, priority/normal, area/controller, size/xx-large

#2941 refactor: replace helm-update-image with yaml-update
  docs/docs/35-references/10-promotion-steps.md
  internal/directives/helm_image_updater.go
  internal/directives/helm_image_updater_test.go
  internal/directives/schemas/helm-update-image-config.json
  internal/directives/schemas/yaml-update-config.json
  internal/directives/yaml_updater.go
  internal/directives/yaml_updater_test.go
  internal/directives/zz_config_types.go
  ui/src/gen/directives/helm-update-image-config.json
  ui/src/gen/directives/yaml-update-config.json
Labels: area/documentation, kind/refactor, priority/normal, area/controller

#2959 fix(build): use `tini` to reap zombie processes
  Dockerfile
  charts/kargo/templates/controller/deployment.yaml
  charts/kargo/templates/garbage-collector/cron-job.yaml
  charts/kargo/templates/management-controller/deployment.yaml
  charts/kargo/templates/webhooks-server/deployment.yaml
  kargo-base.apko.yaml
Labels: kind/bug, priority/high, area/charts, docker, backport/release-1.0

#2951 fix(stages): set healthy status for promotions w/o checks
  internal/controller/stages/regular_stages.go
  internal/controller/stages/regular_stages_test.go
Labels: kind/bug, do not merge yet, priority/high, area/controller

#2949 ci: add typechecks for UI
  .github/workflows/ci.yaml
  Makefile
  ui/src/features/common/code-editor/yaml-editor-lazy.tsx
  ui/src/features/project/credentials/create-credentials-modal.tsx
  ui/src/features/project/credentials/utils.tsx
  ui/src/features/project/list/project-list-filter.tsx
  ui/src/features/project/pipelines/nodes/freight-indicators.tsx
  ui/src/features/project/pipelines/utils/useImages.ts
  ui/tsconfig.json
Labels: kind/chore, area/ci-process, area/ui, priority/normal

#2964 fix: update casing to Azure Example in values.yaml unknown connector type "Microsoft"
  charts/kargo/values.yaml
Labels: kind/bug, priority/high, area/charts

#2973 fix(api): be more thorough with checking if secret management is enabled
  internal/api/common.go
  internal/api/create_credentials_v1alpha1.go
  internal/api/create_or_update_resource_v1alpha1.go
  internal/api/create_resource_v1alpha1.go
  internal/api/delete_credentials_v1alpha1.go
  internal/api/delete_resource_v1alpha1.go
  internal/api/get_credentials_v1alpha1.go
  internal/api/list_credentials_v1alpha1.go
  internal/api/update_credentials_v1alpha1.go
Labels: kind/bug, priority/high, area/api

#2969 fix: missing enumerated values in generated docs for warehouse
  api/v1alpha1/generated.proto
  api/v1alpha1/warehouse_types.go
  charts/kargo/resources/crds/kargo.akuity.io_warehouses.yaml
  ui/src/gen/schema/warehouses.kargo.akuity.io_v1alpha1.json
  ui/src/gen/v1alpha1/generated_pb.ts
Labels: priority/high, area/crds, backport/release-1.0

#2962 docs: authorise kargo to argocd-update
  docs/docs/35-references/10-promotion-steps.md
Labels: area/documentation, kind/enhancement, kind/chore, priority/high, backport/release-1.0

#2966 feat: generic http promotion step
  docs/docs/35-references/10-promotion-steps.md
  internal/directives/http_requester.go
  internal/directives/http_requester_test.go
  internal/directives/schemas/http-config.json
  internal/directives/zz_config_types.go
  ui/src/gen/directives/http-config.json
Labels: area/documentation, kind/enhancement, priority/high, area/controller

#2940 feat: allow configuration of retry attempts for Promotion steps
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/promotion_types.go
  api/v1alpha1/promotion_types_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/kargo/resources/crds/kargo.akuity.io_promotions.yaml
  charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
  internal/controller/promotions/promotions.go
  internal/directives/argocd_revisions.go
  internal/directives/argocd_updater.go
  internal/directives/git_commiter.go
  internal/directives/git_commiter_test.go
  internal/directives/git_pr_opener.go
  internal/directives/git_pr_opener_test.go
  internal/directives/git_pr_waiter.go
  internal/directives/git_pusher.go
  internal/directives/git_pusher_test.go
  internal/directives/promotions.go
  internal/directives/promotions_test.go
  internal/directives/simple_engine.go
  internal/directives/simple_engine_health.go
  internal/directives/simple_engine_health_test.go
  internal/directives/simple_engine_promote.go
  internal/directives/simple_engine_promote_test.go
  internal/directives/simple_engine_test.go
  ui/src/gen/schema/promotions.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
  ui/src/gen/v1alpha1/generated_pb.ts
Labels: kind/enhancement, priority/normal, area/controller

#2981 chore(deps/tools): update golangci-lint to 1.62.0
  hack/tools/go.mod
  hack/tools/go.sum
  internal/conditions/conditions_test.go
  internal/controller/stages/event_handlers.go
  internal/directives/helm_template_runner.go
  internal/image/selector_docker_hub_test.go
  internal/image/selector_ghcr_test.go
  internal/rollouts/analysis_template.go
  internal/webhook/freight/webhook.go
  internal/webhook/promotion/webhook.go
Labels: dependencies, go

#2980 fix(controller)!: do not attempt to infer desired revision when not specified
  docs/docs/35-references/10-promotion-steps.md
  internal/directives/argocd_revisions.go
  internal/directives/argocd_revisions_test.go
  internal/directives/argocd_updater.go
  internal/directives/argocd_updater_test.go
Labels: kind/bug, area/documentation, priority/high, area/controller

#2987 feat(ui): 'http' and 'yaml-update' promotion directives support
  ui/src/features/promotion-directives/registry/use-discover-registries.ts
Labels: kind/enhancement, area/ui, priority/high

#3000 refactor(controller): fix order of imageFrom() func signatures
  internal/directives/promotions.go
Labels: kind/refactor, priority/normal, area/controller

#3003 fix(controller): add `IgnoreDelete` predicate
  internal/controller/promotions/promotions.go
  internal/controller/stages/control_flow_stages.go
  internal/controller/stages/regular_stages.go
  internal/controller/warehouses/warehouses.go
  internal/predicate/ignore_delete.go
Labels: kind/bug, priority/normal, area/controller, area/regression

#3012 fix(controller)!: check create setting when attempting to clone non-existent remote branch
  internal/directives/git_cloner.go
  internal/directives/git_cloner_test.go
Labels: kind/bug, priority/high, area/controller, backport/release-1.1

#3015 docs: adjusts deprecation notices
  docs/docs/35-references/10-promotion-steps.md
  internal/directives/argocd_updater.go
  internal/directives/git_cloner.go
  internal/directives/helm_chart_updater.go
  internal/directives/helm_common.go
  internal/directives/helm_image_updater.go
  internal/directives/kustomize_image_setter.go
Labels: area/documentation, kind/chore, priority/high, backport/release-1.1

#3017 chore: stop using deprecated setting for cert-manager chart
  Makefile
  hack/quickstart/install.sh
  hack/quickstart/k3d.sh
  hack/quickstart/kind.sh
Labels: area/documentation, kind/chore, priority/normal, backport/release-1.1

#3019 fix(controller): manual backport of git-clone fix from #3012
  internal/directives/git_cloner.go
  internal/directives/git_cloner_test.go
Labels: kind/bug, priority/normal, area/controller
