Repository akuity/kargo, pull requests merged in 2024-06, with the labels that each got.

#2082 fix: reduce scope of artifact registry access token
  internal/credentials/gar/service_account_key.go
Labels: kind/bug, area/security, priority/high, area/controller

#2077 docs: document cred management with cli + specific support for ecr and google artifact registry
  docs/docs/30-how-to-guides/20-managing-credentials.md
Labels: area/documentation, kind/enhancement, area/security, priority/high

#2076 feat: allow multiple owners of a project namespace
  internal/controller/management/projects/projects.go
  internal/controller/management/projects/projects_test.go
  internal/webhook/project/webhook.go
  internal/webhook/project/webhook_test.go
Labels: kind/enhancement, area/security, priority/normal, area/webhooks, area/controller

#2089 feat: add approved by column in the UI of the stage
  ui/src/features/stage/promotions.tsx
Labels: area/ui, priority/normal, kind/feature-request

#2096 fix(chart): provide empty default annotations map for api server ingress
  charts/kargo/README.md
  charts/kargo/values.yaml
Labels: kind/bug, priority/high, area/charts

#1919 refactor(controller): avoid patching Stage from Promotions reconciler
  api/v1alpha1/stage_types.go
  api/v1alpha1/stage_types_test.go
  internal/controller/promotions/promotions.go
  internal/controller/stages/stages.go
  internal/controller/stages/stages_test.go
  internal/kargo/kargo.go
  internal/kargo/kargo_test.go
Labels: kind/enhancement, kind/refactor, priority/normal

#2097 chore(ui): add cache headers for static assets
  internal/api/server.go
  internal/http/http.go
Labels: kind/enhancement, area/ui, priority/normal, area/api

#2099 fix(ui): better handle long freight content tags
  ui/src/features/common/truncate-middle.tsx
  ui/src/features/freightline/freight-contents.tsx
  ui/src/features/freightline/freightline-header.tsx
Labels: kind/bug, area/ui, priority/normal

#2101 refactor(ui): Require all content during freight assembly, and default to latest
  ui/src/features/create-freight/chart-table.tsx
  ui/src/features/create-freight/commit-table.tsx
  ui/src/features/create-freight/create-freight.tsx
  ui/src/features/create-freight/image-table.tsx
Labels: kind/refactor, area/ui, priority/normal

#2102 fix: refresh promotions using api server's own internal client
  internal/api/refresh_stage_v1alpha1.go
Labels: kind/bug, priority/normal, area/api

#2103 chore: release chores 0.7
  docs/docs/20-quickstart.mdx
  docs/docs/30-how-to-guides/10-installing-kargo.md
  hack/quickstart/install.sh
  hack/quickstart/k3d.sh
  hack/quickstart/kind.sh
Labels: area/documentation, kind/chore, priority/high

#2104 chore: lock v0.6.x docs into v0.6.x scripts
  docs/docs/20-quickstart.mdx
Labels: area/documentation, kind/chore, priority/normal

#2109 feat(ui): surface promotion status in DAG nodes
  ui/src/features/common/promotion-status/promotion-status-icon.tsx
  ui/src/features/project/pipelines/nodes/stage-node.tsx
  ui/src/features/stage/promotions.tsx
Labels: kind/enhancement, area/ui, priority/normal, backport/release-0.7

#2110 feat(ui): ability to delete freight
  ui/src/features/freightline/freightline.tsx
  ui/src/features/project/pipelines/delete-freight-modal.tsx
  ui/src/features/project/pipelines/freight-action-menu.tsx
Labels: kind/enhancement, area/ui, priority/normal, backport/release-0.7

#2113 chore: bump references in docs from v0.7.0-rc.1 to v0.7.0-rc.2
  docs/docs/20-quickstart.mdx
  docs/docs/30-how-to-guides/10-installing-kargo.md
  hack/quickstart/install.sh
  hack/quickstart/k3d.sh
  hack/quickstart/kind.sh
Labels: area/documentation, kind/chore, priority/normal

#2114 chore: remove fig integration
  .github/workflows/release.yaml
  cmd/cli/root.go
  go.mod
  go.sum
Labels: kind/chore, area/release-process, priority/normal, area/cli, backport/release-0.7

#2124 fix(chart): quote subs and groups mapped to service accounts
  charts/kargo/templates/users/service-accounts.yaml
Labels: kind/bug, priority/high, area/charts, backport/release-0.7

#2122 docs: roadmap adjustments
  docs/docs/50-roadmap.md
Labels: area/documentation, kind/chore, priority/high, backport/release-0.7

#2141 fix: allow obtaining diff paths for root commit
  internal/controller/git/git.go
Labels: kind/bug, priority/normal, area/controller, backport/release-0.7

#2139 feat: support github apps as auth method
  docs/docs/30-how-to-guides/20-managing-credentials.mdx
  docs/src/components/Highlight.js
  docs/src/theme/MDXComponents.js
  go.mod
  go.sum
  internal/credentials/credentials.go
  internal/credentials/credentials_test.go
  internal/credentials/github/app.go
  internal/credentials/github/app_test.go
Labels: kind/enhancement, area/security, priority/high, area/controller

#2105 fix: Fix missing pod annotations from API server and add support for podLabels in Helm chart
  charts/kargo/README.md
  charts/kargo/templates/_helpers.tpl
  charts/kargo/templates/api/deployment.yaml
  charts/kargo/templates/controller/deployment.yaml
  charts/kargo/templates/garbage-collector/cron-job.yaml
  charts/kargo/templates/management-controller/deployment.yaml
  charts/kargo/templates/webhooks-server/deployment.yaml
  charts/kargo/values.yaml
Labels: kind/enhancement, priority/normal, area/charts

#2145 fix(controller): support parsing github enterprise urls
  internal/gitprovider/github/github.go
  internal/gitprovider/github/github_test.go
Labels: kind/bug, priority/normal, area/controller, backport/release-0.7

#2149 docs: DRY things up a bit by swizzling
  docs/STYLE_GUIDE.md
  docs/docs/20-quickstart.md
  docs/docs/30-how-to-guides/20-managing-credentials.md
  docs/docs/40-contributor-guide/10-hacking-on-kargo.md
  docs/docs/40-contributor-guide/index.md
  docs/src/theme/MDXComponents/A.js
  docs/src/theme/MDXComponents/Code.js
  docs/src/theme/MDXComponents/Details.js
  docs/src/theme/MDXComponents/Heading.js
  docs/src/theme/MDXComponents/Img/index.js
  docs/src/theme/MDXComponents/Img/styles.module.css
  docs/src/theme/MDXComponents/Pre.js
  docs/src/theme/MDXComponents/Ul/index.js
  docs/src/theme/MDXComponents/Ul/styles.module.css
  docs/src/theme/MDXComponents/index.js
Labels: area/documentation, kind/refactor, priority/normal

#2155 fix: do not check project namespaces for sas when operating on cluster-scoped resources
  internal/api/kubernetes/client.go
Labels: kind/bug, area/security, kind/refactor, priority/normal, area/api

#2153 fix(chart): add warehouse perms to webhook-server
  charts/kargo/templates/webhooks-server/cluster-role.yaml
Labels: kind/bug, priority/normal, area/charts

#2170 fix(controller): make pull request-based promotions honor cert ignore option
  internal/controller/promotion/git.go
  internal/controller/promotion/pullrequest.go
  internal/gitprovider/github/github.go
  internal/gitprovider/gitlab/gitlab.go
  internal/gitprovider/gitprovider.go
  internal/gitprovider/registry.go
Labels: kind/bug, priority/normal, area/controller

#2169 fix(ui): "approved by" -> "created by" for promotions
  ui/src/features/stage/promotions.tsx
Labels: kind/bug, area/ui, priority/normal

#2175 feat(ui): live manifest viewer from warehouse details
  ui/src/features/common/code-editor/yaml-editor-lazy.tsx
  ui/src/features/project/pipelines/warehouse/edit-warehouse.tsx
  ui/src/features/project/pipelines/warehouse/warehouse-actions.tsx
  ui/src/features/project/pipelines/warehouse/warehouse-details.tsx
Labels: kind/enhancement, area/ui, priority/high

#2173 fix(ui): incorrect label on hide subscription button tooltip
  ui/src/features/project/pipelines/nodes/stage-node.tsx
Labels: kind/bug, area/ui, priority/normal

#2181 fix: quickstart k3d argo script
  hack/quickstart/k3d.sh
Labels: kind/bug, area/documentation, priority/high, backport/release-0.7

#2179 fix(promo): record failure message for Argo CD Application
  internal/controller/promotion/argocd.go
Labels: kind/enhancement, priority/normal, area/controller

#2156 feat(controller): SSH support for Git repositories in Warehouses
  Dockerfile
  api/v1alpha1/generated.proto
  api/v1alpha1/warehouse_types.go
  charts/kargo/resources/crds/kargo.akuity.io_warehouses.yaml
  internal/controller/git/git.go
  ui/src/gen/schema/warehouses.kargo.akuity.io_v1alpha1.json
  ui/src/gen/v1alpha1/generated_pb.ts
Labels: kind/enhancement, area/security, priority/normal, area/controller, area/crds

#2154 feat: beginning of support for multiple pipelines/freight per stage
  api/service/v1alpha1/service.proto
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/stage_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
  internal/api/promote_downstream_v1alpha1.go
  internal/api/promote_downstream_v1alpha1_test.go
  internal/api/promote_to_stage_v1alpha1.go
  internal/api/promote_to_stage_v1alpha1_test.go
  internal/api/query_freights_v1alpha1.go
  internal/api/query_freights_v1alpha1_test.go
  internal/api/server.go
  internal/api/server_test.go
  internal/cli/cmd/promote/promote.go
  internal/cli/option/flag.go
  internal/controller/promotions/promotions.go
  internal/controller/stages/stages.go
  internal/controller/stages/stages_test.go
  internal/kubeclient/indexer.go
  internal/kubeclient/indexer_test.go
  internal/webhook/stage/webhook.go
  internal/webhook/stage/webhook_test.go
  pkg/api/service/v1alpha1/service.pb.go
  pkg/api/service/v1alpha1/svcv1alpha1connect/service.connect.go
  ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
  ui/src/gen/service/v1alpha1/service-KargoService_connectquery.ts
  ui/src/gen/service/v1alpha1/service_connect.ts
  ui/src/gen/service/v1alpha1/service_pb.ts
  ui/src/gen/v1alpha1/generated_pb.ts
Labels: kind/enhancement, kind/refactor, priority/high, area/webhooks, area/controller, area/api

#2174 feat(ui): ability to edit freight alias from freight details
  ui/src/features/freight/freight-details.tsx
  ui/src/features/project/pipelines/pipelines.tsx
  ui/src/features/project/pipelines/update-freight-alias-modal.tsx
Labels: kind/enhancement, area/ui, priority/low

#2188 refactor(docs): don't use dockerhub in the quickstart or concepts doc
  docs/docs/15-concepts.md
  docs/docs/20-quickstart.md
  ui/src/features/project/pipelines/utils/stage-yaml-example.ts
Labels: area/documentation, kind/refactor, priority/high, backport/release-0.7

#2202 chore: merge main into multi-pipelines feature branch
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  Dockerfile
  api/v1alpha1/generated.proto
  api/v1alpha1/warehouse_types.go
  charts/kargo/resources/crds/kargo.akuity.io_warehouses.yaml
  docs/docs/15-concepts.md
  docs/docs/20-quickstart.md
  docs/pnpm-lock.yaml
  go.mod
  go.sum
  internal/controller/git/git.go
  ui/package.json
  ui/pnpm-lock.yaml
  ui/src/features/common/analysis-modal/analysis-modal.tsx
  ui/src/features/common/analysis-modal/constants.ts
  ui/src/features/common/analysis-modal/criteria-list/criteria-list.module.less
  ui/src/features/common/analysis-modal/criteria-list/criteria-list.tsx
  ui/src/features/common/analysis-modal/header/header.tsx
  ui/src/features/common/analysis-modal/legend/legend.tsx
  ui/src/features/common/analysis-modal/metric-chart/metric-chart.module.less
  ui/src/features/common/analysis-modal/metric-chart/metric-chart.tsx
  ui/src/features/common/analysis-modal/metric-label/metric-label.module.less
  ui/src/features/common/analysis-modal/metric-label/metric-label.tsx
  ui/src/features/common/analysis-modal/metric-table/metric-table.module.less
  ui/src/features/common/analysis-modal/metric-table/metric-table.tsx
  ui/src/features/common/analysis-modal/panels/index.tsx
  ui/src/features/common/analysis-modal/panels/metric-panel.tsx
  ui/src/features/common/analysis-modal/panels/styles.module.less
  ui/src/features/common/analysis-modal/panels/summary-panel.tsx
  ui/src/features/common/analysis-modal/query-box/query-box.module.less
  ui/src/features/common/analysis-modal/query-box/query-box.tsx
  ui/src/features/common/analysis-modal/status-indicator/status-indicator.module.less
  ui/src/features/common/analysis-modal/status-indicator/status-indicator.tsx
  ui/src/features/common/analysis-modal/transforms.test.ts
  ui/src/features/common/analysis-modal/transforms.ts
  ui/src/features/common/analysis-modal/types.ts
  ui/src/features/common/analysis-modal/utils.ts
  ui/src/features/freight/freight-details.tsx
  ui/src/features/project/pipelines/images.tsx
  ui/src/features/project/pipelines/pipelines.tsx
  ui/src/features/project/pipelines/types.ts
  ui/src/features/project/pipelines/update-freight-alias-modal.tsx
  ui/src/features/project/pipelines/utils/stage-yaml-example.ts
  ui/src/features/project/pipelines/utils/useImages.ts
  ui/src/features/stage/stage-details.tsx
  ui/src/features/stage/verifications.tsx
  ui/src/gen/schema/warehouses.kargo.akuity.io_v1alpha1.json
  ui/src/gen/v1alpha1/generated_pb.ts
Labels: kind/chore, priority/normal

#2203 chore: cleanup multi-pipeline work
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/stage_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
  internal/controller/stages/stages.go
  internal/controller/stages/stages_test.go
  ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
  ui/src/gen/v1alpha1/generated_pb.ts
Labels: kind/chore, priority/normal, area/controller, area/crds

#2204 feat(ui): convenience page for links to CLI binaries
  ui/src/app.tsx
  ui/src/config/paths.ts
  ui/src/features/common/layout/main-layout.tsx
  ui/src/pages/downloads.tsx
Labels: kind/enhancement, area/ui, priority/normal

#2207 fix(ui): use ECR nginx image for warehouse example
  ui/src/features/project/pipelines/utils/warehouse-yaml-example.ts
Labels: kind/bug, area/ui, priority/normal

#2208 fix(ui): use correct JSON schema URL in YAML editors
  ui/src/features/common/code-editor/yaml-editor-lazy.tsx
  ui/src/features/project/list/create-project-modal.tsx
  ui/src/features/project/pipelines/create-stage-modal.tsx
  ui/src/features/project/pipelines/create-warehouse-modal.tsx
  ui/src/features/project/pipelines/warehouse/edit-warehouse.tsx
  ui/src/features/project/settings/components/edit-project-modal.tsx
  ui/src/features/stage/edit-stage-modal.tsx
Labels: kind/bug, area/ui, priority/normal

#2206 refactor: refactor verification process to be suitable for multiple pipelines
  Dockerfile
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/stage_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/kargo/resources/crds/kargo.akuity.io_promotions.yaml
  charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
  internal/controller/promotions/promotions.go
  internal/controller/stages/stages.go
  internal/controller/stages/stages_test.go
  internal/controller/stages/verification.go
  internal/controller/stages/verification_test.go
  internal/kubeclient/indexer.go
  internal/kubeclient/indexer_test.go
  ui/src/gen/schema/promotions.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
  ui/src/gen/v1alpha1/generated_pb.ts
Labels: kind/refactor, priority/normal, area/controller, area/crds

#2210 chore(api): backfill API tests for FreightHistory
  api/v1alpha1/stage_types.go
  api/v1alpha1/stage_types_test.go
Labels: kind/chore, priority/normal, area/controller

#2215 chore: change labels used by feature request template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: kind/chore, area/devx, priority/normal

#2213 refactor: make origin a struct instead of a string
  api/v1alpha1/freight_types.go
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/stage_types.go
  api/v1alpha1/stage_types_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/kargo/resources/crds/kargo.akuity.io_freights.yaml
  charts/kargo/resources/crds/kargo.akuity.io_promotions.yaml
  charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
  internal/api/promote_downstream_v1alpha1_test.go
  internal/api/promote_to_stage_v1alpha1.go
  internal/api/promote_to_stage_v1alpha1_test.go
  internal/api/query_freights_v1alpha1.go
  internal/api/query_freights_v1alpha1_test.go
  internal/controller/promotions/promotions.go
  internal/controller/stages/stages.go
  internal/controller/stages/stages_test.go
  internal/controller/stages/watches.go
  internal/controller/warehouses/warehouses.go
  internal/kubeclient/indexer.go
  internal/kubeclient/indexer_test.go
  internal/webhook/freight/webhook.go
  internal/webhook/freight/webhook_test.go
  internal/webhook/stage/webhook.go
  internal/webhook/stage/webhook_test.go
  ui/src/gen/schema/freights.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/promotions.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
  ui/src/gen/v1alpha1/generated_pb.ts
Labels: kind/refactor, priority/normal, area/webhooks, area/controller, area/api, area/crds

#2217 refactor(controller): support multi-Freight health checks
  api/v1alpha1/stage_types.go
  api/v1alpha1/stage_types_test.go
  internal/argocd/health.go
  internal/argocd/health_test.go
  internal/controller/stages/health_test.go
  internal/controller/stages/stages.go
Labels: kind/refactor, priority/normal, area/controller

#2218 chore: clarify optionality
  api/v1alpha1/generated.proto
  api/v1alpha1/warehouse_types.go
  charts/kargo/resources/crds/kargo.akuity.io_warehouses.yaml
  ui/src/gen/schema/warehouses.kargo.akuity.io_v1alpha1.json
  ui/src/gen/v1alpha1/generated_pb.ts
Labels: kind/chore, priority/normal, area/crds

#2221 chore: merge latest from main to multi-pipelines feature branch
  .github/ISSUE_TEMPLATE/feature_request.md
  api/v1alpha1/generated.proto
  api/v1alpha1/warehouse_types.go
  charts/kargo/resources/crds/kargo.akuity.io_warehouses.yaml
  ui/eslint.config.mjs
  ui/hack/generate-proto-extensions.mjs
  ui/package.json
  ui/pnpm-lock.yaml
  ui/src/app.tsx
  ui/src/config/paths.ts
  ui/src/features/common/code-editor/yaml-editor-lazy.tsx
  ui/src/features/common/layout/main-layout.tsx
  ui/src/features/project/list/create-project-modal.tsx
  ui/src/features/project/pipelines/create-stage-modal.tsx
  ui/src/features/project/pipelines/create-warehouse-modal.tsx
  ui/src/features/project/pipelines/utils/warehouse-yaml-example.ts
  ui/src/features/project/pipelines/warehouse/edit-warehouse.tsx
  ui/src/features/project/settings/components/edit-project-modal.tsx
  ui/src/features/stage/edit-stage-modal.tsx
  ui/src/gen/schema/warehouses.kargo.akuity.io_v1alpha1.json
  ui/src/gen/v1alpha1/generated_pb.ts
  ui/src/pages/downloads.tsx
  ui/vite.config.ts
Labels: kind/chore, priority/normal

#2212 feat(ui): add freight contents to stage node tooltip
  ui/src/features/common/freight-label.tsx
  ui/src/features/freightline/freight-contents.tsx
  ui/src/features/project/pipelines/nodes/stage-node.tsx
Labels: kind/enhancement, area/ui, priority/normal

#2205 fix(health): sync cooldown before health check
  internal/argocd/health.go
  internal/argocd/health_test.go
  internal/controller/argocd/api/v1alpha1/application_types.go
  internal/controller/argocd/api/v1alpha1/zz_generated.deepcopy.go
Labels: kind/bug, priority/high, area/controller, workaround
