Repository akuity/kargo, pull requests merged in 2024-05, with the labels that each got.

#1898 feat(ui): Edit AnalysisTemplate
  ui/src/features/common/code-editor/yaml-editor-lazy.tsx
  ui/src/features/common/manifest-preview.tsx
  ui/src/features/project/analysis-templates/analysis-templates-list.tsx
  ui/src/features/project/analysis-templates/edit-analysis-template-modal.tsx
  ui/src/features/project/analysis-templates/preview-analysis-template-modal.tsx
  ui/src/features/project/credentials/credentials-list.tsx
  ui/src/features/stage/analysis-run-modal.tsx
  ui/src/features/stage/edit-stage-modal.tsx
  ui/src/features/stage/utils/edit-stage-utils.ts
  ui/src/utils/decode-raw-data.ts
Labels: kind/enhancement, area/ui, priority/normal

#1915 refactor: update protobuf defs to avoid snake case
  api/service/v1alpha1/service.proto
Labels: kind/refactor, priority/normal, area/api

#1917 refactor: make Kargo Roles proper runtime objects
  Makefile
  api/buf.yaml
  api/rbac/v1alpha1/annotations.go
  api/rbac/v1alpha1/generated.pb.go
  api/rbac/v1alpha1/generated.proto
  api/rbac/v1alpha1/groupversion_info.go
  api/rbac/v1alpha1/role_types.go
  api/rbac/v1alpha1/zz_generated.deepcopy.go
  api/service/v1alpha1/service.proto
  api/v1alpha1/annotations.go
  hack/codegen/proto.sh
  internal/api/create_role_v1alpha1.go
  internal/api/get_role_v1alpha1.go
  internal/api/grant_v1alpha1.go
  internal/api/list_roles_v1alpha1.go
  internal/api/rbac/roles.go
  internal/api/rbac/roles_test.go
  internal/api/revoke_v1alpha1.go
  internal/api/update_role_v1alpha1.go
  internal/cli/cmd/create/role.go
  internal/cli/cmd/delete/role.go
  internal/cli/cmd/get/get.go
  internal/cli/cmd/get/roles.go
  internal/cli/cmd/grant/grant.go
  internal/cli/cmd/revoke/revoke.go
  internal/cli/kubernetes/scheme.go
  internal/cli/rbac/role.go
  internal/kubeclient/indexer.go
  pkg/api/service/v1alpha1/service.pb.go
  ui/src/gen/k8s.io/api/rbac/v1/generated_pb.ts
  ui/src/gen/rbac/generated_pb.ts
  ui/src/gen/rbac/v1alpha1/generated_pb.ts
  ui/src/gen/service/v1alpha1/service_pb.ts
Labels: kind/bug, kind/refactor, priority/high, area/cli, area/api

#1913 docs: document role management cli commands
  docs/docs/30-how-to-guides/30-managing-user-permissions.md
Labels: area/documentation, kind/enhancement, priority/high

#1914 feat(ui): Project Settings
  ui/src/features/project/settings/components/delete-project-modal.tsx
  ui/src/features/project/settings/components/edit-project-modal.tsx
  ui/src/features/project/settings/project-settings.tsx
  ui/src/pages/project.tsx
Labels: kind/enhancement, area/ui, priority/normal

#1848 fix(promotions): log event for Argo CD Application
  internal/controller/argocd/api/v1alpha1/audit_events.go
  internal/controller/promotion/argocd.go
  internal/controller/promotion/argocd_test.go
Labels: kind/bug, priority/high, area/controller

#1923 fix(promotions): only check revision match sync result if found
  internal/controller/promotion/argocd.go
  internal/controller/promotion/argocd_test.go
Labels: kind/bug, priority/high, area/controller

#1912 feat: add upgrade logic to project reconciler in management controller
  api/v1alpha1/helpers.go
  api/v1alpha1/labels.go
  charts/kargo/templates/management-controller/cluster-roles.yaml
  internal/controller/management/projects/projects.go
  internal/controller/management/projects/projects_test.go
Labels: kind/enhancement, priority/high, area/controller, area/charts

#1925 chore: release chores 0.5
  docs/docs/20-quickstart.mdx
  docs/docs/30-how-to-guides/10-installing-kargo.md
  hack/quickstart/install.sh
  hack/quickstart/k3d.sh
  hack/quickstart/kind.sh
Labels: area/documentation, kind/chore, area/release-process, priority/normal

#1926 chore: release chores 0.6
  docs/docs/20-quickstart.mdx
  docs/docs/30-how-to-guides/10-installing-kargo.md
  hack/quickstart/install.sh
  hack/quickstart/k3d.sh
  hack/quickstart/kind.sh
Labels: area/documentation, kind/chore, area/release-process, priority/normal

#1928 fix: pin to pnpm 9.0.3 anywhere it is used
  Dockerfile
  Dockerfile.dev
  ui/package.json
Labels: kind/bug, area/devx, area/ci-process, area/release-process, priority/urgent

#1918 feat(controller): Apply Warehouse Git subscription path filters to all CommitSelectionStrategy types
  internal/controller/warehouses/git.go
  internal/controller/warehouses/git_test.go
Labels: kind/enhancement, priority/normal, area/controller

#1937 fix(api): fix bug in kargo role update logic
  internal/api/rbac/roles.go
  internal/api/rbac/roles_test.go
Labels: kind/bug, priority/high, area/api

#1938 chore: remove dead generated code
  ui/src/gen/api/v1alpha1/generated_pb.ts
  ui/src/gen/controller/rollouts/api/v1alpha1/generated_pb.ts
  ui/src/gen/rbac/generated_pb.ts
  ui/src/gen/rollouts/v1alpha1/generated_pb.ts
  ui/src/gen/v1alpha1/types_pb.ts
Labels: kind/chore, area/ui, priority/normal

#1944 fix(chart): update and clean up global admin and viewer roles
  charts/kargo/templates/api/cluster-role.yaml
  charts/kargo/templates/users/cluster-roles.yaml
Labels: kind/bug, area/security, priority/high, area/charts

#1933 docs: document minor and major release procedures
  docs/docs/40-contributor-guide/15-release-procedures.md
Labels: area/documentation, kind/enhancement, priority/normal

#1932 docs: roadmap adjustments
  docs/docs/50-roadmap.md
Labels: area/documentation, kind/chore, priority/high

#1948 fix(controller): add missing annotation to role bindings
  internal/controller/management/projects/projects.go
Labels: kind/bug, area/security, priority/high, area/controller

#1947 refactor: improve ux for managing roles
  api/rbac/v1alpha1/generated.pb.go
  api/rbac/v1alpha1/generated.proto
  api/rbac/v1alpha1/role_types.go
  docs/docs/30-how-to-guides/30-managing-user-permissions.md
  internal/api/rbac/policy_rules.go
  internal/api/rbac/policy_rules_test.go
  internal/api/rbac/roles.go
  internal/api/rbac/roles_test.go
  internal/cli/cmd/grant/grant.go
  internal/cli/cmd/revoke/revoke.go
  internal/cli/option/flag.go
  ui/src/gen/rbac/v1alpha1/generated_pb.ts
Labels: area/security, kind/refactor, priority/high, area/cli, area/api, area/ux

#1952 chore: release chores 0.6 rc2
  docs/docs/20-quickstart.mdx
  docs/docs/30-how-to-guides/10-installing-kargo.md
  hack/quickstart/install.sh
  hack/quickstart/k3d.sh
  hack/quickstart/kind.sh
Labels: kind/chore, area/release-process, priority/high

#1953 chore: bulk backporting of recent changes from main
  api/rbac/v1alpha1/generated.pb.go
  api/rbac/v1alpha1/generated.proto
  api/rbac/v1alpha1/role_types.go
  charts/kargo/templates/api/cluster-role.yaml
  charts/kargo/templates/users/cluster-roles.yaml
  docs/docs/30-how-to-guides/30-managing-user-permissions.md
  docs/docs/50-roadmap.md
  internal/api/rbac/policy_rules.go
  internal/api/rbac/policy_rules_test.go
  internal/api/rbac/roles.go
  internal/api/rbac/roles_test.go
  internal/cli/cmd/grant/grant.go
  internal/cli/cmd/revoke/revoke.go
  internal/cli/option/flag.go
  internal/controller/management/projects/projects.go
  internal/controller/management/projects/projects_test.go
  internal/controller/warehouses/git.go
  internal/controller/warehouses/git_test.go
  ui/public/favicon.ico
  ui/public/kargo-icon.png
  ui/src/app.tsx
  ui/src/config/paths.ts
  ui/src/features/common/confirm-modal/confirm-modal.tsx
  ui/src/features/common/form/field-container.tsx
  ui/src/features/common/form/multi-string-editor.tsx
  ui/src/features/common/utils.ts
  ui/src/features/project/credentials/create-credentials-modal.tsx
  ui/src/features/project/pipelines/pipelines.tsx
  ui/src/features/project/roles/create-role.tsx
  ui/src/features/project/roles/delete-role-modal.tsx
  ui/src/features/project/roles/roles.tsx
  ui/src/features/project/roles/rule-editor.tsx
  ui/src/features/project/roles/rules-modal.tsx
  ui/src/features/project/roles/rules-table.tsx
  ui/src/features/stage/stage-actions.tsx
  ui/src/gen/api/v1alpha1/generated_pb.ts
  ui/src/gen/controller/rollouts/api/v1alpha1/generated_pb.ts
  ui/src/gen/rbac/generated_pb.ts
  ui/src/gen/rbac/v1alpha1/generated_pb.ts
  ui/src/gen/rollouts/v1alpha1/generated_pb.ts
  ui/src/gen/v1alpha1/types_pb.ts
  ui/src/pages/login/login.module.less
  ui/src/pages/login/login.tsx
  ui/src/pages/project.tsx
Labels: kind/chore, area/release-process, priority/high

#1943 feat(stage): carry over message from AnalysisRun
  internal/controller/stages/verification.go
Labels: kind/enhancement, priority/normal, area/controller

#1956 fix(ui): freight contents corner radius cut off
  ui/src/features/freightline/freight-contents.tsx
  ui/src/features/freightline/stage-indicators.tsx
Labels: area/ui

#1961 feat(ui): Various improvements to Promote Subscribers UX
  ui/src/features/freightline/freightline-header.tsx
  ui/src/features/project/pipelines/nodes/stage-node.tsx
  ui/src/features/project/pipelines/pipelines.tsx
Labels: kind/enhancement, area/ui, priority/normal, area/usability

#1969 fix(ui): address infinite refresh issue warehouse
  ui/src/features/project/pipelines/types.ts
Labels: kind/bug, area/ui, priority/high

#1970 fix(ui): backport infinite warehouse refresh fix from `main` to `release-0.6`
  ui/src/features/project/pipelines/types.ts
Labels: kind/bug, area/ui, priority/high

#1971 chore: release chores v0.6.0
  docs/docs/20-quickstart.mdx
  docs/docs/30-how-to-guides/10-installing-kargo.md
  hack/quickstart/install.sh
  hack/quickstart/k3d.sh
  hack/quickstart/kind.sh
Labels: area/documentation, kind/chore, area/release-process, priority/normal

#1972 chore: revert pointers to v0.6.0 RCs
  docs/docs/20-quickstart.mdx
  docs/docs/30-how-to-guides/10-installing-kargo.md
  hack/quickstart/install.sh
  hack/quickstart/k3d.sh
  hack/quickstart/kind.sh
Labels: area/documentation, kind/chore, area/release-process, priority/normal

#1975 feat: use config value if no address passed to login command
  cmd/cli/root.go
  internal/cli/cmd/login/login.go
  internal/cli/option/option.go
Labels: kind/enhancement, priority/low, area/cli

#1973 feat(ui): display descriptions for kargo objects (and allow edit/update on certain resources)
  ui/src/features/common/description-expandable.tsx
  ui/src/features/common/description.tsx
  ui/src/features/common/utils.ts
  ui/src/features/freight/freight-details.tsx
  ui/src/features/project/analysis-templates/analysis-templates-list.tsx
  ui/src/features/project/credentials/credentials-list.tsx
  ui/src/features/project/roles/create-role.tsx
  ui/src/features/project/roles/roles.tsx
  ui/src/features/project/roles/rules-modal.tsx
  ui/src/features/project/roles/rules-table.tsx
  ui/src/features/stage/stage-details.tsx
  ui/src/pages/project.tsx
Labels: kind/enhancement, area/ui, priority/normal

#1927 feat(ui): Warehouse details
  ui/src/app.tsx
  ui/src/config/paths.ts
  ui/src/features/project/pipelines/nodes/repo-node.tsx
  ui/src/features/project/pipelines/pipelines.tsx
  ui/src/features/project/pipelines/warehouse/edit-warehouse-modal.tsx
  ui/src/features/project/pipelines/warehouse/repo-subscriptions.tsx
  ui/src/features/project/pipelines/warehouse/warehouse-actions.tsx
  ui/src/features/project/pipelines/warehouse/warehouse-details.tsx
  ui/src/utils/decode-raw-data.ts
Labels: kind/enhancement, area/ui, priority/normal

#1978 feat: allow updating role description via api
  internal/api/rbac/roles.go
  internal/api/rbac/roles_test.go
Labels: kind/enhancement, priority/normal, area/api

#1983 fix(ui): Better display of long labels
  ui/src/features/common/freight-label.tsx
  ui/src/features/freightline/freight-item.tsx
  ui/src/features/freightline/freightline.module.less
  ui/src/features/freightline/freightline.tsx
  ui/src/features/project/pipelines/nodes/repo-node.module.less
  ui/src/features/project/pipelines/nodes/stage-node.tsx
  ui/src/features/project/pipelines/utils/graph.ts
Labels: kind/bug, area/ui, priority/normal

#1986 feat(ui): remember previous location when token refresh logs you out
  ui/src/config/transport.ts
  ui/src/pages/login/login.tsx
Labels: kind/enhancement, area/ui, priority/normal

#1979 feat(ui): display freight contents in freight details page
  ui/src/features/freight/freight-details.tsx
  ui/src/features/freightline/freight-contents.tsx
  ui/src/features/freightline/freight-item.tsx
  ui/src/features/freightline/freightline.module.less
  ui/src/features/stage/promotions.tsx
Labels: kind/enhancement, area/ui, priority/normal

#1980 feat(ui): ability to retry verifications from UI
  ui/src/features/stage/stage-actions.tsx
  ui/src/features/stage/stage-details.tsx
  ui/src/features/stage/verification-icon.tsx
  ui/src/features/stage/verifications.tsx
Labels: kind/enhancement, area/ui, priority/normal

#1936 feat(devx): allow automated backporting of PRs
  .github/workflows/backport.yaml
Labels: kind/enhancement, area/devx, area/ci-process, priority/normal

#2002 docs: add ecr/gha auth to v0.7 roadmap
  docs/docs/50-roadmap.md
Labels: kind/enhancement, area/ci-process, do not merge yet, priority/normal, backport/release-0.6

#2006 chore: minor ui linting cleanup
  .github/workflows/ci.yaml
  Makefile
Labels: kind/chore, area/ci-process, priority/normal

#2005 fix: use akuitybot PAT for backport worfklow
  .github/workflows/backport.yaml
Labels: kind/bug, area/ci-process, priority/normal

#1977 fix(promotion): prepare credentials for Helm chart dependency update
  internal/controller/promotion/git.go
  internal/controller/promotion/git_test.go
  internal/controller/promotion/helm.go
  internal/controller/promotion/helm_test.go
  internal/controller/promotion/kustomize.go
  internal/controller/promotion/kustomize_test.go
  internal/controller/promotion/render.go
  internal/controller/promotion/render_test.go
  internal/credentials/credentials.go
  internal/helm/helm.go
Labels: kind/bug, kind/enhancement, priority/normal, area/controller

#1994 chore(ui): Improve performance of UI
  .gitignore
  go.mod
  internal/api/server.go
  internal/cli/cmd/login/assets/splash.css
  ui/package.json
  ui/pnpm-lock.yaml
  ui/src/app.less
  ui/src/features/common/layout/error-boundary.tsx
  ui/src/features/common/layout/main-layout.module.less
  ui/src/features/common/layout/main-layout.tsx
  ui/src/features/common/suspense-spin.tsx
  ui/src/features/freight/freight-details.tsx
  ui/src/features/freightline/freight-item.tsx
  ui/src/features/freightline/freightline-wrapper.tsx
  ui/src/features/freightline/freightline.module.less
  ui/src/features/freightline/freightline.tsx
  ui/src/features/project/pipelines/create-stage-modal.tsx
  ui/src/features/project/pipelines/create-warehouse-modal.tsx
  ui/src/features/project/pipelines/pipelines.tsx
  ui/src/features/project/pipelines/warehouse/warehouse-details.tsx
  ui/src/features/stage/stage-details.tsx
  ui/vite.config.ts
Labels: kind/chore, area/ui, priority/normal

#2012 chore: update various dependencies
  go.mod
  go.sum
Labels: kind/chore, dependencies, go

#2013 feat(ui): Ability to abort verification from UI
  ui/src/features/stage/stage-actions.tsx
  ui/src/features/stage/stage-details.tsx
Labels: kind/enhancement, area/ui, priority/normal

#2015 fix(ui): Promotion confirmation message overflowed freight box
  ui/src/features/freightline/freight-item.tsx
  ui/src/features/freightline/freightline.module.less
Labels: kind/bug, area/ui, priority/normal

#2016 chore: upgrade prereqs used for development and quickstart
  Makefile
  hack/quickstart/install.sh
  hack/quickstart/k3d.sh
  hack/quickstart/kind.sh
Labels: area/documentation, kind/chore, area/devx, priority/normal

#2023 chore(ui): vertically compress pipeline page layout (slightly)
  ui/src/features/freightline/freightline-header.tsx
  ui/src/pages/project.tsx
Labels: kind/chore, area/ui, priority/normal

#2025 fix(ui): modals crashing due to missing context from lazy-loading
  ui/src/features/common/portal.tsx
  ui/src/features/project/pipelines/pipelines.tsx
Labels: kind/bug, area/ui, priority/normal

#2026 fix(controller): populate warehouse field in new freight
  internal/controller/warehouses/warehouses.go
Labels: kind/bug, priority/high, area/controller

#2024 fix(ui): correct logic for determining which freight are promo eligible
  ui/src/features/freightline/freightline.tsx
  ui/src/features/project/pipelines/utils/use-promotion-eligible-freight.ts
Labels: kind/bug, area/ui, priority/normal

#2018 refactor: use container image repo client from go-containerregistry
  go.mod
  go.sum
  internal/controller/warehouses/images.go
  internal/image/creds.go
  internal/image/digest_selector.go
  internal/image/image.go
  internal/image/image_test.go
  internal/image/lexical_selector.go
  internal/image/newest_build_selector.go
  internal/image/registry.go
  internal/image/registry_test.go
  internal/image/repository_client.go
  internal/image/repository_client_docker_hub_test.go
  internal/image/repository_client_test.go
  internal/image/selector_docker_hub_test.go
  internal/image/selector_ghcr_test.go
  internal/image/selector_test.go
  internal/image/semver_selector.go
  internal/image/semver_selector_test.go
Labels: kind/refactor, priority/normal, area/controller

#2019 fix(promotion): set namespace on ArgoCD event
  internal/controller/promotion/argocd.go
Labels: kind/bug, priority/normal, area/controller, backport/release-0.6

#2032 fix(ci): ensure backport PR title passes linter
  .github/workflows/backport.yaml
Labels: kind/bug, area/ci-process, priority/normal

#2034 feat(api)!: replace LastFreight in Warehouse w/ ID
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/warehouse_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/kargo/resources/crds/kargo.akuity.io_warehouses.yaml
  internal/controller/warehouses/warehouses.go
  internal/controller/warehouses/warehouses_test.go
  ui/src/gen/schema/warehouses.kargo.akuity.io_v1alpha1.json
  ui/src/gen/v1alpha1/generated_pb.ts
Labels: kind/enhancement, kind/chore, priority/normal, area/controller, area/api

#2028 feat(ui): Filter freightline by warehouse
  ui/package.json
  ui/pnpm-lock.yaml
  ui/src/features/freightline/freightline-header.tsx
  ui/src/features/project/pipelines/pipelines.tsx
Labels: kind/enhancement, area/ui, priority/normal

#1904 feat(chart): allow config of global defaults
  charts/kargo/README.md
  charts/kargo/templates/_helpers.tpl
  charts/kargo/templates/api/deployment.yaml
  charts/kargo/templates/api/ingress.yaml
  charts/kargo/templates/api/service.yaml
  charts/kargo/templates/controller/deployment.yaml
  charts/kargo/templates/dex-server/deployment.yaml
  charts/kargo/templates/garbage-collector/cron-job.yaml
  charts/kargo/templates/management-controller/deployment.yaml
  charts/kargo/templates/webhooks-server/deployment.yaml
  charts/kargo/values.yaml
Labels: kind/enhancement, priority/normal, area/charts

#2038 feat(warehouse): allow discovery interval and limit configurations
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/warehouse_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/kargo/resources/crds/kargo.akuity.io_warehouses.yaml
  internal/controller/warehouses/git.go
  internal/controller/warehouses/git_test.go
  internal/controller/warehouses/helm.go
  internal/controller/warehouses/images.go
  internal/controller/warehouses/warehouses.go
  ui/src/gen/schema/warehouses.kargo.akuity.io_v1alpha1.json
  ui/src/gen/v1alpha1/generated_pb.ts
Labels: kind/enhancement, priority/normal, area/controller, area/api

#2037 feat(controller): add rudimentary ecr and artifact registry support
  go.mod
  go.sum
  internal/credentials/credentials.go
  internal/credentials/credentials_test.go
  internal/credentials/ecr/ecr.go
  internal/credentials/ecr/ecr_test.go
  internal/credentials/gcp/gcp.go
  internal/credentials/gcp/gcp_test.go
Labels: kind/enhancement, area/security, priority/high, area/controller

#2046 chore: update go minor dependencies + codegen process tweaks
  .github/workflows/ci.yaml
  Dockerfile.dev
  Makefile
  charts/kargo/resources/crds/kargo.akuity.io_freights.yaml
  charts/kargo/resources/crds/kargo.akuity.io_projects.yaml
  charts/kargo/resources/crds/kargo.akuity.io_promotions.yaml
  charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
  charts/kargo/resources/crds/kargo.akuity.io_warehouses.yaml
  cmd/controlplane/main.go
  go.mod
  go.sum
  hack/install-tools.sh
  hack/tools.go
  internal/controller/promotions/predicates.go
  internal/controller/promotions/predicates_test.go
  internal/controller/promotions/promotions.go
  internal/controller/promotions/watches.go
  internal/controller/promotions/watches_test.go
  internal/controller/stages/stages.go
  internal/controller/stages/watches.go
  internal/controller/stages/watches_test.go
  internal/kargo/kargo.go
  internal/webhook/promotion/webhook.go
  internal/webhook/stage/webhook.go
  ui/src/gen/k8s.io/api/batch/v1/generated_pb.ts
  ui/src/gen/k8s.io/api/core/v1/generated_pb.ts
  ui/src/gen/k8s.io/api/rbac/v1/generated_pb.ts
  ui/src/gen/k8s.io/apimachinery/pkg/apis/meta/v1/generated_pb.ts
Labels: kind/chore, area/devx, priority/normal, area/cli, dependencies, go

#2035 chore(warehouse): enrich discovery logs
  internal/controller/warehouses/git.go
  internal/controller/warehouses/helm.go
  internal/controller/warehouses/helm_test.go
  internal/controller/warehouses/images.go
  internal/image/newest_build_selector.go
Labels: kind/chore, priority/normal, area/controller

#2048 docs: slightly reorder roadmap entries
  docs/docs/50-roadmap.md
Labels: area/documentation, kind/chore, priority/low, backport/release-0.6

#2051 fix(promo): Argo CD Application not found err fmt
  internal/controller/promotion/argocd.go
Labels: kind/bug, priority/normal, area/controller

#2053 fix(ui): refresh freight after manual approval
  ui/src/features/project/pipelines/pipelines.tsx
Labels: kind/bug, area/ui, priority/normal

#2059 chore: switch from aws-sdk-go v1 to v2
  go.mod
  go.sum
  internal/credentials/credentials.go
  internal/credentials/ecr/access_key.go
  internal/credentials/ecr/access_key_test.go
  internal/credentials/ecr/pod_identity.go
Labels: kind/chore, priority/normal, area/controller

#2066 feat(controller): fully support eks pod identity for ecr access
  cmd/controlplane/controller.go
  internal/controller/promotion/root_test.go
  internal/credentials/credentials.go
  internal/credentials/credentials_test.go
  internal/credentials/ecr/access_key_test.go
  internal/credentials/ecr/pod_identity.go
  internal/credentials/ecr/pod_identity_test.go
Labels: kind/bug, kind/enhancement, kind/refactor, priority/high, area/controller

#2072 fix(chart): dex additional volumes indentation
  charts/kargo/templates/dex-server/deployment.yaml
Labels: kind/bug, priority/normal, area/charts

#2075 fix: graceful failure when rollouts crds are missing
  cmd/controlplane/controller.go
Labels: kind/bug, priority/high, area/controller

#2070 feat(controller): support gcp workload identity federation as auth method for google artifact registry
  go.mod
  go.sum
  internal/credentials/credentials.go
  internal/credentials/ecr/access_key.go
  internal/credentials/ecr/pod_identity.go
  internal/credentials/ecr/pod_identity_test.go
  internal/credentials/gar/common.go
  internal/credentials/gar/service_account_key.go
  internal/credentials/gar/service_account_key_test.go
  internal/credentials/gar/workload_identity_federation.go
  internal/credentials/gar/workload_identity_federation_test.go
Labels: kind/enhancement, priority/high, area/controller

#2071 feat(ui): Freight assembly
  charts/kargo/templates/api/cluster-role.yaml
  ui/src/config/paths.ts
  ui/src/features/create-freight/artifact-menu-group.tsx
  ui/src/features/create-freight/artifact-menu-item.tsx
  ui/src/features/create-freight/chart-table.tsx
  ui/src/features/create-freight/commit-table.tsx
  ui/src/features/create-freight/create-freight.tsx
  ui/src/features/create-freight/image-table.tsx
  ui/src/features/create-freight/truncated-copyable.tsx
  ui/src/features/create-freight/types.ts
  ui/src/features/freightline/freightline-header.tsx
  ui/src/features/project/pipelines/pipelines.tsx
  ui/src/features/project/pipelines/warehouse/repo-subscriptions.tsx
  ui/src/features/project/pipelines/warehouse/warehouse-details.tsx
Labels: kind/enhancement, area/ui, priority/normal

#2081 chore: categorize uncategorized resourced in Tiltfile
  Tiltfile
Labels: kind/chore, area/devx, priority/normal
