Repository akuity/kargo, pull requests merged in 2024-07, with the labels that each got.

#2209 feat(ui): display last promotion completion time instead of freight creation time
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/promotion_types.go
  api/v1alpha1/stage_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/kargo/resources/crds/kargo.akuity.io_promotions.yaml
  charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
  internal/controller/promotions/promotions.go
  internal/controller/stages/stages.go
  internal/controller/stages/stages_test.go
  internal/controller/stages/verification_test.go
  ui/src/features/project/pipelines/nodes/stage-node.module.less
  ui/src/features/project/pipelines/nodes/stage-node.tsx
  ui/src/features/project/pipelines/utils/graph.ts
  ui/src/gen/schema/promotions.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
  ui/src/gen/v1alpha1/generated_pb.ts
Labels: kind/enhancement, area/ui, priority/normal, area/controller

#2230 chore: audit controller and management controller permissions
  api/v1alpha1/helpers.go
  api/v1alpha1/helpers_test.go
  charts/kargo/templates/controller/cluster-roles.yaml
  charts/kargo/templates/management-controller/cluster-roles.yaml
  internal/controller/management/namespaces/namespaces.go
  internal/controller/management/namespaces/namespaces_test.go
  internal/controller/management/projects/projects.go
  internal/controller/management/projects/projects_test.go
  internal/controller/stages/stages.go
Labels: area/security, kind/chore, priority/normal, area/controller, area/charts

#2197 feat(ui): ability to collapse old freight in freightline
  ui/src/features/freightline/freight-item.tsx
  ui/src/features/freightline/freightline-header.tsx
  ui/src/features/freightline/freightline.tsx
  ui/src/features/project/pipelines/pipelines.tsx
Labels: kind/enhancement, area/ui, priority/normal

#2232 feat: make promotions work in multi-pipeline feature branch
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/promotion_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/kargo/resources/crds/kargo.akuity.io_promotions.yaml
  charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
  internal/controller/promotion/argocd.go
  internal/controller/promotion/argocd_test.go
  internal/controller/promotion/composite.go
  internal/controller/promotion/composite_test.go
  internal/controller/promotion/git.go
  internal/controller/promotion/git_test.go
  internal/controller/promotion/helm.go
  internal/controller/promotion/helm_test.go
  internal/controller/promotion/kustomize.go
  internal/controller/promotion/kustomize_test.go
  internal/controller/promotion/render.go
  internal/controller/promotion/render_test.go
  internal/controller/promotion/root.go
  internal/controller/promotion/root_test.go
  internal/controller/promotions/promotions.go
  internal/controller/stages/stages.go
  internal/controller/stages/stages_test.go
  ui/src/gen/schema/promotions.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
  ui/src/gen/v1alpha1/generated_pb.ts
Labels: kind/enhancement, priority/normal, area/controller

#2238 feat: add unique, deterministically calculated ids for freight collections
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/labels.go
  api/v1alpha1/stage_types.go
  charts/kargo/resources/crds/kargo.akuity.io_promotions.yaml
  charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
  internal/controller/stages/verification.go
  internal/controller/stages/verification_test.go
  ui/src/gen/schema/promotions.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
  ui/src/gen/v1alpha1/generated_pb.ts
Labels: kind/enhancement, priority/normal, area/controller, area/crds

#2241 feat: factor origin into freight name
  api/v1alpha1/freight_types.go
  api/v1alpha1/freight_types_test.go
Labels: kind/enhancement, priority/normal, area/webhooks, area/controller

#2236 feat(ui): Support multiple pipelines
  Dockerfile
  internal/api/query_freights_v1alpha1.go
  ui/src/context/colors.ts
  ui/src/features/freight/freight-status-list.tsx
  ui/src/features/freightline/freightline-header.tsx
  ui/src/features/freightline/freightline.tsx
  ui/src/features/freightline/palette.tsx
  ui/src/features/freightline/stage-indicators.tsx
  ui/src/features/project/list/project-item/project-item.tsx
  ui/src/features/project/pipelines/nodes/repo-node.module.less
  ui/src/features/project/pipelines/nodes/repo-node.tsx
  ui/src/features/project/pipelines/nodes/stage-node.module.less
  ui/src/features/project/pipelines/nodes/stage-node.tsx
  ui/src/features/project/pipelines/pipelines.tsx
  ui/src/features/project/pipelines/types.ts
  ui/src/features/project/pipelines/utils/graph.ts
  ui/src/features/project/pipelines/utils/use-pipeline-graph.ts
  ui/src/features/project/pipelines/utils/useImages.ts
  ui/src/features/stage/requested-freight.tsx
  ui/src/features/stage/stage-details.tsx
  ui/src/features/stage/subscriptions.tsx
  ui/src/features/stage/utils/index.ts
Labels: kind/enhancement, area/ui, priority/normal

#2242 docs: roadmap updates
  docs/docs/50-roadmap.md
Labels: area/documentation, kind/enhancement, priority/normal, backport/release-0.7

#2243 fix(argocd): mark suspended App as progressing
  internal/argocd/health.go
  internal/argocd/health_test.go
Labels: kind/bug, priority/normal, area/controller

#2257 feat(cli): add origin support to `kargo get freight`
  api/service/v1alpha1/service.proto
  api/v1alpha1/freight_types.go
  charts/kargo/resources/crds/kargo.akuity.io_freights.yaml
  internal/api/query_freights_v1alpha1.go
  internal/cli/cmd/get/freight.go
  internal/cli/option/flag.go
  pkg/api/service/v1alpha1/service.pb.go
  ui/src/gen/service/v1alpha1/service_pb.ts
Labels: kind/enhancement, priority/high, area/cli, area/api

#2261 chore: merge main
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  Dockerfile
  Dockerfile.dev
  docs/docs/50-roadmap.md
  go.mod
  go.sum
  internal/argocd/health.go
  internal/argocd/health_test.go
  internal/credentials/kubernetes/gar/workload_identity_federation.go
Labels: kind/chore, priority/normal

#2262 fix(ui): edges for multi-pipelines should not be kinked
  ui/src/features/project/pipelines/pipelines.tsx
  ui/src/features/project/pipelines/utils/graph.ts
  ui/src/features/project/pipelines/utils/use-pipeline-graph.ts
Labels: kind/refactor, area/ui, priority/normal

#2268 fix(ui): deprecation of stage.status.currentFreight
  ui/src/features/common/utils.ts
  ui/src/features/project/list/project-item/project-item.tsx
  ui/src/features/project/list/project-item/stage-popover.tsx
  ui/src/features/project/pipelines/nodes/stage-node.tsx
  ui/src/features/project/pipelines/pipelines.tsx
  ui/src/features/project/pipelines/utils/use-pipeline-graph.ts
  ui/src/features/project/pipelines/utils/useImages.ts
  ui/src/features/stage/stage-actions.tsx
  ui/src/features/stage/stage-details.tsx
Labels: kind/bug, area/ui, priority/normal

#2272 fix(ui): error assembling freight
  ui/src/features/create-freight/create-freight.tsx
Labels: kind/bug, area/ui, priority/high

#2274 fix(ui): don't show promote subs button for downstream w/ mult. edges
  ui/src/features/project/pipelines/pipelines.tsx
Labels: kind/bug, area/ui, priority/normal

#2277 fix(ui): freight contents overflowing horizontally
  ui/src/features/freight-timeline/freight-contents.tsx
Labels: area/regression

#2280 fix(controller): allow oci helm repos to be used with aws creds
  internal/credentials/kubernetes/ecr/access_key.go
  internal/credentials/kubernetes/ecr/access_key_test.go
  internal/credentials/kubernetes/ecr/common.go
  internal/credentials/kubernetes/ecr/pod_identity.go
  internal/credentials/kubernetes/ecr/pod_identity_test.go
Labels: kind/enhancement, priority/normal, area/controller

#2282 fix(ui): redirect to login with expired token
  ui/src/features/auth/token-renew.tsx
Labels: kind/bug, area/ui, priority/normal

#2285 feat: if project-scoped ECR auth fails, fallback to default
  internal/credentials/kubernetes/ecr/pod_identity.go
Labels: kind/enhancement, priority/high, area/controller

#2286 chore: merge latest from main to multi-pipelines feature branch
  internal/credentials/kubernetes/ecr/access_key.go
  internal/credentials/kubernetes/ecr/access_key_test.go
  internal/credentials/kubernetes/ecr/common.go
  internal/credentials/kubernetes/ecr/pod_identity.go
  internal/credentials/kubernetes/ecr/pod_identity_test.go
  ui/package.json
  ui/pnpm-lock.yaml
  ui/src/features/auth/token-renew.tsx
  ui/src/features/freight-timeline/freight-contents.tsx
Labels: kind/chore

#2287 fix(ui): correctly display reverify button
  ui/src/features/common/utils.ts
  ui/src/features/stage/stage-actions.tsx
Labels: kind/bug, area/ui, priority/normal

#2288 fix(ui): multiple edges to multiple children
  ui/src/features/project/pipelines/utils/graph.ts
  ui/src/features/project/pipelines/utils/use-pipeline-graph.ts
Labels: kind/bug, area/ui, priority/normal

#2273 feat(stage): support multi-pipeline auto-promotion
  api/v1alpha1/generated.pb.go
  api/v1alpha1/stage_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
  internal/controller/promotions/promotions.go
  internal/controller/promotions/promotions_test.go
  internal/controller/stages/stages.go
  internal/controller/stages/stages_test.go
  internal/kubeclient/indexer.go
  internal/kubeclient/indexer_test.go
  ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
Labels: kind/enhancement, priority/normal, area/controller

#2297 chore: merge latest from main into main multi-pipelines feature branch
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  Dockerfile
  api/v1alpha1/freight_types.go
  api/v1alpha1/freight_types_test.go
  api/v1alpha1/generated.proto
  api/v1alpha1/stage_types.go
  api/v1alpha1/stage_types_test.go
  charts/kargo/resources/crds/kargo.akuity.io_freights.yaml
  charts/kargo/resources/crds/kargo.akuity.io_promotions.yaml
  charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
  go.mod
  go.sum
  internal/webhook/freight/webhook.go
  internal/webhook/freight/webhook_test.go
  ui/package.json
  ui/pnpm-lock.yaml
  ui/src/gen/schema/freights.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/promotions.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
  ui/src/gen/v1alpha1/generated_pb.ts
Labels: kind/chore

#2235 feat(controller): irsa support
  charts/kargo/README.md
  charts/kargo/templates/controller/service-account.yaml
  charts/kargo/values.yaml
  docs/docs/30-how-to-guides/20-managing-credentials.md
  internal/credentials/kubernetes/database.go
  internal/credentials/kubernetes/ecr/managed_identity_credential.go
  internal/credentials/kubernetes/ecr/managed_identity_credential_test.go
Labels: kind/enhancement, priority/high, area/controller

#2304 chore: update docs and scripts to lock release-0.7 branch into latest stabe release
  docs/docs/20-quickstart.mdx
  docs/docs/30-how-to-guides/10-installing-kargo.md
  hack/quickstart/install.sh
  hack/quickstart/k3d.sh
  hack/quickstart/kind.sh
Labels: area/documentation, kind/chore, priority/normal

#2305 chore: update docs and scripts to work with v0.8.0-rc.1
  docs/docs/20-quickstart.md
  docs/docs/30-how-to-guides/10-installing-kargo.md
  hack/quickstart/install.sh
  hack/quickstart/k3d.sh
  hack/quickstart/kind.sh
Labels: area/documentation, kind/chore, priority/normal

#2303 docs: doc updates
  docs/docs/15-concepts.md
  docs/docs/20-quickstart.md
  docs/docs/50-roadmap.md
Labels: area/documentation, kind/refactor, priority/normal, backport/release-0.8

#2306 feat: freight summary on stage status
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/stage_types.go
  charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
  internal/cli/cmd/get/stages.go
  internal/controller/stages/stages.go
  internal/controller/stages/stages_test.go
  ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
  ui/src/gen/v1alpha1/generated_pb.ts
Labels: kind/enhancement, priority/normal, area/controller, area/cli, area/crds

#2308 chore: backport #2306 to release-0.8 branch
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/stage_types.go
  charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
  internal/cli/cmd/get/stages.go
  internal/controller/stages/stages.go
  internal/controller/stages/stages_test.go
  ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
  ui/src/gen/v1alpha1/generated_pb.ts
Labels: kind/enhancement, priority/normal, area/controller, area/cli, area/crds

#2283 feat(ui): ability to hide images table
  ui/src/features/project/pipelines/images.tsx
  ui/src/features/project/pipelines/pipelines.tsx
Labels: kind/enhancement, area/ui, priority/normal, backport/release-0.8

#2309 feat: add v0.7.x --> v0.8.x upgrade logic
  api/v1alpha1/helpers.go
  api/v1alpha1/labels.go
  charts/kargo/templates/controller/cluster-roles.yaml
  charts/kargo/templates/management-controller/cluster-roles.yaml
  cmd/controlplane/controller.go
  cmd/controlplane/management_controller.go
  go.mod
  internal/controller/management/upgrade/freight.go
  internal/controller/promotions/promotions.go
  internal/controller/stages/stages.go
  internal/controller/stages/upgrade.go
  internal/controller/warehouses/warehouses.go
  internal/controller/warehouses/warehouses_test.go
  internal/kubeclient/indexer.go
  internal/webhook/freight/webhook.go
  internal/webhook/freight/webhook_test.go
Labels: kind/enhancement, priority/high, area/controller, area/ux, area/crds

#2278 feat(ui): display links in promo table for pr-based promos
  ui/src/features/stage/pr-links.tsx
  ui/src/features/stage/promotions.tsx
  ui/src/features/stage/stage-details.tsx
Labels: kind/enhancement, area/ui, priority/normal, area/ux

#2301 feat(ui): indicate PR based promotion in Stage nodes
  ui/src/features/project/pipelines/nodes/stage-node.tsx
Labels: kind/enhancement, area/ui, priority/normal, area/ux

#2316 fix(ui): don't fetch freight/promo information if name is null
  ui/src/features/project/list/project-item/stage-popover.tsx
Labels: kind/bug, area/ui, priority/high, backport/release-0.8

#2318 refactor(controller): minor cleanup of aws managed identity credential helper
  internal/credentials/kubernetes/ecr/managed_identity.go
  internal/credentials/kubernetes/ecr/managed_identity_test.go
Labels: kind/refactor, priority/normal, area/controller, backport/release-0.8

#2320 chore: restore main branch (edge) docs and scripts to always point at latet release
  docs/docs/20-quickstart.md
  docs/docs/30-how-to-guides/10-installing-kargo.md
  hack/quickstart/install.sh
  hack/quickstart/k3d.sh
  hack/quickstart/kind.sh
Labels: area/documentation, kind/chore, priority/normal

#2329 fix(ui): crash in stage details popover
  ui/src/features/project/list/project-item/stage-popover.tsx
Labels: kind/bug, area/ui, priority/high, backport/release-0.8

#2300 chore(kubeclient): tidy indexers and add tests
  internal/kubeclient/indexer.go
  internal/kubeclient/indexer_test.go
Labels: kind/chore, priority/normal, area/controller

#2281 feat(ui): ability to zoom pipelines dag
  ui/src/features/project/pipelines/pipelines.tsx
Labels: kind/enhancement, area/ui, priority/normal

#2270 docs: Update README.md
  README.md
  docs/docs/10-overview.md
Labels: area/documentation, kind/chore, priority/normal, backport/release-0.8

#2334 fix(ui): incorrect DAG rendering for singular forward connection to node with multiple backward connections
  ui/src/features/project/pipelines/utils/graph.ts
Labels: kind/bug, area/ui, priority/normal, backport/release-0.8

#2336 fix(ui): properly display stage indicators in timeline after migration
  ui/src/features/project/pipelines/pipelines.tsx
Labels: kind/bug, area/ui, priority/high, backport/release-0.8

#2284 feat(ui): visual + layout improvements
  ui/src/features/create-freight/artifact-menu-group.tsx
  ui/src/features/create-freight/artifact-menu-item.tsx
  ui/src/features/create-freight/create-freight.tsx
  ui/src/features/create-freight/image-table.tsx
  ui/src/features/create-freight/truncated-copyable.tsx
  ui/src/features/freight-timeline/freight-contents.tsx
  ui/src/features/freight-timeline/freight-timeline-header.tsx
  ui/src/features/freight-timeline/freight-timeline-wrapper.tsx
  ui/src/features/freight-timeline/freight-timeline.less
  ui/src/features/freight-timeline/freight-timeline.module.less
  ui/src/features/freight-timeline/freight-timeline.tsx
  ui/src/features/project/list/project-item/stage-popover.tsx
  ui/src/features/project/pipelines/images.tsx
  ui/src/features/project/pipelines/nodes/repo-node.tsx
  ui/src/features/project/pipelines/pipelines.tsx
  ui/src/features/project/settings/project-settings.tsx
  ui/src/pages/downloads.tsx
  ui/src/pages/project.tsx
Labels: kind/enhancement, area/ui, priority/normal

#2342 fix(ui): hide promotion button for control flow stages
  ui/src/features/project/pipelines/nodes/stage-node.tsx
Labels: kind/bug, area/ui, priority/high, backport/release-0.8

#2258 feat(ui): ability to promote freight via dropdown in timeline
  ui/src/features/freight-timeline/freight-item.tsx
  ui/src/features/freight-timeline/freight-timeline-header.tsx
  ui/src/features/freight-timeline/freight-timeline.module.less
  ui/src/features/freight-timeline/freight-timeline.tsx
  ui/src/features/project/pipelines/freight-action-menu.tsx
  ui/src/features/project/pipelines/nodes/stage-node.tsx
  ui/src/features/project/pipelines/pipelines.tsx
  ui/src/features/project/pipelines/types.ts
  ui/src/features/project/pipelines/utils/state.ts
Labels: kind/enhancement, area/ui, priority/normal, area/ux

#2344 fix(ui): stop relying on deprecated field in images table
  ui/src/features/project/pipelines/images.tsx
Labels: kind/bug, priority/high, backport/release-0.8

#2347 fix(ui): update colors hook
  ui/src/features/project/pipelines/images.tsx
Labels: kind/bug, area/ui, priority/high

#2352 docs: Add sample Dex Azure connector.
  charts/kargo/values.yaml
Labels: area/documentation, kind/enhancement, priority/normal, area/charts

#2362 fix(controller): fix panic when last promotion has no freight collection
  internal/controller/promotions/promotions.go
Labels: kind/bug, priority/normal, area/controller, backport/release-0.8

#2348 feat(ui): indicate stages with auto promotion enabled in DAG
  ui/src/features/project/pipelines/nodes/stage-node.tsx
  ui/src/features/project/pipelines/pipelines.tsx
  ui/src/pages/project.tsx
Labels: kind/enhancement, area/ui, priority/normal

#2351 chore(ui): indicate resource type in Warehouse Details view
  ui/src/features/project/pipelines/warehouse/warehouse-details.tsx
Labels: kind/refactor, area/ui, priority/normal

#2349 fix(ui): scroll promotion status messages (matches warehouse behavior)
  ui/src/features/common/promotion-status/promotion-status-icon.tsx
  ui/src/features/project/pipelines/message-tooltip.tsx
  ui/src/features/project/pipelines/nodes/repo-node.tsx
Labels: kind/bug, area/ui, priority/normal

#2350 fix(ui): display friendlier message when assembling freight that already exists
  ui/src/config/transport.ts
  ui/src/features/assemble-freight/artifact-menu-group.tsx
  ui/src/features/assemble-freight/artifact-menu-item.tsx
  ui/src/features/assemble-freight/assemble-freight.tsx
  ui/src/features/assemble-freight/chart-table.tsx
  ui/src/features/assemble-freight/commit-table.tsx
  ui/src/features/assemble-freight/image-table.tsx
  ui/src/features/assemble-freight/truncated-copyable.tsx
  ui/src/features/assemble-freight/types.ts
  ui/src/features/project/pipelines/warehouse/warehouse-details.tsx
Labels: kind/refactor, area/ui, priority/normal
