Repository akuity/kargo, pull requests merged in 2024-09, with the labels that each got.

#2475 fix(ui): hide old freight mode broken when project has empty stages
  ui/src/features/common/utils.ts
  ui/src/features/project/pipelines/pipelines.tsx
Labels: kind/bug, area/ui, priority/normal

#2476 feat(ui): ability to scroll freight timeline with buttons
  ui/src/features/freight-timeline/freight-timeline-header.tsx
  ui/src/features/freight-timeline/freight-timeline-wrapper.tsx
  ui/src/features/freight-timeline/utils.ts
Labels: kind/enhancement, area/ui, priority/normal

#2483 refactor(controller): overhaul git repo interfaces
  Dockerfile
  Tiltfile
  cmd/credential-helper/main.go
  go.mod
  go.sum
  internal/controller/git/bare_repo.go
  internal/controller/git/bare_repo_test.go
  internal/controller/git/base_repo.go
  internal/controller/git/client_opts.go
  internal/controller/git/commit_signing.go
  internal/controller/git/consts.go
  internal/controller/git/credentials.go
  internal/controller/git/git.go
  internal/controller/git/repo.go
  internal/controller/git/repo_test.go
  internal/controller/git/work_tree.go
  internal/controller/git/work_tree_test.go
  internal/controller/promotion/git.go
  internal/controller/promotion/pullrequest.go
Labels: kind/enhancement, kind/refactor, priority/high, area/controller

#2486 feat(controller): more git pkg enhancements
  internal/controller/git/bare_repo.go
  internal/controller/git/bare_repo_test.go
  internal/controller/git/base_repo.go
  internal/controller/git/repo.go
  internal/controller/git/repo_test.go
  internal/controller/git/work_tree.go
  internal/controller/git/work_tree_test.go
  internal/controller/promotion/git.go
  internal/controller/promotion/pullrequest.go
  internal/controller/warehouses/git.go
Labels: kind/enhancement, priority/high, area/controller

#2488 feat(ui): surface verification errors in DAG
  ui/src/features/project/pipelines/nodes/stage-node.tsx
  ui/src/features/project/pipelines/nodes/util.ts
Labels: kind/enhancement, area/ui, priority/normal

#2499 fix(kubeclient): retry patch on conflict
  internal/kubeclient/patch.go
Labels: kind/bug, priority/normal, area/controller, backport/release-0.8

#2493 feat: add convenience targets for working on docs
  Makefile
  docs/package.json
Labels: kind/enhancement, area/devx, priority/normal

#2480 feat(api): add endpoints to get AnalysisTemplate config resources
  api/service/v1alpha1/service.proto
  api/v1alpha1/labels.go
  charts/kargo/templates/api/cluster-role.yaml
  internal/api/get_analysis_template_config_map_v1alpha1.go
  internal/api/get_analysis_template_secret_v1alpha1.go
  internal/api/list_analysis_template_config_maps_v1alpha1.go
  internal/api/list_analysis_template_secrets_v1alpha1.go
  pkg/api/service/v1alpha1/service.pb.go
  pkg/api/service/v1alpha1/svcv1alpha1connect/service.connect.go
  ui/src/gen/service/v1alpha1/service-KargoService_connectquery.ts
  ui/src/gen/service/v1alpha1/service_connect.ts
  ui/src/gen/service/v1alpha1/service_pb.ts
Labels: kind/enhancement, area/charts, area/api

#2517 feat: implement conditional secret management
  api/service/v1alpha1/service.proto
  charts/kargo/README.md
  charts/kargo/templates/api/cluster-role.yaml
  charts/kargo/templates/api/configmap.yaml
  charts/kargo/values.yaml
  internal/api/config/config.go
  internal/api/delete_credentials_v1alpha1.go
  internal/api/get_config_v1alpha1.go
  internal/api/get_credentials_v1alpha1.go
  internal/api/get_credentials_v1alpha1_test.go
  internal/api/list_credentials_v1alpha1.go
  internal/api/update_credentials_v1alpha1.go
  pkg/api/service/v1alpha1/service.pb.go
  ui/src/gen/service/v1alpha1/service_pb.ts
  ui/src/pages/project.tsx
Labels: kind/enhancement, area/security, area/ui, priority/high, area/api

#2315 feat(api)!: Generalise OIDC Claims
  api/rbac/v1alpha1/annotations.go
  api/rbac/v1alpha1/generated.pb.go
  api/rbac/v1alpha1/generated.proto
  api/rbac/v1alpha1/role_types.go
  api/rbac/v1alpha1/zz_generated.deepcopy.go
  api/service/v1alpha1/service.proto
  api/v1alpha1/event.go
  charts/kargo/README.md
  charts/kargo/templates/api/configmap.yaml
  charts/kargo/templates/dex-server/secret.yaml
  charts/kargo/templates/users/service-accounts.yaml
  charts/kargo/values.yaml
  docs/docs/30-how-to-guides/30-managing-user-permissions.md
  hack/tilt/values.dev.yaml
  internal/api/get_public_config_v1alpha1.go
  internal/api/grant_v1alpha1.go
  internal/api/kubernetes/client.go
  internal/api/kubernetes/client_test.go
  internal/api/oidc/config.go
  internal/api/option/auth.go
  internal/api/option/auth_test.go
  internal/api/rbac/roles.go
  internal/api/rbac/roles_test.go
  internal/api/revoke_v1alpha1.go
  internal/api/user/user.go
  internal/api/user/user_test.go
  internal/cli/cmd/create/role.go
  internal/cli/cmd/grant/grant.go
  internal/cli/cmd/revoke/revoke.go
  internal/cli/option/flag.go
  internal/kubeclient/indexer.go
  internal/kubeclient/indexer_test.go
  pkg/api/service/v1alpha1/service.pb.go
  ui/src/features/project/roles/create-role.tsx
  ui/src/features/project/roles/roles.tsx
  ui/src/gen/rbac/v1alpha1/generated_pb.ts
  ui/src/gen/service/v1alpha1/service_pb.ts
Labels: kind/enhancement, area/security, priority/normal, area/charts, area/api

#2531 feat(controller): more git pkg improvements
  internal/controller/git/bare_repo.go
  internal/controller/git/bare_repo_test.go
  internal/controller/git/base_repo.go
  internal/controller/git/work_tree.go
  internal/controller/git/work_tree_test.go
Labels: kind/enhancement, kind/refactor, priority/high, area/controller

#2536 feat: promotion directives foundation
  Makefile
  go.mod
  go.sum
  hack/codegen/directive-configs.sh
  internal/argocd/revision.go
  internal/controller/freight/finder.go
  internal/controller/freight/finder_test.go
  internal/controller/promotion/argocd.go
  internal/controller/promotion/helm.go
  internal/controller/promotion/kustomize.go
  internal/controller/promotion/kustomize_test.go
  internal/controller/promotion/render.go
  internal/directives/copy_directive.go
  internal/directives/copy_directive_test.go
  internal/directives/directive.go
  internal/directives/directive_test.go
  internal/directives/engine.go
  internal/directives/engine_test.go
  internal/directives/git_clone_directive.go
  internal/directives/git_clone_directive_test.go
  internal/directives/git_commit_directive.go
  internal/directives/git_commit_directive_test.go
  internal/directives/git_push_directive.go
  internal/directives/git_push_directive_test.go
  internal/directives/helm_template_directive.go
  internal/directives/helm_template_directive_test.go
  internal/directives/helm_update_chart_directive.go
  internal/directives/helm_update_chart_directive_test.go
  internal/directives/helm_update_image_directive.go
  internal/directives/helm_update_image_directive_test.go
  internal/directives/kustomize_build_directive.go
  internal/directives/kustomize_build_directive_test.go
  internal/directives/kustomize_set_image_directive.go
  internal/directives/kustomize_set_image_directive_test.go
  internal/directives/mock_directive_test.go
  internal/directives/oci_registry_test.go
  internal/directives/registry.go
  internal/directives/registry_test.go
  internal/directives/schema_loader.go
  internal/directives/schemas/common.json
  internal/directives/schemas/copy-directive-config.json
  internal/directives/schemas/git-clone-config.json
  internal/directives/schemas/git-commit-config.json
  internal/directives/schemas/git-push-config.json
  internal/directives/schemas/helm-template-config.json
  internal/directives/schemas/helm-update-chart-config.json
  internal/directives/schemas/helm-update-image-config.json
  internal/directives/schemas/kustomize-build-config.json
  internal/directives/schemas/kustomize-set-image-config.json
  internal/directives/testdata/helm/charts/demo-0.1.0.tgz
  internal/directives/testdata/helm/charts/examplechart-0.1.0.tgz
  internal/directives/validation.go
  internal/directives/zz_config_types.go
  internal/helm/registry.go
  internal/yaml/decode.go
  internal/yaml/decode_test.go
  internal/yaml/update.go
  internal/yaml/update_test.go
  internal/yaml/yaml.go
  internal/yaml/yaml_test.go
Labels: kind/enhancement, priority/normal, size/xx-large

#2537 feat: add git-based promotion directives
  .github/workflows/ci.yaml
  Dockerfile.dev
  hack/codegen/directive-configs.sh
  internal/argocd/revision.go
  internal/controller/freight/finder.go
  internal/controller/freight/finder_test.go
  internal/controller/promotion/argocd.go
  internal/controller/promotion/git.go
  internal/directives/copy_directive.go
  internal/directives/directive.go
  internal/directives/git_clone_directive.go
  internal/directives/git_clone_directive_test.go
  internal/directives/git_commit_directive.go
  internal/directives/git_commit_directive_test.go
  internal/directives/git_open_pr_directive.go
  internal/directives/git_open_pr_directive_test.go
  internal/directives/git_overwrite_directive.go
  internal/directives/git_overwrite_directive_test.go
  internal/directives/git_push_directive.go
  internal/directives/git_push_directive_test.go
  internal/directives/git_wait_for_pr_directive.go
  internal/directives/git_wait_for_pr_directive_test.go
  internal/directives/schemas/git-clone-config.json
  internal/directives/schemas/git-commit-config.json
  internal/directives/schemas/git-open-pr-config.json
  internal/directives/schemas/git-overwrite-config.json
  internal/directives/schemas/git-wait-for-pr-config.json
  internal/directives/zz_config_types.go
  internal/gitprovider/github/github.go
  internal/gitprovider/gitlab/gitlab.go
  internal/gitprovider/gitprovider.go
Labels: kind/enhancement, priority/high, area/controller

#2474 feat(ui): ability to create Stage via UI wizard
  ui/src/app.tsx
  ui/src/config/paths.ts
  ui/src/features/common/form/field-container.tsx
  ui/src/features/common/small-label.tsx
  ui/src/features/common/stage-tag.tsx
  ui/src/features/common/utils.ts
  ui/src/features/project/list/project-item/project-item.tsx
  ui/src/features/project/pipelines/create-stage-modal.tsx
  ui/src/features/project/pipelines/pipelines.tsx
  ui/src/features/project/pipelines/utils/promo-mechanism-example.ts
  ui/src/features/project/pipelines/warehouse/warehouse-details.tsx
  ui/src/features/stage/create-stage.tsx
  ui/src/features/stage/git-update-editor/git-update-editor.module.less
  ui/src/features/stage/git-update-editor/helm-charts.tsx
  ui/src/features/stage/git-update-editor/helm-images.tsx
  ui/src/features/stage/git-update-editor/helm-mechanism.tsx
  ui/src/features/stage/git-update-editor/kustomize-mechanism.tsx
  ui/src/features/stage/git-update-editor/origin-override.tsx
  ui/src/features/stage/git-update-editor/render-mechanism.tsx
  ui/src/features/stage/git-update-editor/schemas.ts
  ui/src/features/stage/git-update-editor/use-digest-tag.tsx
  ui/src/features/stage/git-update-editor/values-table.tsx
  ui/src/features/stage/git-update-editor/warehouse-tooltip.tsx
  ui/src/features/stage/requested-freight-editor.tsx
  ui/src/features/stage/requested-freight.tsx
  ui/src/features/stage/stage-details.tsx
  ui/src/pages/project.tsx
Labels: kind/enhancement, area/ui, priority/normal

#2541 fix(api): prevent panic in FormatEventUserActor
  api/v1alpha1/event.go
Labels: kind/bug, priority/normal, area/api

#2542 fix(directives): propagate origin for `git-clone` if set
  internal/directives/git_clone_directive.go
Labels: kind/bug, priority/normal, area/controller

#2546 feat: make git-based promotion directives slightly more flexible
  internal/directives/git_commit_directive.go
  internal/directives/git_commit_directive_test.go
  internal/directives/git_open_pr_directive.go
  internal/directives/git_open_pr_directive_test.go
  internal/directives/git_push_directive.go
  internal/directives/git_push_directive_test.go
  internal/directives/schemas/git-open-pr-config.json
  internal/directives/zz_config_types.go
Labels: kind/enhancement, kind/refactor, priority/high, area/controller

#2545 feat(controller): add argocd-update directive
  internal/directives/argocd_update_directive.go
  internal/directives/argocd_update_directive_test.go
  internal/directives/origins.go
  internal/directives/origins_test.go
  internal/directives/schemas/argocd-update-config.json
  internal/directives/zz_config_types.go
Labels: kind/enhancement, priority/high, area/controller

#2539 feat(api/controller): Promotion directive steps
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/promotion_types.go
  api/v1alpha1/stage_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/kargo/resources/crds/kargo.akuity.io_promotions.yaml
  charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
  go.mod
  hack/codegen/proto.sh
  internal/controller/promotions/promotions.go
  internal/controller/stages/stages.go
  internal/directives/engine.go
  internal/directives/fake_engine.go
  internal/directives/fake_engine_test.go
  internal/directives/git_clone_directive.go
  internal/directives/simple_engine.go
  internal/directives/simple_engine_test.go
  internal/kargo/kargo.go
  internal/webhook/promotion/webhook.go
  internal/webhook/promotion/webhook_test.go
  ui/src/gen/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/generated_pb.ts
  ui/src/gen/schema/promotions.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
  ui/src/gen/v1alpha1/generated_pb.ts
Labels: kind/enhancement, area/controller, area/api

#2547 feat(controller): configure work dir for promotion
  internal/controller/promotions/promotions.go
Labels: kind/enhancement, priority/normal, area/controller

#2548 fix(git): improve parsing of worktree list
  internal/controller/git/bare_repo.go
  internal/controller/git/bare_repo_test.go
Labels: kind/bug, priority/normal, area/controller

#2552 feat: multisource healthchecks
  internal/argocd/health.go
  internal/argocd/health_test.go
  internal/argocd/revision.go
  internal/argocd/revision_test.go
  internal/controller/argocd/api/v1alpha1/application_types.go
  internal/controller/argocd/api/v1alpha1/zz_generated.deepcopy.go
  internal/controller/promotion/argocd.go
  internal/controller/promotion/argocd_test.go
Labels: kind/enhancement, kind/refactor, priority/urgent, area/controller

#2550 fix(ui): stage/freight live manifest scrolls infinitely
  ui/src/features/common/manifest-preview.tsx
  ui/src/features/freight/freight-details.tsx
  ui/src/features/project/pipelines/pipelines.tsx
  ui/src/features/stage/stage-details.tsx
Labels: kind/bug, area/ui, priority/high

#2565 fix(ui): jitter scrollbar on hover assemble freight button
  ui/src/features/freight-timeline/freight-timeline-header.tsx
Labels: kind/bug, area/ui, priority/normal

#2553 refactor: port recent improvements from classic promo mechs to argocd-update directive
  internal/directives/argocd_revisions.go
  internal/directives/argocd_revisions_test.go
  internal/directives/argocd_update_directive.go
  internal/directives/argocd_update_directive_test.go
Labels: kind/refactor, priority/high, area/controller

#2566 fix(ui): graph line b/w warehouse and multiple subscriptions broken
  ui/src/features/project/pipelines/pipelines.tsx
  ui/src/features/project/pipelines/utils/use-pipeline-graph.ts
Labels: kind/bug, area/ui

#2513 fix(ui): Hide managed fields in UI doesn't work
  ui/src/features/common/code-editor/yaml-editor-lazy.tsx
  ui/src/features/stage/analysis-run-modal.tsx
Labels: kind/bug, area/ui, priority/normal

#2567 fix(directives): improve helm chart dependency validation
  internal/directives/copy_directive.go
  internal/directives/helm_update_chart_directive.go
  internal/directives/helm_update_chart_directive_test.go
Labels: kind/bug, priority/normal, area/controller

#2554 refactor: make engine and directive interfaces and related types support the notion of healthchecks
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/stage_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
  internal/controller/promotions/promotions.go
  internal/directives/argocd_revisions.go
  internal/directives/argocd_revisions_test.go
  internal/directives/argocd_updater.go
  internal/directives/argocd_updater_test.go
  internal/directives/config.go
  internal/directives/config_test.go
  internal/directives/directive.go
  internal/directives/engine.go
  internal/directives/fake_engine.go
  internal/directives/fake_engine_test.go
  internal/directives/file_copier.go
  internal/directives/file_copier_test.go
  internal/directives/git_cloner.go
  internal/directives/git_cloner_test.go
  internal/directives/git_commiter.go
  internal/directives/git_commiter_test.go
  internal/directives/git_pr_opener.go
  internal/directives/git_pr_opener_test.go
  internal/directives/git_pr_waiter.go
  internal/directives/git_pr_waiter_test.go
  internal/directives/git_pusher.go
  internal/directives/git_pusher_test.go
  internal/directives/git_tree_overwriter.go
  internal/directives/git_tree_overwriter_test.go
  internal/directives/health_checks.go
  internal/directives/helm_chart_updater.go
  internal/directives/helm_chart_updater_test.go
  internal/directives/helm_image_updater.go
  internal/directives/helm_image_updater_test.go
  internal/directives/helm_template_runner.go
  internal/directives/helm_template_runner_test.go
  internal/directives/kustomize_builder.go
  internal/directives/kustomize_builder_test.go
  internal/directives/kustomize_image_setter.go
  internal/directives/kustomize_image_setter_test.go
  internal/directives/mock_directive_test.go
  internal/directives/mock_health_check_step_runner.go
  internal/directives/mock_promotion_step_runner_test.go
  internal/directives/promotions.go
  internal/directives/registry.go
  internal/directives/registry_test.go
  internal/directives/simple_engine.go
  internal/directives/simple_engine_test.go
  internal/directives/state.go
  internal/directives/state_test.go
  ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
  ui/src/gen/v1alpha1/generated_pb.ts
Labels: kind/refactor, priority/high, area/controller

#2571 fix: remove faulty Dependabot config
  .github/dependabot.yml
Labels: kind/bug, area/ci-process, priority/normal, dependencies

#2570 feat(controller): complementary health checks for argocd-update promotion step
  internal/controller/argocd/api/v1alpha1/application_types.go
  internal/directives/argocd_health.go
  internal/directives/argocd_health_test.go
  internal/directives/argocd_revisions.go
  internal/directives/argocd_revisions_test.go
  internal/directives/argocd_updater.go
  internal/directives/argocd_updater_test.go
Labels: kind/enhancement, priority/high, area/controller

#2580 feat(controller): use directives engine for Stage health checks
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/promotion_types.go
  api/v1alpha1/stage_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/kargo/resources/crds/kargo.akuity.io_promotions.yaml
  charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
  cmd/controlplane/controller.go
  internal/controller/promotions/promotions.go
  internal/controller/promotions/promotions_test.go
  internal/controller/stages/stages.go
  internal/controller/stages/stages_test.go
  internal/directives/config.go
  internal/directives/config_test.go
  internal/directives/simple_engine.go
  ui/src/gen/schema/promotions.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
  ui/src/gen/v1alpha1/generated_pb.ts
Labels: kind/enhancement, priority/urgent, area/controller

#2583 refactor: swap step field for uses field
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/promotion_types.go
  charts/kargo/resources/crds/kargo.akuity.io_promotions.yaml
  charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
  internal/controller/promotions/promotions.go
  internal/controller/stages/stages.go
  ui/src/gen/schema/promotions.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
  ui/src/gen/v1alpha1/generated_pb.ts
Labels: kind/refactor, priority/normal, area/controller, area/crds

#2585 feat: allow argocd-update steps to learn desired revisions for sources from previous steps
  internal/directives/argocd_revisions.go
  internal/directives/git_commiter.go
  internal/directives/git_commiter_test.go
  internal/directives/git_pr_opener.go
  internal/directives/git_pr_opener_test.go
  internal/directives/git_pr_waiter.go
  internal/directives/schemas/argocd-update-config.json
  internal/directives/schemas/git-commit-config.json
  internal/directives/schemas/git-open-pr-config.json
  internal/directives/zz_config_types.go
Labels: kind/enhancement, kind/refactor, priority/high, area/controller

#2588 fix: fix bug in git overwrite promotion step
  internal/directives/git_tree_overwriter.go
Labels: kind/bug, priority/urgent, area/controller

#2589 fix: cast output from promotion steps as map[string]any
  internal/directives/simple_engine.go
Labels: kind/bug, priority/urgent, area/controller

#2590 fix: make git-commit promotion step check for diffs before committing
  internal/directives/git_commiter.go
Labels: kind/bug, priority/urgent, area/controller

#2591 fix: prefer map[string]any everywhere where we don't actually need to use DeepCopy
  internal/directives/argocd_health.go
  internal/directives/argocd_revisions.go
  internal/directives/git_commiter.go
  internal/directives/git_commiter_test.go
  internal/directives/git_pr_opener.go
  internal/directives/git_pr_opener_test.go
  internal/directives/git_pr_waiter.go
  internal/directives/git_pusher.go
  internal/directives/git_pusher_test.go
  internal/directives/health_checks.go
  internal/directives/helm_chart_updater.go
  internal/directives/helm_chart_updater_test.go
  internal/directives/helm_image_updater.go
  internal/directives/helm_image_updater_test.go
  internal/directives/kustomize_image_setter.go
  internal/directives/kustomize_image_setter_test.go
  internal/directives/promotions.go
  internal/directives/simple_engine.go
  internal/directives/simple_engine_test.go
Labels: kind/bug, kind/refactor, priority/urgent

#2592 fix(ui): unblock promotions when promotion directives are used
  ui/src/features/project/pipelines/nodes/stage-node.tsx
Labels: kind/bug, area/ui, priority/high

#2594 chore(api): mark PromotionMechanisms as deprecated
  api/v1alpha1/generated.proto
  api/v1alpha1/stage_types.go
  charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
  internal/api/promote_downstream_v1alpha1.go
  internal/argocd/health.go
  internal/argocd/health_test.go
  internal/argocd/revision_test.go
  internal/controller/freight/origins.go
  internal/controller/freight/origins_test.go
  internal/controller/promotion/argocd.go
  internal/controller/promotion/argocd_test.go
  internal/controller/promotion/composite.go
  internal/controller/promotion/git.go
  internal/controller/promotion/git_test.go
  internal/controller/promotion/helm_test.go
  internal/controller/promotion/kustomize_test.go
  internal/controller/promotion/render_test.go
  internal/kubeclient/indexer.go
  internal/webhook/promotion/webhook.go
  internal/webhook/stage/webhook.go
  internal/webhook/stage/webhook_test.go
  ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
  ui/src/gen/v1alpha1/generated_pb.ts
Labels: kind/chore, priority/normal, area/api

#2595 fix: allow overwriter promotion step to handle individual files
  internal/directives/git_tree_overwriter.go
Labels: kind/bug, priority/urgent, area/controller

#2600 fix(controller): fix source branch used by pr-opener
  internal/directives/git_pr_opener.go
Labels: kind/bug, priority/urgent, area/controller

#2601 fix(controller): make git-pr-waiter get pr number using correct key
  internal/directives/git_pr_waiter.go
Labels: kind/bug, priority/urgent, area/controller

#2602 fix(controller): make simple engine short-circuit step execution on non-success
  internal/directives/simple_engine.go
Labels: kind/bug, priority/urgent, area/controller

#2605 fix(ui): display 0 instead of null when condition is falsy
  ui/src/features/project/pipelines/pipelines.tsx
Labels: kind/bug, area/ui, priority/high

#2599 fix(directives): restore Chart.lock on no changes
  internal/directives/helm_chart_updater.go
  internal/directives/helm_chart_updater_test.go
Labels: kind/bug, priority/high, area/controller

#2604 feat: keep track of promotion state in promotion status
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/promotion_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/kargo/resources/crds/kargo.akuity.io_promotions.yaml
  charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
  internal/controller/promotions/promotions.go
  internal/directives/git_pr_waiter.go
  internal/directives/promotions.go
  internal/directives/simple_engine.go
  internal/directives/state.go
  ui/src/gen/schema/promotions.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
  ui/src/gen/v1alpha1/generated_pb.ts
Labels: kind/enhancement, priority/urgent, area/controller, area/crds

#2609 refactor: update wait-for-pr step for improved consistency with other built-ins
  internal/directives/git_pr_waiter.go
  internal/directives/git_pr_waiter_test.go
  internal/directives/schemas/git-wait-for-pr-config.json
  internal/directives/zz_config_types.go
Labels: kind/refactor, priority/high, area/controller

#2610 docs: roadmap update
  docs/docs/50-roadmap.md
Labels: area/documentation, kind/refactor, priority/high

#2579 feat: migrate sso user, serviceaccount mapping annotations
  cmd/controlplane/management_controller.go
  internal/controller/management/upgrade/serviceaccounts.go
  internal/controller/management/upgrade/serviceaccounts_test.go
Labels: kind/enhancement, kind/chore, area/controller

#2611 docs: update docs and scripts to lock release-0.8 branch into latest stable release
  docs/docs/20-quickstart.md
  docs/docs/30-how-to-guides/10-installing-kargo.md
  hack/quickstart/install.sh
  hack/quickstart/k3d.sh
  hack/quickstart/kind.sh
Labels: area/documentation, kind/chore, area/release-process, priority/high

#2612 docs: update docs and scripts to work with v0.9.0-rc.1
  docs/docs/20-quickstart.md
  docs/docs/30-how-to-guides/10-installing-kargo.md
  hack/quickstart/install.sh
  hack/quickstart/k3d.sh
  hack/quickstart/kind.sh
Labels: area/documentation, kind/chore, area/release-process, priority/high
