Repository akuity/kargo, pull requests merged in 2024-12, with the labels that each got.

#3029 docs: fix typo ecr to gar
  docs/docs/30-how-to-guides/20-managing-credentials.md
Labels: area/documentation, priority/normal, backport/release-1.1

#3031 fix: retry getting AnalysisRun on error
  internal/controller/stages/regular_stages.go
Labels: kind/bug, priority/high, area/controller, backport/release-1.1

#2960 chore(backport release-1.0): fix(build): use `tini` to reap zombie processes
  Dockerfile
  charts/kargo/templates/controller/deployment.yaml
  charts/kargo/templates/garbage-collector/cron-job.yaml
  charts/kargo/templates/management-controller/deployment.yaml
  charts/kargo/templates/webhooks-server/deployment.yaml
  kargo-base.apko.yaml
Labels: kind/bug, priority/high, area/charts, docker

#3040 feat(api): track verification and approval times
  api/v1alpha1/freight_types.go
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/zz_generated.deepcopy.go
  charts/kargo/resources/crds/kargo.akuity.io_freights.yaml
  internal/api/approve_freight_v1alpha1.go
  internal/controller/stages/control_flow_stages.go
  internal/controller/stages/control_flow_stages_test.go
  internal/controller/stages/regular_stages.go
  internal/controller/stages/regular_stages_test.go
  ui/src/gen/schema/freights.kargo.akuity.io_v1alpha1.json
  ui/src/gen/v1alpha1/generated_pb.ts
Labels: kind/enhancement, priority/normal, area/controller, area/api

#3042 fix(controller)!: argocd-update: require desired revision to be specified when using updateTargetRevision
  docs/docs/35-references/10-promotion-steps.md
  internal/directives/argocd_updater_test.go
  internal/directives/schemas/argocd-update-config.json
  internal/directives/simple_engine_promote.go
  internal/directives/zz_config_types.go
  ui/src/gen/directives/argocd-update-config.json
Labels: kind/bug, priority/high, area/controller, backport/release-1.1

#3045 docs: document outline of step options
  docs/docs/35-references/10-promotion-steps.md
Labels: area/documentation, kind/chore, priority/high, backport/release-1.1

#3044 docs: fix two small doc mistakes
  docs/docs/35-references/10-promotion-steps.md
  docs/docs/35-references/20-expression-language.md
Labels: kind/bug, area/documentation, priority/high, backport/release-1.1

#3046 docs: update quickstart to use expressions
  docs/docs/20-quickstart.md
Labels: area/documentation, kind/chore, priority/high, backport/release-1.1

#3039 chore(ui): bump `oauth4webapi` major version
  ui/package.json
  ui/pnpm-lock.yaml
  ui/src/features/auth/oidc-login.tsx
  ui/src/features/auth/token-renew.tsx
  ui/src/features/auth/utils.ts
Labels: area/ui, priority/normal

#3054 chore(backport release-1.1): fix(controller): prevent unsuccessful promo from blocking next promo
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/stage_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
  internal/controller/stages/regular_stages.go
  internal/controller/stages/regular_stages_test.go
  ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
  ui/src/gen/v1alpha1/generated_pb.ts
Labels: kind/bug, priority/urgent, area/controller

#3051 docs: fix heading level on argocd-update health checks
  docs/docs/35-references/10-promotion-steps.md
Labels: kind/bug, area/documentation, priority/high, backport/release-1.1

#3057 fix(directives): don't mark App sync as automated
  internal/directives/argocd_updater.go
Labels: kind/bug, area/controller, backport/release-1.1

#3059 fix(creds): don't require base64 PK for GitHub Apps
  docs/docs/30-how-to-guides/20-managing-credentials.md
  internal/credentials/kubernetes/github/app.go
Labels: kind/bug, priority/normal, area/controller, backport/release-1.1

#3060 fix: refactor retries
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/promotion_types.go
  api/v1alpha1/promotion_types_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/kargo/resources/crds/kargo.akuity.io_promotions.yaml
  charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
  internal/controller/promotions/promotions.go
  internal/directives/argocd_updater.go
  internal/directives/git_pr_waiter.go
  internal/directives/promotions.go
  internal/directives/promotions_test.go
  internal/directives/simple_engine_promote.go
  internal/directives/simple_engine_promote_test.go
  ui/src/gen/schema/promotions.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
  ui/src/gen/v1alpha1/generated_pb.ts
Labels: kind/bug, kind/refactor, priority/urgent, area/controller, area/crds

#3065 docs: update retry docs
  docs/docs/35-references/10-promotion-steps.md
Labels: area/documentation, kind/refactor, priority/high, backport/release-1.1

#3068 chore: manual backport of refactored retries (#3060)
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/promotion_types.go
  api/v1alpha1/promotion_types_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/kargo/resources/crds/kargo.akuity.io_promotions.yaml
  charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
  internal/controller/promotions/promotions.go
  internal/directives/argocd_updater.go
  internal/directives/git_pr_waiter.go
  internal/directives/promotions.go
  internal/directives/promotions_test.go
  internal/directives/simple_engine_promote.go
  internal/directives/simple_engine_promote_test.go
  ui/src/gen/schema/promotions.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
  ui/src/gen/v1alpha1/generated_pb.ts
Labels: kind/chore, kind/refactor, priority/urgent, area/controller

#3066 refactor(controller): replace http step timeoutSeconds with timeout
  docs/docs/35-references/10-promotion-steps.md
  internal/directives/http_requester.go
  internal/directives/http_requester_test.go
  internal/directives/schemas/http-config.json
  internal/directives/zz_config_types.go
  ui/src/gen/directives/http-config.json
Labels: kind/refactor, priority/high, area/controller, backport/release-1.1

#3069 chore: clear app status op state
  internal/directives/argocd_updater.go
Labels: kind/chore, priority/urgent, area/controller, backport/release-1.1

#3074 chore(controller): make backoff configurable for tests
  internal/controller/stages/regular_stages.go
  internal/controller/stages/regular_stages_test.go
Labels: kind/chore, priority/low, area/controller

#3078 chore: release chores 1.0
  docs/docs/20-quickstart.md
  docs/docs/30-how-to-guides/10-installing-kargo.md
  hack/quickstart/install.sh
  hack/quickstart/k3d.sh
  hack/quickstart/kind.sh
Labels: area/documentation, kind/chore, area/release-process, priority/normal

#3079 chore: release chores 1.1
  docs/docs/20-quickstart.md
Labels: area/documentation, kind/chore, area/release-process, priority/normal

#3085 fix(docs): typos in promition steps causing examples to not work
  docs/docs/35-references/10-promotion-steps.md
Labels: kind/bug, area/documentation, priority/normal, backport/release-1.1

#3075 chore(ci): handle deprecation of Go linter format
  .github/workflows/ci.yaml
Labels: kind/chore, area/ci-process, priority/low

#3098 fix(controller): Promotion on verification failure
  internal/controller/stages/regular_stages.go
  internal/controller/stages/regular_stages_test.go
Labels: kind/bug, priority/high, area/controller, backport/release-1.1

#3083 fix(controller): app sync fix
  internal/directives/argocd_updater.go
  internal/directives/argocd_updater_test.go
Labels: kind/bug, priority/high, area/controller, backport/release-1.1

#3102 chore(backport release-1.1): chore(deps): bump the go-patch group with 8 updates
  go.mod
  go.sum
Labels: dependencies, go

#3103 chore(backport release-1.1): chore(deps): bump golang from 1.23.3-bookworm to 1.23.4-bookworm
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  Dockerfile
  Dockerfile.dev
Labels: dependencies, docker

#3077 fix: broken link
  docs/docs/40-contributor-guide/15-release-procedures.md
Labels: area/documentation, kind/chore, backport/release-1.1

#3107 feat: custom PR title (#3063)
  docs/docs/35-references/10-promotion-steps.md
  internal/directives/git_pr_opener.go
  internal/directives/git_pr_opener_test.go
  internal/directives/schemas/git-open-pr-config.json
  internal/directives/zz_config_types.go
  ui/src/gen/directives/git-open-pr-config.json
Labels: kind/enhancement, priority/normal, area/controller

#3112 fix(controller): correct typo in output message
  internal/directives/git_pr_opener.go
Labels: kind/chore, area/controller, backport/release-1.1

#3110 fix(controller): do not normalize urls when searching for image creds
  internal/credentials/kubernetes/database.go
  internal/credentials/kubernetes/database_test.go
Labels: kind/bug, priority/normal, area/controller, backport/release-1.1

#3115 feat(directives): optional `images` for `kustomize-set-image`
  docs/docs/35-references/10-promotion-steps.md
  internal/controller/freight/finder.go
  internal/controller/freight/finder_test.go
  internal/directives/kustomize_image_setter.go
  internal/directives/kustomize_image_setter_test.go
  internal/directives/schemas/kustomize-set-image-config.json
  internal/directives/zz_config_types.go
  ui/src/gen/directives/kustomize-set-image-config.json
Labels: kind/enhancement, priority/normal, area/controller

#3117 fix(auth): auto attach `offline_access` only if idp supports
  ui/src/features/auth/context/auth-context-provider.tsx
  ui/src/features/auth/context/auth-context.tsx
  ui/src/features/auth/jwt-utils.ts
  ui/src/features/auth/oidc-login.tsx
  ui/src/features/auth/oidc-utils.ts
  ui/src/features/auth/token-renew.tsx
  ui/src/features/common/layout/main-layout.tsx
  ui/src/pages/user.tsx
Labels: kind/bug, area/ui, priority/high

#3122 fix(auth): token renew failure
  ui/src/features/auth/token-renew.tsx
Labels: kind/bug, area/ui, priority/high, backport/release-1.1

#3041 chore(chart): start using Kubernetes' builtin gRPC probe
  charts/kargo/templates/api/deployment.yaml
Labels: kind/chore, priority/normal, area/charts, area/api

#2934 docs: manual rolebindings for global namespaces
  docs/docs/30-how-to-guides/20-managing-credentials.md
Labels: kind/bug, area/documentation, priority/normal, backport/release-1.1

#2935 docs: add a resources page for Kargo related talks
  docs/docs/45-resources.md
Labels: area/documentation, kind/enhancement, priority/normal, backport/release-1.1

#3135 docs: Kargo role matrix
  docs/docs/30-how-to-guides/30-managing-user-permissions.md
Labels: area/documentation, kind/enhancement, priority/normal, backport/release-1.1

#3119 fix(controller): git-push step: pull --rebase before push
  docs/docs/35-references/10-promotion-steps.md
  internal/controller/git/errors.go
  internal/controller/git/errors_test.go
  internal/controller/git/work_tree.go
  internal/directives/errors.go
  internal/directives/errors_test.go
  internal/directives/git_pr_waiter.go
  internal/directives/git_pr_waiter_test.go
  internal/directives/git_pusher.go
  internal/directives/git_pusher_test.go
  internal/directives/http_requester.go
  internal/directives/http_requester_test.go
  internal/directives/schemas/git-push-config.json
  internal/directives/simple_engine_promote.go
  internal/directives/simple_engine_promote_test.go
  internal/directives/zz_config_types.go
  ui/src/gen/directives/git-push-config.json
Labels: kind/bug, priority/high, area/controller, backport/release-1.1

#3138 feat(ui): Argo CD deep link in Promotion lists
  ui/src/features/stage/promotion-details-modal.tsx
  ui/src/features/stage/promotions.tsx
  ui/src/features/stage/stage-actions.tsx
  ui/src/features/stage/stage-details.tsx
  ui/src/plugins/argocd-plugin/argocd-plugin.tsx
  ui/src/plugins/argocd-plugin/deep-link/promotion.tsx
  ui/src/plugins/atoms/plugin-helper.ts
  ui/src/plugins/atoms/plugin-interfaces.ts
  ui/src/plugins/atoms/ui-plugin-hole/deep-link-promotion-step.tsx
  ui/src/plugins/atoms/ui-plugin-hole/deep-link-promotion.tsx
  ui/src/plugins/index.tsx
Labels: kind/bug, area/ui, priority/high

#3157 docs: update docs re: argocd sync windows
  docs/docs/35-references/10-promotion-steps.md
Labels: area/documentation, kind/enhancement, priority/high, backport/release-1.1

#3156 feat: make yaml-update syntax the same as json-update syntax
  docs/docs/35-references/10-promotion-steps.md
  internal/directives/helm_chart_updater.go
  internal/directives/helm_chart_updater_test.go
  internal/directives/helm_image_updater.go
  internal/directives/helm_image_updater_test.go
  internal/directives/yaml_updater.go
  internal/directives/yaml_updater_test.go
  internal/yaml/decode.go
  internal/yaml/update.go
  internal/yaml/update_test.go
  internal/yaml/yaml.go
  internal/yaml/yaml_test.go
Labels: kind/enhancement, kind/refactor, priority/high, area/controller

#3072 chore(ui): connectrpc migrate to version 2
  buf.ui.gen.yaml
  hack/codegen/proto.sh
  ui/hack/generate-proto-extensions.mjs
  ui/package.json
  ui/pnpm-lock.yaml
  ui/src/features/assemble-freight/commit-table.tsx
  ui/src/features/assemble-freight/image-table.tsx
  ui/src/features/common/analysis-modal/metric-chart/metric-chart.tsx
  ui/src/features/common/analysis-modal/transforms.ts
  ui/src/features/common/manifest-preview.tsx
  ui/src/features/common/promotion-directive-step-status/utils.test.ts
  ui/src/features/common/utils.ts
  ui/src/features/freight-timeline/freight-item-label.tsx
  ui/src/features/freight/freight-details.tsx
  ui/src/features/project/analysis-templates/analysis-templates-list.tsx
  ui/src/features/project/analysis-templates/create-analysis-template-modal.tsx
  ui/src/features/project/analysis-templates/edit-analysis-template-modal.tsx
  ui/src/features/project/events/events.tsx
  ui/src/features/project/list/project-item/stage-popover.tsx
  ui/src/features/project/pipelines/nodes/freight-label.tsx
  ui/src/features/project/pipelines/nodes/stage-node.tsx
  ui/src/features/project/pipelines/utils/watcher.ts
  ui/src/features/project/pipelines/warehouse/warehouse-actions.tsx
  ui/src/features/project/roles/create-role.tsx
  ui/src/features/project/settings/components/delete-project-modal.tsx
  ui/src/features/stage/create-stage.tsx
  ui/src/features/stage/create-warehouse/subscription-wizard.tsx
  ui/src/features/stage/freight-history.tsx
  ui/src/features/stage/promotion-details-modal.tsx
  ui/src/features/stage/promotion-steps-wizard/use-promotion-wizard-steps-state.ts
  ui/src/features/stage/promotions.tsx
  ui/src/features/stage/stage-actions.tsx
  ui/src/features/stage/stage-details.tsx
  ui/src/features/stage/utils/promotion.ts
  ui/src/features/stage/verifications.tsx
  ui/src/features/utils/cache/analysis-templates.ts
  ui/src/features/utils/cache/image-stage-matrix.ts
  ui/src/features/utils/cache/project.ts
  ui/src/features/utils/manifest-generator.ts
  ui/src/gen/k8s.io/api/batch/v1/generated_pb.ts
  ui/src/gen/k8s.io/api/core/v1/generated_pb.ts
  ui/src/gen/k8s.io/api/rbac/v1/generated_pb.ts
  ui/src/gen/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/generated_pb.ts
  ui/src/gen/k8s.io/apimachinery/pkg/api/resource/generated_pb.ts
  ui/src/gen/k8s.io/apimachinery/pkg/apis/meta/v1/generated_pb.ts
  ui/src/gen/k8s.io/apimachinery/pkg/runtime/generated_pb.ts
  ui/src/gen/k8s.io/apimachinery/pkg/runtime/schema/generated_pb.ts
  ui/src/gen/k8s.io/apimachinery/pkg/util/intstr/generated_pb.ts
  ui/src/gen/rbac/v1alpha1/generated_pb.ts
  ui/src/gen/rollouts/api/v1alpha1/generated_pb.ts
  ui/src/gen/service/v1alpha1/service-KargoService_connectquery.ts
  ui/src/gen/service/v1alpha1/service_connect.ts
  ui/src/gen/service/v1alpha1/service_pb.ts
  ui/src/gen/v1alpha1/generated_pb.ts
  ui/src/utils/connectrpc-utils.ts
Labels: kind/chore, area/ui, priority/normal

#3158 feat(chart): add option for ingress controller terminating ssl with its own cert
  charts/kargo/README.md
  charts/kargo/templates/_helpers.tpl
  charts/kargo/templates/api/configmap.yaml
  charts/kargo/templates/controller/configmap.yaml
  charts/kargo/templates/dex-server/secret.yaml
  charts/kargo/values.yaml
Labels: kind/enhancement, priority/low, area/charts

#3128 feat(gitprovider): add Azure DevOps support and update provider confi…
  go.mod
  go.sum
  internal/directives/git_pr_opener.go
  internal/directives/schemas/git-open-pr-config.json
  internal/directives/schemas/git-wait-for-pr-config.json
  internal/directives/zz_config_types.go
  internal/gitprovider/azure/azure.go
  internal/gitprovider/azure/azure_test.go
  ui/src/gen/directives/git-open-pr-config.json
  ui/src/gen/directives/git-wait-for-pr-config.json
Labels: kind/enhancement, priority/normal, area/controller

#3118 feat: PR labels (#3002)
  docs/docs/35-references/10-promotion-steps.md
  go.mod
  internal/directives/git_pr_opener.go
  internal/directives/schemas/git-open-pr-config.json
  internal/directives/zz_config_types.go
  internal/gitprovider/azure/azure.go
  internal/gitprovider/github/github.go
  internal/gitprovider/github/github_test.go
  internal/gitprovider/gitlab/gitlab.go
  internal/gitprovider/gitprovider.go
  ui/src/gen/directives/git-open-pr-config.json
Labels: kind/enhancement, priority/normal, area/controller

#3086 feat: add promotion step to remove a file/directory
  docs/docs/35-references/10-promotion-steps.md
  internal/directives/file_deleter.go
  internal/directives/file_deleter_test.go
  internal/directives/schemas/delete-config.json
  internal/directives/zz_config_types.go
  ui/src/features/promotion-directives/registry/use-discover-registries.ts
  ui/src/gen/directives/delete-config.json
Labels: kind/enhancement, priority/normal, area/controller

#3151 feat: json update promotion step
  docs/docs/35-references/10-promotion-steps.md
  go.mod
  go.sum
  internal/directives/json_updater.go
  internal/directives/json_updater_test.go
  internal/directives/schemas/json-update-config.json
  internal/directives/zz_config_types.go
  ui/src/features/promotion-directives/registry/use-discover-registries.ts
  ui/src/gen/directives/json-update-config.json
Labels: kind/enhancement, priority/normal, area/controller

#3170 fix(controller): fix tricky expr evaluation cases dealing with quotes and newlines
  internal/expressions/json_templates.go
  internal/expressions/json_templates_test.go
Labels: kind/bug, priority/high, area/controller, backport/release-1.1

#3167 chore: remove image updater info
  api/v1alpha1/generated.proto
  api/v1alpha1/warehouse_types.go
  charts/kargo/resources/crds/kargo.akuity.io_warehouses.yaml
  ui/src/gen/schema/warehouses.kargo.akuity.io_v1alpha1.json
  ui/src/gen/v1alpha1/generated_pb.ts
Labels: area/documentation, kind/chore, priority/normal, backport/release-1.1

#2921 docs: authorizing kargo stages to modify argo apps
  docs/docs/30-how-to-guides/25-argo-cd-integration.md
Labels: area/documentation, kind/enhancement, backport/release-1.1

#3168 fix(ui): avoid truncate artifact details unnecessarily
  ui/src/features/freight-timeline/freight-content-item.tsx
  ui/src/features/freight-timeline/freight-contents.tsx
  ui/src/features/freight/freight-details.tsx
Labels: kind/bug, area/ui, priority/normal
