Repository akuity/kargo, pull requests merged in 2025-04, with the labels that each got.

#3768 feat(ui): Project Settings Redesign
  ui/src/app.tsx
  ui/src/config/paths.ts
  ui/src/config/themeConfig.ts
  ui/src/features/common/layout/base-header.tsx
  ui/src/features/common/layout/main-layout.module.less
  ui/src/features/project/credentials/credentials-list.tsx
  ui/src/features/project/events/events.tsx
  ui/src/features/project/list/project-item/project-item.module.less
  ui/src/features/project/list/project-list-filter.tsx
  ui/src/features/project/project-utils.tsx
  ui/src/features/project/settings/project-settings.tsx
  ui/src/features/project/settings/views/analysis-templates/analysis-templates.tsx
  ui/src/features/project/settings/views/analysis-templates/create-analysis-template-modal.tsx
  ui/src/features/project/settings/views/analysis-templates/edit-analysis-template-modal.tsx
  ui/src/features/project/settings/views/analysis-templates/utils/analysis-template-example.ts
  ui/src/features/project/settings/views/credentials/create-credentials-modal.tsx
  ui/src/features/project/settings/views/credentials/credentials.tsx
  ui/src/features/project/settings/views/credentials/secret-editor.tsx
  ui/src/features/project/settings/views/credentials/types.ts
  ui/src/features/project/settings/views/credentials/utils.tsx
  ui/src/features/project/settings/views/general/delete-project-modal.tsx
  ui/src/features/project/settings/views/general/general-settings.tsx
  ui/src/features/project/settings/views/promotion-tasks/create-promotion-task.tsx
  ui/src/features/project/settings/views/promotion-tasks/edit-promotion-task-modal.tsx
  ui/src/features/project/settings/views/promotion-tasks/promotion-task-example.ts
  ui/src/features/project/settings/views/promotion-tasks/promotion-tasks.tsx
  ui/src/features/project/settings/views/roles/create-role.tsx
  ui/src/features/project/settings/views/roles/delete-role-modal.tsx
  ui/src/features/project/settings/views/roles/roles.tsx
  ui/src/features/project/settings/views/roles/rule-editor.tsx
  ui/src/features/project/settings/views/roles/rules-modal.tsx
  ui/src/features/project/settings/views/roles/rules-table.tsx
  ui/src/pages/project.tsx
Labels: kind/enhancement, area/ui, priority/normal, area/usability

#3778 feat: allow specifying a token for job metric logs access + docs
  charts/kargo/README.md
  charts/kargo/templates/api/deployment.yaml
  charts/kargo/values.yaml
  docs/docs/40-operator-guide/20-advanced-installation/30-common-configurations.md
  internal/server/config/config.go
  internal/server/get_analysisrun_logs_v1alpha1.go
Labels: area/documentation, kind/enhancement, priority/high, area/charts, area/api, backport/release-1.4

#3780 fix(ui): always allow oidc auth code flow over http
  ui/src/features/auth/oidc-utils.ts
Labels: kind/bug, area/ui, priority/high, backport/release-1.3, backport/release-1.4

#3784 docs: add v1.4.0 release notes
  docs/docs/80-release-notes/95-v1.4.0.md
Labels: area/documentation, kind/enhancement, priority/high, backport/release-1.4

#3786 chore: lock 1.3 docs into 1.3 charts, scripts, etc.
  docs/docs/20-quickstart/index.md
  docs/docs/40-operator-guide/10-basic-installation.md
  docs/docs/40-operator-guide/20-advanced-installation/10-advanced-with-helm.md
  docs/docs/40-operator-guide/20-advanced-installation/20-advanced-with-argocd.md
  docs/docs/50-user-guide/05-installing-the-cli/index.md
  hack/quickstart/install.sh
  hack/quickstart/k3d.sh
  hack/quickstart/kind.sh
Labels: area/documentation, kind/chore, priority/high

#3773 feat(ui): Improve Stage Details view
  ui/public/argo-logo.svg
  ui/src/app.less
  ui/src/features/stage/freight-history.tsx
  ui/src/features/stage/requested-freight.module.less
  ui/src/features/stage/stage-actions.tsx
  ui/src/features/stage/stage-details.tsx
  ui/src/features/stage/tabs/freight-history/freight-history.tsx
  ui/src/features/stage/tabs/settings/stage-delete-button.tsx
  ui/src/features/stage/tabs/settings/stage-edit-form.tsx
  ui/src/features/stage/tabs/settings/stage-settings.tsx
  ui/src/features/stage/verifications.tsx
Labels: kind/enhancement, area/ui, priority/normal

#3794 fix: make quote() func in expressions not double-quote strings
  internal/expressions/json_templates.go
  internal/expressions/json_templates_test.go
Labels: kind/bug, priority/high, area/controller, backport/release-1.3

#3810 chore(docs): fix typo in "Logging In"
  docs/docs/50-user-guide/20-how-to-guides/10-logging-in/index.md
Labels: area/documentation, kind/chore, priority/normal, backport/release-1.4

#3538 docs: Update 50-analysis-templates.md
  docs/docs/50-user-guide/60-reference-docs/50-analysis-templates.md
Labels: kind/bug, area/documentation, priority/normal, backport/release-1.4

#3827 chore(deps): update Helm to v3.17.3
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: priority/normal, dependencies, go, backport/release-1.4

#3820 fix!: freight from funcs return nil instead of error when freight not found
  docs/docs/50-user-guide/60-reference-docs/40-expressions.md
  internal/controller/freight/finder.go
  internal/controller/freight/finder_test.go
Labels: kind/refactor, priority/normal, area/controller

#3835 feat(ui): Extensions
  ui/package.json
  ui/pnpm-lock.yaml
  ui/src/extensions/extensions-context.ts
  ui/src/extensions/types.ts
  ui/src/features/stage/stage-details.tsx
Labels: kind/enhancement, area/ui, priority/normal

#3831 chore: update Logs from Job Metrics docs
  charts/kargo/README.md
  charts/kargo/values.yaml
  docs/docs/40-operator-guide/20-advanced-installation/30-common-configurations.md
Labels: area/documentation, kind/refactor, priority/normal, backport/release-1.4

#3795 feat: support passing dynamic key-value pairs in helm-template step
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/helm-template.md
  internal/promotion/runner/builtin/helm_template_runner.go
  internal/promotion/runner/builtin/helm_template_runner_test.go
  internal/promotion/runner/builtin/schemas/helm-template-config.json
  pkg/x/promotion/runner/builtin/zz_config_types.go
  ui/src/gen/directives/helm-template-config.json
Labels: kind/enhancement, priority/normal, area/controller

#3839 docs: add explainer on interval and count
  docs/docs/50-user-guide/60-reference-docs/50-analysis-templates.md
Labels: area/documentation, kind/enhancement, priority/normal, backport/release-1.4

#3840 fix(chart): remove unnecessary permissions from the api server
  charts/kargo/templates/api/cluster-role.yaml
Labels: kind/bug, area/security, priority/high, area/api, backport/release-1.4

#3846 fix(hack): various fixes to (protobuf) codegen
  api/v1alpha1/generated.pb.go
  hack/codegen/proto.sh
Labels: kind/bug, priority/high, area/api

#3841 feat: support custom username claim
  charts/kargo/README.md
  charts/kargo/templates/api/configmap.yaml
  charts/kargo/values.yaml
  internal/api/event.go
  internal/api/events_test.go
  internal/server/oidc/config.go
  internal/server/option/auth.go
  internal/server/option/auth_test.go
  internal/server/user/user.go
Labels: priority/low, area/charts, area/api

#3822 feat(ui): Settings redesign
  ui/src/app.tsx
  ui/src/config/paths.ts
  ui/src/features/settings/analysis-templates/analysis-templates.tsx
  ui/src/features/settings/cluster-promotion-tasks/cluster-promotion-tasks.tsx
  ui/src/features/settings/cluster-promotion-tasks/create-cluster-promotion-task.tsx
  ui/src/pages/settings.tsx
Labels: kind/enhancement, area/ui, priority/normal

#3860 fix: remove hardcoded RemoveSourceBranch flag in gitlab gitprovider CreatePullRequest
  internal/gitprovider/gitlab/gitlab.go
Labels: kind/bug, priority/normal, area/controller, backport/release-1.4

#3862 fix(docs): correctly reference outputs
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/compose-output.md
Labels: area/documentation, backport/release-1.4

#3851 feat: improve step timeout accuracy
  internal/controller/promotions/promotions.go
  internal/controller/promotions/promotions_test.go
  internal/promotion/mock_step_runner.go
  internal/promotion/promotion_test.go
  internal/promotion/registry.go
Labels: kind/enhancement, priority/normal, area/controller

#3868 fix(chart): give controller cluster-wide configmap reads
  charts/kargo/templates/controller/cluster-roles.yaml
Labels: kind/bug, priority/high, area/charts

#3864 fix(docs): Make compose-output example work
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/compose-output.md
Labels: kind/bug, area/documentation, priority/normal, backport/release-1.4

#3872 feat: bypass patch perms for refresh of stages and warehouses
  internal/server/refresh_stage_v1alpha1.go
  internal/server/refresh_warehouse_v1alpha1.go
  internal/server/refresh_warehouse_v1alpha1_test.go
Labels: area/security, kind/refactor, priority/normal, area/api

#3874 docs: document OCI annotations
  docs/docs/50-user-guide/20-how-to-guides/50-working-with-freight.md
  docs/docs/50-user-guide/20-how-to-guides/img/freight-oci-annotations.png
Labels: area/documentation, kind/enhancement, priority/normal, backport/release-1.4

#3876 fix(chart): PromotionTask validation registration
  charts/kargo/templates/webhooks/webhooks.yaml
Labels: kind/bug, priority/normal, area/charts, backport/release-1.4

#3885 chore: manual backport of #3835
  ui/package.json
  ui/pnpm-lock.yaml
  ui/src/extensions/extensions-context.ts
  ui/src/extensions/types.ts
  ui/src/features/stage/stage-details.tsx
Labels: kind/enhancement, kind/chore, area/ui, priority/normal

#3771 fix(ui): projects filter ui
  ui/src/features/project/list/project-list-filter.tsx
  ui/src/features/project/list/projects-list.tsx
Labels: kind/bug, area/ui, priority/normal

#3875 feat: move Project configuration to ProjectConfig resource
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/project_config_types.go
  api/v1alpha1/project_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/kargo/resources/crds/kargo.akuity.io_projectconfigs.yaml
  charts/kargo/resources/crds/kargo.akuity.io_projects.yaml
  charts/kargo/templates/controller/cluster-roles.yaml
  charts/kargo/templates/management-controller/cluster-roles.yaml
  charts/kargo/templates/users/cluster-roles.yaml
  charts/kargo/templates/webhooks-server/cluster-role.yaml
  charts/kargo/templates/webhooks/webhooks.yaml
  cmd/controlplane/webhooks.go
  docs/docs/50-user-guide/20-how-to-guides/20-working-with-projects.md
  docs/old-docs/30-how-to-guides/11-working-with-projects.md
  internal/controller/management/projects/projects.go
  internal/controller/management/projects/projects_test.go
  internal/controller/stages/regular_stages.go
  internal/controller/stages/regular_stages_test.go
  internal/webhook/project/webhook.go
  internal/webhook/project/webhook_test.go
  internal/webhook/projectconfig/webhook.go
  internal/webhook/projectconfig/webhook_test.go
  ui/src/gen/api/v1alpha1/generated_pb.ts
  ui/src/gen/schema/projectconfigs.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/projects.kargo.akuity.io_v1alpha1.json
Labels: kind/enhancement, priority/normal, area/controller, area/api

#3902 chore: deprecate gitRepoURL in API and UI
  api/v1alpha1/generated.proto
  api/v1alpha1/stage_types.go
  api/v1alpha1/warehouse_types.go
  charts/kargo/resources/crds/kargo.akuity.io_freights.yaml
  charts/kargo/resources/crds/kargo.akuity.io_promotions.yaml
  charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
  charts/kargo/resources/crds/kargo.akuity.io_warehouses.yaml
  docs/docs/50-user-guide/20-how-to-guides/30-working-with-warehouses.md
  docs/docs/50-user-guide/60-reference-docs/40-expressions.md
  docs/old-docs/35-references/20-expression-language.md
  internal/controller/warehouses/images.go
  internal/controller/warehouses/warehouses.go
  ui/src/features/assemble-freight/assemble-freight.tsx
  ui/src/features/assemble-freight/image-table.tsx
  ui/src/gen/api/v1alpha1/generated_pb.ts
  ui/src/gen/schema/freights.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/promotions.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/warehouses.kargo.akuity.io_v1alpha1.json
Labels: area/documentation, kind/chore, priority/high

#3899 docs: explain `promote` verb and add RBAC examples
  docs/docs/50-user-guide/50-security/20-access-controls/index.md
Labels: area/documentation, priority/normal, backport/release-1.4

#3903 fix(controller): allow promo when health is unknown
  internal/controller/stages/regular_stages.go
  internal/controller/stages/regular_stages_test.go
Labels: kind/bug, priority/high, area/controller

#3905 fix(controller): deal with the possibility of an App having a nil status field when we patch it
  internal/promotion/runner/builtin/argocd_updater.go
Labels: kind/bug, priority/high, area/controller, backport/release-1.4

#3912 chore: remove unused code
  internal/cli/client/errors.go
  internal/kargo-render/render.go
  internal/kargo/kargo.go
  internal/kustomize/kustomize.go
  internal/kustomize/kustomize_test.go
Labels: kind/chore, priority/low, area/controller

#3913 chore: remove deprecated `ProjectSecretLabelKey`
  api/v1alpha1/labels.go
  internal/promotion/simple_engine.go
  internal/promotion/simple_engine_test.go
  internal/server/delete_project_secret_v1alpha1.go
  internal/server/delete_project_secret_v1alpha1_test.go
  internal/server/list_project_secrets_v1alpha1.go
  internal/server/list_project_secrets_v1alpha1_test.go
  internal/server/update_project_secret_v1alpha1.go
  internal/server/update_project_secret_v1alpha1_test.go
Labels: kind/chore, priority/normal, area/api

#3914 chore: remove deprecated `messageFromSteps` field
  docs/docs/20-quickstart/index.md
  docs/docs/50-user-guide/20-how-to-guides/40-working-with-stages.md
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/argocd-update.md
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/git-commit.md
  docs/docs/50-user-guide/60-reference-docs/40-expressions.md
  docs/old-docs/20-quickstart.md
  docs/old-docs/30-how-to-guides/14-working-with-stages.md
  docs/old-docs/35-references/10-promotion-steps.md
  docs/old-docs/35-references/20-expression-language.md
  internal/promotion/runner/builtin/git_commiter.go
  internal/promotion/runner/builtin/git_commiter_test.go
  internal/promotion/runner/builtin/schemas/git-commit-config.json
  pkg/x/promotion/runner/builtin/zz_config_types.go
  ui/src/gen/directives/git-commit-config.json
Labels: kind/chore, priority/normal, area/controller, area/api

#3888 feat(controller): collect stats in project status
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/project_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/kargo/resources/crds/kargo.akuity.io_projects.yaml
  charts/kargo/templates/management-controller/cluster-roles.yaml
  internal/controller/management/projects/event_handlers.go
  internal/controller/management/projects/event_handlers_test.go
  internal/controller/management/projects/projects.go
  internal/controller/management/projects/projects_test.go
  internal/controller/management/projects/stats.go
  internal/controller/management/projects/stats_test.go
  ui/src/gen/api/v1alpha1/generated_pb.ts
  ui/src/gen/schema/projects.kargo.akuity.io_v1alpha1.json
Labels: kind/enhancement, priority/high, area/controller, area/crds

#3924 chore(docs): remove "old documentation"
  docs/old-docs/10-overview.md
  docs/old-docs/15-concepts.md
  docs/old-docs/20-quickstart.md
  docs/old-docs/30-how-to-guides/10-installing-kargo.md
  docs/old-docs/30-how-to-guides/11-working-with-projects.md
  docs/old-docs/30-how-to-guides/14-working-with-stages.md
  docs/old-docs/30-how-to-guides/15-working-with-freight.md
  docs/old-docs/30-how-to-guides/20-managing-credentials.md
  docs/old-docs/30-how-to-guides/25-argo-cd-integration.md
  docs/old-docs/30-how-to-guides/30-managing-user-permissions.md
  docs/old-docs/30-how-to-guides/_category_.json
  docs/old-docs/35-references/10-promotion-steps.md
  docs/old-docs/35-references/20-expression-language.md
  docs/old-docs/35-references/30-promotion-tasks.md
  docs/old-docs/35-references/_category_.json
  docs/old-docs/40-contributor-guide/10-hacking-on-kargo.md
  docs/old-docs/40-contributor-guide/15-release-procedures.md
  docs/old-docs/40-contributor-guide/20-signing-commits.md
  docs/old-docs/40-contributor-guide/30-code-of-conduct.md
  docs/old-docs/40-contributor-guide/5-debugging-kargo.md
  docs/old-docs/40-contributor-guide/index.md
  docs/old-docs/45-resources.md
  docs/old-docs/50-roadmap.md
  docs/old-docs/README.md
  docs/old-docs/_category_.json
  docs/old-docs/static/.nojekyll
  docs/old-docs/static/img/architecture.png
  docs/old-docs/static/img/argo-dashboard.png
  docs/old-docs/static/img/create-stage-2.png
  docs/old-docs/static/img/create-stage-3.png
  docs/old-docs/static/img/create-stage.png
  docs/old-docs/static/img/delete-stage.png
  docs/old-docs/static/img/kargo-dashboard-projects.png
  docs/old-docs/static/img/kargo-dashboard-promotion.png
  docs/old-docs/static/img/kargo-dashboard.png
  docs/old-docs/static/img/kargo-freight-verified.png
  docs/old-docs/static/img/kargo-frieght-timeline.png
  docs/old-docs/static/img/kargo-projects.png
  docs/old-docs/static/img/kargo-promote-option-2.png
  docs/old-docs/static/img/kargo-promote-option.png
  docs/old-docs/static/img/kargo.png
  docs/old-docs/static/img/logo.svg
  docs/old-docs/static/img/refresh-stage.png
  docs/old-docs/static/img/reverify-freight.png
  docs/old-docs/static/img/undraw_docusaurus_mountain.svg
  docs/old-docs/static/img/undraw_docusaurus_react.svg
  docs/old-docs/static/img/undraw_docusaurus_tree.svg
  docs/old-docs/static/img/verified-in.png
Labels: area/documentation, kind/chore, priority/normal

#3925 feat: allow gpg key override at commit-time
  internal/controller/git/bare_repo.go
  internal/controller/git/bare_repo_test.go
  internal/controller/git/base_repo.go
  internal/controller/git/repo.go
  internal/controller/git/repo_test.go
  internal/controller/git/work_tree.go
  internal/controller/git/work_tree_test.go
  internal/promotion/runner/builtin/git_cloner_test.go
  internal/promotion/runner/builtin/git_commiter_test.go
  internal/promotion/runner/builtin/git_pusher_test.go
Labels: kind/enhancement, area/security, priority/high, area/controller

#3209 feat: add support for Bitbucket to `git-open-pr` and `git-wait-for-pr`
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/git-open-pr.md
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/git-wait-for-pr.md
  go.mod
  go.sum
  internal/gitprovider/bitbucket/bitbucket.go
  internal/gitprovider/bitbucket/bitbucket_test.go
  internal/gitprovider/gitprovider.go
  internal/promotion/runner/builtin/git_pr_opener.go
  internal/promotion/runner/builtin/git_pr_waiter.go
  internal/promotion/runner/builtin/schemas/git-open-pr-config.json
  internal/promotion/runner/builtin/schemas/git-wait-for-pr-config.json
  pkg/x/promotion/runner/builtin/zz_config_types.go
  ui/src/gen/directives/git-open-pr-config.json
  ui/src/gen/directives/git-wait-for-pr-config.json
Labels: kind/enhancement, priority/low, area/controller

#3886 feat: add name and label selectors to PromotionPolicy
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/project_config_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/kargo/resources/crds/kargo.akuity.io_projectconfigs.yaml
  charts/kargo/resources/crds/kargo.akuity.io_projects.yaml
  docs/docs/50-user-guide/20-how-to-guides/20-working-with-projects.md
  internal/controller/management/projects/projects_test.go
  internal/controller/stages/regular_stages.go
  internal/controller/stages/regular_stages_test.go
  internal/controller/warehouses/git.go
  internal/controller/warehouses/git_test.go
  internal/pattern/matcher.go
  internal/pattern/matcher_test.go
  internal/webhook/projectconfig/webhook.go
  internal/webhook/projectconfig/webhook_test.go
  ui/src/gen/api/v1alpha1/generated_pb.ts
  ui/src/gen/schema/projectconfigs.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/projects.kargo.akuity.io_v1alpha1.json
Labels: kind/enhancement, priority/normal, area/controller, area/api

#3940 chore(deps): update dependencies
  go.mod
  go.sum
Labels: dependencies, go

#3930 docs: Fix typo
  docs/docs/50-user-guide/10-core-concepts/index.md
Labels: kind/bug, area/documentation, priority/normal

#3856 feat(cmd): support configuring metrics bind address
  cmd/controlplane/controller.go
  cmd/controlplane/garbage_collector.go
  cmd/controlplane/management_controller.go
  cmd/controlplane/webhooks.go
Labels: kind/enhancement, priority/normal, area/webhooks, area/controller, area/garbage-collector

#3944 fix(api): CEL validation `PromotionPolicy`
  Makefile
  api/v1alpha1/generated.proto
  api/v1alpha1/project_config_types.go
  charts/kargo/resources/crds/kargo.akuity.io_projectconfigs.yaml
  charts/kargo/resources/crds/kargo.akuity.io_projects.yaml
  ui/src/gen/api/v1alpha1/generated_pb.ts
  ui/src/gen/schema/projectconfigs.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/projects.kargo.akuity.io_v1alpha1.json
Labels: kind/bug, priority/high, area/api

#3879 chore: Adding init container support for the Controller in Helm
  charts/kargo/README.md
  charts/kargo/templates/controller/deployment.yaml
  charts/kargo/values.yaml
Labels: kind/enhancement, priority/low, area/charts

#3946 feat(ui): Project List Redesign
  ui/src/features/project/list/project-item/project-item.module.less
  ui/src/features/project/list/project-item/project-item.tsx
  ui/src/features/project/list/project-list-filter.tsx
  ui/src/features/project/list/projects-list.tsx
  ui/src/pages/projects.tsx
Labels: kind/enhancement, area/ui, priority/high

#3950 feat(ui): Drawer views improvements
  ui/src/features/freight/freight-details.tsx
  ui/src/features/project/settings/views/roles/create-role.tsx
  ui/src/features/stage/create-stage.tsx
  ui/src/features/stage/create-warehouse/create-warehouse.tsx
Labels: kind/enhancement, area/ui, priority/high

#3953 fix(webhook): ensure proper client injection
  internal/webhook/project/webhook.go
Labels: kind/bug, priority/high, area/webhooks

#3948 docs(installation): fix minor typo (double `with`)
  docs/docs/40-operator-guide/20-advanced-installation/20-advanced-with-argocd.md
Labels: area/documentation, priority/normal, backport/release-1.4

#3869 feat: mark skipped steps as skipped
  api/v1alpha1/generated.pb.go
  api/v1alpha1/promotion_types.go
  internal/controller/promotions/promotions.go
  internal/controller/promotions/promotions_test.go
  internal/promotion/runner/builtin/argocd_updater.go
  internal/promotion/runner/builtin/argocd_updater_test.go
  internal/promotion/runner/builtin/file_copier.go
  internal/promotion/runner/builtin/file_copier_test.go
  internal/promotion/runner/builtin/file_deleter.go
  internal/promotion/runner/builtin/file_deleter_test.go
  internal/promotion/runner/builtin/git_cloner.go
  internal/promotion/runner/builtin/git_cloner_test.go
  internal/promotion/runner/builtin/git_commiter.go
  internal/promotion/runner/builtin/git_commiter_test.go
  internal/promotion/runner/builtin/git_pr_opener.go
  internal/promotion/runner/builtin/git_pr_waiter.go
  internal/promotion/runner/builtin/git_pr_waiter_test.go
  internal/promotion/runner/builtin/git_pusher.go
  internal/promotion/runner/builtin/git_tree_clearer.go
  internal/promotion/runner/builtin/git_tree_clearer_test.go
  internal/promotion/runner/builtin/helm_chart_updater.go
  internal/promotion/runner/builtin/helm_chart_updater_test.go
  internal/promotion/runner/builtin/helm_template_runner.go
  internal/promotion/runner/builtin/helm_template_runner_test.go
  internal/promotion/runner/builtin/http_requester.go
  internal/promotion/runner/builtin/http_requester_test.go
  internal/promotion/runner/builtin/json_parser.go
  internal/promotion/runner/builtin/json_parser_test.go
  internal/promotion/runner/builtin/json_updater.go
  internal/promotion/runner/builtin/json_updater_test.go
  internal/promotion/runner/builtin/kustomize_builder.go
  internal/promotion/runner/builtin/kustomize_builder_test.go
  internal/promotion/runner/builtin/kustomize_image_setter.go
  internal/promotion/runner/builtin/kustomize_image_setter_test.go
  internal/promotion/runner/builtin/output_composer.go
  internal/promotion/runner/builtin/yaml_parser.go
  internal/promotion/runner/builtin/yaml_parser_test.go
  internal/promotion/runner/builtin/yaml_updater.go
  internal/promotion/runner/builtin/yaml_updater_test.go
  internal/promotion/simple_engine.go
  internal/promotion/simple_engine_test.go
  pkg/promotion/promotion.go
  ui/src/features/common/promotion-directive-step-status/promotion-step-status.ts
  ui/src/features/common/promotion-directive-step-status/utils.test.ts
  ui/src/features/common/promotion-directive-step-status/utils.ts
  ui/src/features/stage/promotion-details-modal.tsx
Labels: kind/enhancement, do not merge yet, area/ui, priority/normal, area/controller

#3922 feat: make git-commit step able to sign commits with user-configurable gpg key
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/git-clone.md
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/git-commit.md
  internal/controller/git/work_tree.go
  internal/promotion/runner/builtin/git_cloner.go
  internal/promotion/runner/builtin/git_cloner_test.go
  internal/promotion/runner/builtin/git_commiter.go
  internal/promotion/runner/builtin/git_commiter_test.go
  internal/promotion/runner/builtin/schemas/git-clone-config.json
  internal/promotion/runner/builtin/schemas/git-commit-config.json
  pkg/x/promotion/runner/builtin/zz_config_types.go
  ui/src/gen/directives/git-clone-config.json
  ui/src/gen/directives/git-commit-config.json
Labels: kind/enhancement, priority/high, area/controller

#3949 chore(api): remove deprecated `phase` and `message` fields from Project and Stage
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/project_config_types.go
  api/v1alpha1/project_types.go
  api/v1alpha1/stage_types.go
  api/v1alpha1/warehouse_types.go
  charts/kargo/resources/crds/kargo.akuity.io_projectconfigs.yaml
  charts/kargo/resources/crds/kargo.akuity.io_projects.yaml
  charts/kargo/resources/crds/kargo.akuity.io_promotions.yaml
  charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
  internal/cli/cmd/get/stages.go
  internal/controller/management/projects/projects.go
  internal/controller/management/projects/projects_test.go
  internal/controller/stages/control_flow_stages.go
  internal/controller/stages/control_flow_stages_test.go
  internal/controller/stages/regular_stages.go
  internal/controller/stages/regular_stages_test.go
  ui/src/features/common/stage-phase/stage-phase-icon.tsx
  ui/src/features/common/stage-phase/utils.ts
  ui/src/features/common/stage-status/stage-condition-icon.tsx
  ui/src/features/common/stage-status/styles.module.less
  ui/src/features/common/stage-status/truck-icon/styles.module.less
  ui/src/features/common/stage-status/truck-icon/truck-icon.tsx
  ui/src/features/common/stage-status/utils.ts
  ui/src/features/project/pipelines/nodes/stage-node.tsx
  ui/src/features/stage/stage-details.tsx
  ui/src/gen/api/v1alpha1/generated_pb.ts
  ui/src/gen/schema/projects.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/promotions.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
Labels: kind/chore, area/ui, priority/normal, area/api

#3957 docs(oidc-setup): fix wrong example (viewer→viewerS)
  docs/docs/40-operator-guide/40-security/20-openid-connect.md
Labels: kind/bug, area/documentation, priority/normal, backport/release-1.4
