Repository akuity/kargo, pull requests merged in 2025-03, with the labels that each got.

#3602 fix(ui): invalid verification duration
  ui/src/features/stage/utils/verification-phase.ts
  ui/src/features/stage/verifications.tsx
Labels: kind/bug, area/ui, priority/high, backport/release-1.3

#3610 fix(controller): replace missing credential lookup in git-clone step
  internal/directives/git_cloner.go
Labels: kind/bug, priority/high, area/controller, backport/release-1.3

#3609 chore: move generated step config types to pkg/x
  hack/codegen/directive-configs.sh
  internal/directives/argocd_revisions.go
  internal/directives/argocd_revisions_test.go
  internal/directives/argocd_updater.go
  internal/directives/argocd_updater_test.go
  internal/directives/file_copier.go
  internal/directives/file_copier_test.go
  internal/directives/file_deleter.go
  internal/directives/file_deleter_test.go
  internal/directives/git_cloner.go
  internal/directives/git_cloner_test.go
  internal/directives/git_commiter.go
  internal/directives/git_commiter_test.go
  internal/directives/git_pr_opener.go
  internal/directives/git_pr_opener_test.go
  internal/directives/git_pr_waiter.go
  internal/directives/git_pr_waiter_test.go
  internal/directives/git_pusher.go
  internal/directives/git_pusher_test.go
  internal/directives/git_tree_clearer.go
  internal/directives/git_tree_clearer_test.go
  internal/directives/helm_chart_updater.go
  internal/directives/helm_chart_updater_test.go
  internal/directives/helm_template_runner.go
  internal/directives/helm_template_runner_test.go
  internal/directives/http_requester.go
  internal/directives/http_requester_test.go
  internal/directives/json_parser.go
  internal/directives/json_parser_test.go
  internal/directives/json_updater.go
  internal/directives/json_updater_test.go
  internal/directives/kustomize_builder.go
  internal/directives/kustomize_builder_test.go
  internal/directives/kustomize_image_setter.go
  internal/directives/kustomize_image_setter_test.go
  internal/directives/output_composer.go
  internal/directives/registry.go
  internal/directives/simple_engine.go
  internal/directives/yaml_parser.go
  internal/directives/yaml_parser_test.go
  internal/directives/yaml_updater.go
  internal/directives/yaml_updater_test.go
  internal/event/promotion.go
  pkg/x/directive/builtin/zz_config_types.go
Labels: kind/chore, priority/normal, area/controller

#3614 fix(ui): graph edge glitch
  ui/src/features/project/pipelines/graph.tsx
  ui/src/features/project/pipelines/nodes/custom-node.tsx
Labels: kind/bug, area/ui, priority/normal, backport/release-1.3

#3613 chore: move version package to pkg/x/version
  Dockerfile
  Makefile
  cmd/controlplane/api.go
  cmd/controlplane/controller.go
  cmd/controlplane/garbage_collector.go
  cmd/controlplane/management_controller.go
  cmd/controlplane/version.go
  cmd/controlplane/webhooks.go
  internal/cli/cmd/version/version.go
  internal/server/get_version_info_v1alpha1.go
  pkg/api/service/v1alpha1/types.go
  pkg/x/version/version.go
Labels: kind/chore, priority/normal, area/webhooks, area/controller, area/api

#3617 refactor(credentials): replace `Helper` type with `Provider` interface
  internal/controller/warehouses/git.go
  internal/controller/warehouses/git_test.go
  internal/controller/warehouses/helm.go
  internal/controller/warehouses/helm_test.go
  internal/controller/warehouses/images.go
  internal/controller/warehouses/images_test.go
  internal/credentials/credentials.go
  internal/credentials/database.go
  internal/credentials/kubernetes/basic/basic.go
  internal/credentials/kubernetes/basic/basic_test.go
  internal/credentials/kubernetes/database.go
  internal/credentials/kubernetes/database_test.go
  internal/credentials/kubernetes/ecr/access_key.go
  internal/credentials/kubernetes/ecr/access_key_test.go
  internal/credentials/kubernetes/ecr/common.go
  internal/credentials/kubernetes/ecr/common_test.go
  internal/credentials/kubernetes/ecr/managed_identity.go
  internal/credentials/kubernetes/ecr/managed_identity_test.go
  internal/credentials/kubernetes/gar/common.go
  internal/credentials/kubernetes/gar/common_test.go
  internal/credentials/kubernetes/gar/service_account_key.go
  internal/credentials/kubernetes/gar/service_account_key_test.go
  internal/credentials/kubernetes/gar/workload_identity_federation.go
  internal/credentials/kubernetes/gar/workload_identity_federation_test.go
  internal/credentials/kubernetes/github/app.go
  internal/credentials/kubernetes/github/app_test.go
  internal/directives/git_cloner.go
  internal/directives/git_pr_opener.go
  internal/directives/git_pr_waiter.go
  internal/directives/git_pusher.go
  internal/directives/helm_chart_updater.go
  internal/directives/helm_chart_updater_test.go
Labels: kind/enhancement, kind/refactor, priority/normal, area/controller

#3621 fix(credentials): comparable constructor return types
  internal/credentials/kubernetes/ecr/access_key.go
  internal/credentials/kubernetes/ecr/access_key_test.go
  internal/credentials/kubernetes/ecr/managed_identity.go
  internal/credentials/kubernetes/gar/service_account_key.go
  internal/credentials/kubernetes/gar/service_account_key_test.go
  internal/credentials/kubernetes/gar/workload_identity_federation.go
  internal/credentials/kubernetes/github/app.go
  internal/credentials/kubernetes/github/app_test.go
Labels: kind/bug, priority/high, area/controller

#3622 chore: move rollouts api stubs
  api/service/v1alpha1/service.proto
  api/stubs/rollouts/v1alpha1/analysis_types.go
  api/stubs/rollouts/v1alpha1/doc.go
  api/stubs/rollouts/v1alpha1/generated.pb.go
  api/stubs/rollouts/v1alpha1/generated.proto
  api/stubs/rollouts/v1alpha1/groupversion_info.go
  api/stubs/rollouts/v1alpha1/types.go
  api/stubs/rollouts/v1alpha1/zz_generated.deepcopy.go
  buf.yaml
  cmd/controlplane/controller.go
  hack/codegen/proto.sh
  internal/api/stubs/rollouts/analysis.go
  internal/api/stubs/rollouts/analysis_test.go
  internal/controller/management/projects/projects.go
  internal/controller/stages/control_flow_stages.go
  internal/controller/stages/control_flow_stages_test.go
  internal/controller/stages/event_handlers.go
  internal/controller/stages/event_handlers_test.go
  internal/controller/stages/regular_stages.go
  internal/controller/stages/regular_stages_test.go
  internal/credentials/kubernetes/database.go
  internal/rollouts/analysis_run_builder.go
  internal/rollouts/analysis_run_builder_test.go
  internal/rollouts/analysis_template.go
  internal/rollouts/analysis_template_test.go
  internal/server/delete_analysistemplate_v1alpha1.go
  internal/server/delete_analysistemplate_v1alpha1_test.go
  internal/server/delete_clusteranalysistemplate_v1alpha1.go
  internal/server/delete_clusteranalysistemplate_v1alpha1_test.go
  internal/server/get_analysisrun_v1alpha1.go
  internal/server/get_analysisrun_v1alpha1_test.go
  internal/server/get_analysistemplate_v1alpha1.go
  internal/server/get_analysistemplate_v1alpha1_test.go
  internal/server/get_clusteranalysistemplate_v1alpha1.go
  internal/server/get_clusteranalysistemplate_v1alpha1_test.go
  internal/server/kubernetes/client.go
  internal/server/list_analysistemplates_v1alpha1.go
  internal/server/list_analysistemplates_v1alpha1_test.go
  internal/server/list_clusteranalysistemplates_v1alpha1.go
  internal/server/list_clusteranalysistemplates_v1alpha1_test.go
  internal/server/rbac/policy_rules.go
  internal/server/server.go
  pkg/api/service/v1alpha1/service.pb.go
  ui/src/features/common/analysis-modal/analysis-modal.tsx
  ui/src/features/common/analysis-modal/transforms.ts
  ui/src/features/common/analysis-modal/types.ts
  ui/src/features/project/analysis-templates/analysis-templates-list.tsx
  ui/src/features/settings/analysis-templates/analysis-templates.tsx
  ui/src/features/utils/cache/analysis-templates.ts
  ui/src/gen/rollouts/api/v1alpha1/generated_pb.ts
  ui/src/gen/service/v1alpha1/service_pb.ts
  ui/src/gen/stubs/rollouts/v1alpha1/generated_pb.ts
Labels: kind/chore, priority/normal, area/controller, area/api

#3618 feat(ui): hide subscription and fix stage node overflow
  ui/src/features/project/pipelines/context/pipeline-context.ts
  ui/src/features/project/pipelines/graph.tsx
  ui/src/features/project/pipelines/nodes/custom-node.tsx
  ui/src/features/project/pipelines/nodes/freight-label.tsx
  ui/src/features/project/pipelines/pipelines.tsx
  ui/src/features/project/pipelines/utils/use-pipeline-graph.ts
Labels: kind/bug, area/ui, priority/normal

#3603 feat: annotate argocd context to stage and move deep link back to stage details
  api/v1alpha1/annotations.go
  internal/api/finalizers.go
  internal/api/finalizers_test.go
  internal/api/stage.go
  internal/api/stage_test.go
  internal/controller/stages/control_flow_stages.go
  internal/controller/stages/control_flow_stages_test.go
  internal/controller/stages/regular_stages.go
  ui/src/features/stage/stage-details.tsx
  ui/src/plugins/argocd-plugin/argocd-plugin.tsx
  ui/src/plugins/argocd-plugin/deep-link/promotion.tsx
  ui/src/plugins/index.tsx
Labels: area/ui, priority/normal, area/controller

#3645 docs: releaseName is now required by `helm-template`
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/helm-template.md
  docs/old-docs/35-references/10-promotion-steps.md
Labels: area/documentation, backport/release-1.3

#3650 fix(api): sort warehouses when listing
  internal/server/list_warehouses_v1alpha1.go
Labels: kind/bug, priority/normal, area/api, backport/release-1.3

#3642 fix(directives): compose-output available to task
  internal/directives/simple_engine_promote.go
  internal/directives/simple_engine_promote_test.go
Labels: kind/bug, priority/normal, area/controller, backport/release-1.3

#3654 chore: support `ConsecutiveSuccessLimit` from Argo Rollouts 1.8.0
  Makefile
  api/stubs/rollouts/v1alpha1/analysis_types.go
  api/stubs/rollouts/v1alpha1/generated.pb.go
  api/stubs/rollouts/v1alpha1/generated.proto
  api/stubs/rollouts/v1alpha1/zz_generated.deepcopy.go
  hack/quickstart/install.sh
  hack/quickstart/k3d.sh
  hack/quickstart/kind.sh
  ui/src/gen/api/stubs/rollouts/v1alpha1/generated_pb.ts
Labels: priority/normal, area/controller, area/api, dependencies

#3689 fix(api): update Git branch validation
  api/v1alpha1/generated.proto
  api/v1alpha1/warehouse_types.go
  charts/kargo/resources/crds/kargo.akuity.io_warehouses.yaml
  ui/src/gen/api/v1alpha1/generated_pb.ts
  ui/src/gen/schema/warehouses.kargo.akuity.io_v1alpha1.json
Labels: kind/bug, priority/high, area/api, backport/release-1.3

#3705 chore: update Go dependencies
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: dependencies, go

#3292 fix: responsive versioned dropdown
  docs/src/components/VersionDropdown.css
  docs/src/components/VersionDropdown.js
Labels: backport/release-1.0, backport/release-1.1, backport/release-1.2

#3682 feat(ui): analysis run logs
  ui/src/app.tsx
  ui/src/config/paths.ts
  ui/src/features/common/analysis-modal/analysis-modal.tsx
  ui/src/features/common/analysis-run-logs/analysis-run-logs.tsx
  ui/src/features/common/analysis-run-logs/extract-analysis-run.ts
  ui/src/features/common/analysis-run-logs/use-monaco-editor-log-language.ts
  ui/src/pages/analysis-run-logs.tsx
Labels: kind/enhancement, area/ui, priority/high

#3716 chore: udpate dependabot config to account for new modules
  .github/dependabot.yml
Labels: kind/chore, priority/normal, dependencies

#3676 feat(image): collect OCI annotations for discovered images
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/stage_types.go
  api/v1alpha1/warehouse_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/kargo/resources/crds/kargo.akuity.io_freights.yaml
  charts/kargo/resources/crds/kargo.akuity.io_promotions.yaml
  charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
  charts/kargo/resources/crds/kargo.akuity.io_warehouses.yaml
  internal/controller/warehouses/images.go
  internal/controller/warehouses/warehouses.go
  internal/image/image.go
  internal/image/repository_client.go
  internal/image/repository_client_test.go
  internal/image/selector_ghcr_test.go
  ui/src/gen/api/v1alpha1/generated_pb.ts
  ui/src/gen/schema/freights.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/promotions.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/warehouses.kargo.akuity.io_v1alpha1.json
Labels: kind/enhancement, priority/normal, area/controller, area/api

#3725 docs: document `Annotations` of `Image` object
  docs/docs/50-user-guide/60-reference-docs/40-expressions.md
Labels: area/documentation, kind/enhancement, priority/normal

#3727 feat(cli): improve UX (re-)login
  internal/cli/cmd/login/login.go
  internal/cli/cmd/login/login_test.go
  internal/cli/config/config.go
Labels: kind/enhancement, priority/normal, area/cli, area/ux

#3715 feat(ui): visualize oci annotation
  internal/image/repository_client.go
  internal/image/repository_client_test.go
  ui/src/features/assemble-freight/assemble-freight.tsx
  ui/src/features/freight-timeline/freight-content-item.tsx
  ui/src/features/freight-timeline/freight-contents.tsx
  ui/src/features/freight-timeline/freight-item.tsx
  ui/src/features/freight-timeline/open-container-initiative-utils.ts
  ui/src/features/freight/artifact-metadata.tsx
  ui/src/features/freight/flatten-freight-origin-utils.ts
  ui/src/features/freight/freight-details.tsx
Labels: kind/enhancement, area/ui, priority/high

#3729 chore: run go mod tidy
  go.mod
Labels: kind/chore, priority/normal, dependencies

#3730 fix(chart): GOMAXPROCS set request if limit absent
  charts/kargo/templates/_helpers.tpl
  charts/kargo/templates/api/deployment.yaml
  charts/kargo/templates/controller/deployment.yaml
  charts/kargo/templates/dex-server/deployment.yaml
  charts/kargo/templates/garbage-collector/cron-job.yaml
  charts/kargo/templates/management-controller/deployment.yaml
  charts/kargo/templates/webhooks-server/deployment.yaml
Labels: kind/bug, priority/normal, area/charts

#3731 fix: soak time bug
  internal/api/stage.go
  internal/api/stage_test.go
  internal/api/warehouse.go
  internal/api/warehouse_test.go
  internal/controller/stages/regular_stages_test.go
Labels: kind/bug, priority/high, area/controller, area/api, backport/release-1.3

#3739 chore(backport release-1.3): fix: soak time bug
  api/v1alpha1/stage_helpers.go
  api/v1alpha1/stage_helpers_test.go
  api/v1alpha1/warehouse_helpers.go
  api/v1alpha1/warehouse_helpers_test.go
  internal/controller/stages/regular_stages_test.go
Labels: kind/bug, priority/high, area/controller, area/api

#3737 feat: Promotion and Cluster promotion tasks UI
  api/service/v1alpha1/service.pb.go
  api/service/v1alpha1/service.proto
  api/service/v1alpha1/svcv1alpha1connect/service.connect.go
  internal/server/get_cluster_promotion_task_v1alpha1.go
  internal/server/get_cluster_promotion_task_v1alpha1_test.go
  internal/server/get_promotion_task_v1alpha1.go
  internal/server/get_promotion_task_v1alpha1_test.go
  internal/server/list_cluster_promotion_tasks_v1alpha1.go
  internal/server/list_cluster_promotion_tasks_v1alpha1_test.go
  internal/server/list_promotion_tasks_v1alpha1.go
  internal/server/list_promotion_tasks_v1alpha1_test.go
  internal/server/testdata/cluster-promotion-task.yaml
  internal/server/testdata/promotion-task.yaml
  ui/src/app.tsx
  ui/src/config/paths.ts
  ui/src/features/project/pipelines/warehouse/edit-warehouse.tsx
  ui/src/features/promotion-tasks/create-promotion-task.tsx
  ui/src/features/promotion-tasks/edit-promotion-task-modal.tsx
  ui/src/features/promotion-tasks/promotion-task-example.ts
  ui/src/features/promotion-tasks/promotion-tasks.tsx
  ui/src/features/settings/cluster-promotion-tasks/cluster-promotion-task-example.ts
  ui/src/features/settings/cluster-promotion-tasks/cluster-promotion-tasks.tsx
  ui/src/features/settings/cluster-promotion-tasks/create-cluster-promotion-task.tsx
  ui/src/features/settings/cluster-promotion-tasks/edit-cluster-promotion-task-modal.tsx
  ui/src/features/stage/create-warehouse/create-warehouse.tsx
  ui/src/features/utils/manifest-generator.ts
  ui/src/gen/api/service/v1alpha1/service-KargoService_connectquery.ts
  ui/src/gen/api/service/v1alpha1/service_pb.ts
  ui/src/pages/project.tsx
  ui/src/pages/settings.tsx
  ui/src/utils/decode-raw-data.ts
Labels: area/ui, priority/high, area/api

#3742 fix(ui): freight artifact name overflow issue
  ui/src/features/common/truncate-middle.tsx
  ui/src/features/freight-timeline/freight-content-item.tsx
Labels: kind/bug, area/ui, priority/high

#3740 fix: always honor availability strategy
  api/v1alpha1/freight_types.go
  api/v1alpha1/stage_types.go
  api/v1alpha1/stage_types_test.go
  internal/api/stage.go
  internal/api/warehouse.go
  internal/api/warehouse_test.go
Labels: kind/bug, priority/high, area/webhooks, area/api

#3744 chore(backport release-1.3): fix: always honor availability strategy (#3740)
  api/v1alpha1/freight_helpers.go
  api/v1alpha1/stage_helpers.go
  api/v1alpha1/stage_helpers_test.go
  api/v1alpha1/warehouse_helpers.go
  api/v1alpha1/warehouse_helpers_test.go
Labels: kind/bug, priority/high, area/webhooks, area/api

#3745 chore(ci): remove generated code from coverage reports
  .github/workflows/ci.yaml
Labels: kind/chore, area/ci-process, priority/normal

#3748 chore: return error if trying to access analysis run logs and not configured
  internal/server/get_analysisrun_logs_v1alpha1.go
Labels: kind/chore, priority/high, area/api

#3764 fix(ui): windows cli link
  ui/src/pages/downloads.tsx
Labels: kind/bug, area/ui, priority/normal, backport/release-1.3
