Repository akuity/kargo, pull requests merged in 2025-09, with the labels that each got.

#4970 chore(deps): bump golang from 1.24.6-bookworm to 1.25.0-trixie
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  Dockerfile
  Dockerfile.dev
  api/go.mod
  go.mod
  hack/tools/go.mod
  pkg/go.mod
Labels: area/ci-process, dependencies, go, docker

#4982 feat(ui): auto select relevant warehouse during promotion
  ui/src/features/project/pipelines/freight/freight-timeline.tsx
Labels: kind/enhancement, area/ui, priority/normal

#4991 fix(ui): filter issues
  ui/src/features/project/pipelines/url-params/use-freight-timeline-controller-store.ts
Labels: kind/bug, area/ui, priority/high, area/regression, backport/release-1.7

#4981 feat(ui): option to hide minimap
  ui/src/app.tsx
  ui/src/features/project/pipelines/context/freight-timeline-controller-context.ts
  ui/src/features/project/pipelines/graph/graph.tsx
  ui/src/features/project/pipelines/url-params/use-freight-timeline-controller-store.ts
Labels: kind/enhancement, area/ui, priority/normal

#4923 feat(ui): stage node links
  api/service/v1alpha1/service.pb.go
  api/service/v1alpha1/service.proto
  docs/docs/90-api-documentation.md
  internal/server/get_config_v1alpha1.go
  ui/src/features/project/pipelines/context/dictionary-context.ts
  ui/src/features/project/pipelines/nodes/analysis-run-logs-link.tsx
  ui/src/features/project/pipelines/nodes/argocd-link.tsx
  ui/src/features/project/pipelines/nodes/pull-request-link.tsx
  ui/src/features/project/pipelines/nodes/stage-meta-utils.ts
  ui/src/features/project/pipelines/nodes/stage-node.tsx
  ui/src/features/project/pipelines/pipelines.tsx
  ui/src/features/stage/promotion-steps.tsx
  ui/src/features/stage/stage-actions.tsx
  ui/src/features/stage/use-get-argocd-links.ts
  ui/src/features/stage/utils/promotion.ts
  ui/src/gen/api/service/v1alpha1/service_pb.ts
  ui/src/plugins/atoms/plugin-helper.ts
Labels: kind/enhancement, area/ui, priority/normal

#4983 feat(ui): show artifact icons and have filter for it
  ui/src/features/project/pipelines/freight/artifact-icon.tsx
  ui/src/features/project/pipelines/freight/freight-artifact.tsx
  ui/src/features/project/pipelines/nodes/stage-freight.tsx
Labels: kind/enhancement, area/ui, priority/normal, area/usability

#5023 refactor(events): Rename encoding for event fields
  pkg/event/freight.go
  pkg/event/promotion.go
Labels: kind/refactor, priority/normal

#5029 chore: Revert "chore(backport release-1.7): fix(step)!: tighten validation `desiredRevision` (#5013)
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/argocd-update.md
  internal/promotion/runner/builtin/argocd_updater_test.go
  internal/promotion/runner/builtin/schemas/argocd-update-config.json
  pkg/x/promotion/runner/builtin/zz_config_types.go
  ui/src/gen/directives/argocd-update-config.json
Labels: kind/bug, priority/high, area/controller

#5030 chore: Revert "fix(step)!: tighten validation `desiredRevision` (#4846)"
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/argocd-update.md
  internal/promotion/runner/builtin/argocd_updater_test.go
  internal/promotion/runner/builtin/schemas/argocd-update-config.json
  pkg/x/promotion/runner/builtin/zz_config_types.go
  ui/src/gen/directives/argocd-update-config.json
Labels: kind/bug, kind/chore, priority/normal, area/controller

#5032 fix(event): Fix missing rename
  pkg/event/freight.go
Labels: kind/bug, priority/high

#5025 feat(ui): Drag and Drop Promotion
  ui/package.json
  ui/pnpm-lock.yaml
  ui/src/features/common/confirm-modal/confirm-modal.tsx
  ui/src/features/common/confirm-modal/use-confirm-modal.tsx
  ui/src/features/project/pipelines/freight/freight-card.tsx
  ui/src/features/project/pipelines/freight/freight-timeline.tsx
  ui/src/features/project/pipelines/nodes/stage-node.tsx
  ui/src/features/project/pipelines/pipelines.tsx
  ui/src/features/project/pipelines/promotion/drag-and-drop/dnd-promotion-context.tsx
  ui/src/features/project/pipelines/promotion/drag-and-drop/drop-overlay.module.less
  ui/src/features/project/pipelines/promotion/drag-and-drop/drop-overlay.tsx
  ui/src/features/project/pipelines/promotion/use-manual-approval-modal.tsx
Labels: area/ui, priority/normal

#4995 feat(controller): narrow scope of github app installation access tokens
  api/v1alpha1/annotations.go
  docs/docs/50-user-guide/50-security/30-managing-credentials.md
  go.mod
  go.sum
  internal/credentials/credentials.go
  internal/credentials/kubernetes/basic/basic.go
  internal/credentials/kubernetes/basic/basic_test.go
  internal/credentials/kubernetes/database.go
  internal/credentials/kubernetes/ecr/access_key.go
  internal/credentials/kubernetes/ecr/access_key_test.go
  internal/credentials/kubernetes/ecr/managed_identity.go
  internal/credentials/kubernetes/ecr/managed_identity_test.go
  internal/credentials/kubernetes/gar/service_account_key.go
  internal/credentials/kubernetes/gar/service_account_key_test.go
  internal/credentials/kubernetes/gar/workload_identity_federation.go
  internal/credentials/kubernetes/gar/workload_identity_federation_test.go
  internal/credentials/kubernetes/github/app.go
  internal/credentials/kubernetes/github/app_test.go
Labels: area/documentation, kind/enhancement, area/security, priority/low, area/controller

#5063 feat(ui): Increase Stage name visibility on bright bg colors
  ui/src/features/project/pipelines/nodes/stage-meta-utils.ts
  ui/src/features/project/pipelines/nodes/stage-node.tsx
  ui/src/utils/get-contrast-text-color.test.ts
  ui/src/utils/get-contrast-text-color.ts
Labels: kind/enhancement, area/ui, priority/normal

#5002 feat: support special characters for OIDC mappings
  api/rbac/v1alpha1/annotations.go
  api/rbac/v1alpha1/annotations_test.go
  charts/kargo/templates/users/service-accounts.yaml
  docs/docs/40-operator-guide/40-security/20-openid-connect/index.md
  docs/docs/40-operator-guide/40-security/30-access-controls.md
  docs/docs/50-user-guide/50-security/20-access-controls/index.md
  docs/docs/50-user-guide/60-reference-docs/70-annotations.md
  internal/controller/management/projects/projects.go
  internal/indexer/indexer.go
  internal/indexer/indexer_test.go
  internal/server/rbac/roles.go
  internal/server/rbac/roles_test.go
Labels: kind/bug, area/security, priority/normal

#5066 chore: update docusaurus 3.8.1
  docs/package.json
  docs/plugins/gtag/package.json
  docs/plugins/gtag/pnpm-lock.yaml
  docs/pnpm-lock.yaml
Labels: area/documentation, kind/chore, priority/low, backport/release-1.7

#5067 refactor(api-server): dry up api endpoints
  internal/server/common.go
  internal/server/common_test.go
  internal/server/get_analysisrun_v1alpha1.go
  internal/server/get_analysistemplate_v1alpha1.go
  internal/server/get_cluster_config_v1alpha1.go
  internal/server/get_cluster_promotion_task_v1alpha1.go
  internal/server/get_clusteranalysistemplate_v1alpha1.go
  internal/server/get_config_map_v1alpha1.go
  internal/server/get_credentials_v1alpha1.go
  internal/server/get_freight_v1alpha1.go
  internal/server/get_project_config_v1alpha1.go
  internal/server/get_project_v1alpha1.go
  internal/server/get_promotion_task_v1alpha1.go
  internal/server/get_promotion_v1alpha1.go
  internal/server/get_stage_v1alpha1.go
  internal/server/get_warehouse_v1alpha1.go
Labels: kind/refactor, priority/low, area/api-server

#5069 feat(events)!: Add an event ID to all events
  pkg/event/custom.go
  pkg/event/event.go
  pkg/event/event_test.go
  pkg/event/freight.go
  pkg/event/freight_test.go
  pkg/event/kubernetes/kubernetes.go
  pkg/event/kubernetes/kubernetes_test.go
  pkg/event/promotion.go
  pkg/event/promotion_test.go
Labels: kind/enhancement, priority/normal, area/controller

#4998 chore: small README.md updates
  README.md
Labels: area/documentation, kind/chore, priority/normal

#4861 feat: `set-metadata` promo step, deprecate two-arg `freightMetadata` format, add `stageMetadata` handling
  api/v1alpha1/freight_types_test.go
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/stage_types.go
  api/v1alpha1/stage_types_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/jira.md
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/set-metadata.md
  docs/docs/50-user-guide/60-reference-docs/40-expressions.md
  docs/docs/90-api-documentation.md
  internal/expressions/function/functions.go
  internal/expressions/function/functions_test.go
  internal/promotion/runner/builtin/init.go
  internal/promotion/runner/builtin/metadata_setter.go
  internal/promotion/runner/builtin/metadata_setter_test.go
  internal/promotion/runner/builtin/schemas/set-metadata-config.json
  pkg/x/promotion/runner/builtin/zz_config_types.go
  ui/src/gen/api/v1alpha1/generated_pb.ts
  ui/src/gen/directives/set-metadata-config.json
  ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
Labels: kind/enhancement, priority/high, area/controller, area/crds

#5084 fix(ci): set permissions for linters
  .github/workflows/ci.yaml
Labels: area/ci-process, priority/normal

#5104 fix: makefile syntax changes
  Makefile
Labels: kind/chore, area/devx, priority/low

#4914 fix: prevent nil pointer dereference in buildTargetFreightCollection
  pkg/controller/promotions/promotions.go
  pkg/controller/promotions/promotions_test.go
Labels: kind/bug, priority/normal, area/controller
