Repository akuity/kargo, pull requests merged in 2025-01, with the labels that each got.

#3192 fix: incorrectly worded error message in argocd-update is corrected
  internal/directives/argocd_updater.go
  internal/directives/argocd_updater_test.go
Labels: kind/bug, priority/normal, area/controller

#3164 fix(ui): stage phase icon
  ui/src/features/common/stage-phase/stage-phase-icon.tsx
  ui/src/features/common/stage-phase/styles.module.less
  ui/src/features/common/stage-phase/truck-icon/styles.module.less
  ui/src/features/common/stage-phase/truck-icon/truck-icon.tsx
  ui/src/features/common/stage-phase/utils.ts
  ui/src/features/stage/stage-details.tsx
Labels: kind/bug, area/ui, priority/normal

#3169 fix(ui): implicit verification filter
  ui/src/features/stage/verifications.tsx
Labels: kind/bug, area/ui, priority/normal

#3174 fix(ui): link to image repo correctly in Warehouse UI
  ui/src/features/project/pipelines/warehouse/repo-subscriptions.tsx
Labels: kind/bug, area/ui, priority/normal

#3218 feat: Mount path /tmp as emptyDir volume
  charts/kargo/templates/controller/deployment.yaml
Labels: kind/enhancement, priority/normal, area/controller, area/charts

#3100 feat: factor optional "soak time" into freight availability
  api/v1alpha1/freight_helpers.go
  api/v1alpha1/freight_helpers_test.go
  api/v1alpha1/freight_types.go
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/stage_helpers.go
  api/v1alpha1/stage_helpers_test.go
  api/v1alpha1/stage_types.go
  api/v1alpha1/stage_types_test.go
  api/v1alpha1/warehouse_helpers.go
  api/v1alpha1/warehouse_helpers_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/kargo/resources/crds/kargo.akuity.io_freights.yaml
  charts/kargo/resources/crds/kargo.akuity.io_promotions.yaml
  charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
  internal/api/approve_freight_v1alpha1.go
  internal/api/promote_downstream_v1alpha1.go
  internal/api/promote_downstream_v1alpha1_test.go
  internal/api/promote_to_stage_v1alpha1.go
  internal/api/query_freights_v1alpha1.go
  internal/api/query_freights_v1alpha1_test.go
  internal/api/server.go
  internal/controller/promotions/promotions.go
  internal/controller/stages/control_flow_stages.go
  internal/controller/stages/control_flow_stages_test.go
  internal/controller/stages/event_handlers.go
  internal/controller/stages/regular_stages.go
  internal/controller/stages/regular_stages_test.go
  internal/indexer/indexer.go
  internal/indexer/indexer_test.go
  internal/webhook/freight/webhook.go
  internal/webhook/promotion/webhook.go
  ui/src/gen/schema/freights.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/promotions.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
  ui/src/gen/v1alpha1/generated_pb.ts
Labels: kind/enhancement, priority/high, area/controller, area/api

#3235 fix: warehouse branch regex that was to limiting
  api/v1alpha1/generated.proto
  api/v1alpha1/warehouse_types.go
  charts/kargo/resources/crds/kargo.akuity.io_warehouses.yaml
  ui/src/gen/schema/warehouses.kargo.akuity.io_v1alpha1.json
  ui/src/gen/v1alpha1/generated_pb.ts
Labels: kind/bug, priority/high, area/crds, backport/release-1.1

#2914 docs: updated kargo ui snapshot
  README.md
  docs/docs/10-overview.md
  docs/static/img/kargo-dashboard.png
  docs/static/img/screenshot.png
Labels: area/documentation, kind/chore, priority/high, backport/release-1.1

#3243 refactor(chart): generalize option that specifies TLS is terminated upstream
  charts/kargo/README.md
  charts/kargo/templates/_helpers.tpl
  charts/kargo/values.yaml
Labels: kind/refactor, priority/high, area/charts

#3245 fix(chart): RFC 1132 compliant name for tmp mount
  charts/kargo/templates/controller/deployment.yaml
Labels: kind/bug, priority/high, area/charts

#3121 feat: (cluster) Promotion tasks
  api/v1alpha1/cluster_promotion_task_types.go
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/promotion_task_types.go
  api/v1alpha1/promotion_types.go
  api/v1alpha1/stage_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/kargo/resources/crds/kargo.akuity.io_clusterpromotiontasks.yaml
  charts/kargo/resources/crds/kargo.akuity.io_promotions.yaml
  charts/kargo/resources/crds/kargo.akuity.io_promotiontasks.yaml
  charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
  charts/kargo/templates/api/cluster-role.yaml
  charts/kargo/templates/controller/cluster-roles.yaml
  charts/kargo/templates/users/cluster-roles.yaml
  charts/kargo/templates/webhooks-server/cluster-role.yaml
  charts/kargo/templates/webhooks/webhooks.yaml
  cmd/controlplane/webhooks.go
  internal/api/promote_downstream_v1alpha1.go
  internal/api/promote_downstream_v1alpha1_test.go
  internal/api/promote_to_stage_v1alpha1.go
  internal/api/promote_to_stage_v1alpha1_test.go
  internal/controller/promotions/promotions.go
  internal/controller/stages/regular_stages.go
  internal/controller/stages/regular_stages_test.go
  internal/directives/output_composer.go
  internal/directives/promotions.go
  internal/directives/schemas/compose-output-config.json
  internal/directives/simple_engine.go
  internal/directives/simple_engine_promote.go
  internal/directives/zz_config_types.go
  internal/indexer/indexer.go
  internal/indexer/indexer_test.go
  internal/kargo/kargo.go
  internal/kargo/kargo_test.go
  internal/kargo/promotion_builder.go
  internal/kargo/promotion_builder_test.go
  internal/webhook/promotion/webhook.go
  internal/webhook/promotiontask/webhook.go
  internal/webhook/promotiontask/webhook_test.go
  ui/src/features/stage/create-stage.tsx
  ui/src/features/stage/promotion-steps-wizard/use-promotion-wizard-steps-state.ts
  ui/src/gen/directives/compose-output-config.json
  ui/src/gen/schema/clusterpromotiontasks.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/promotions.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/promotiontasks.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
  ui/src/gen/v1alpha1/generated_pb.ts
Labels: kind/enhancement, priority/high, area/controller, area/api

#2608 docs: working with stages documentation
  docs/docs/15-concepts.md
  docs/docs/30-how-to-guides/14-working-with-stages.md
  docs/static/img/create-stage-2.png
  docs/static/img/create-stage-3.png
  docs/static/img/create-stage.png
  docs/static/img/delete-stage.png
  docs/static/img/refresh-stage.png
  docs/static/img/reverify-freight.png
  docs/static/img/verified-in.png
Labels: area/documentation, kind/enhancement, priority/high, backport/release-1.1

#3259 chore(deps): bump library/node from 22.8.0 to 22.13.0 (LTS)
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  Dockerfile
Labels: dependencies, docker

#3263 docs: document exprlang func return values
  docs/docs/35-references/20-expression-language.md
Labels: area/documentation, backport/release-1.1, backport/release-1.2

#3267 chore(backport release-1.2): bump library/node from 22.8.0 to 22.13.0 (LTS)
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  Dockerfile
Labels: dependencies, docker

#3266 docs: `PromotionTask` reference and more
  docs/docs/35-references/10-promotion-steps.md
  docs/docs/35-references/30-promotion-tasks.md
Labels: area/documentation, backport/release-1.2

#3270 docs: fix rendering of outputs table `http` step
  docs/docs/35-references/10-promotion-steps.md
Labels: area/documentation, backport/release-1.2

#3226 feat: versioned docs dropdown
  docs/docusaurus.config.js
  docs/src/components/VersionDropdown.css
  docs/src/components/VersionDropdown.js
  docs/src/theme/NavbarItem/ComponentTypes.js
Labels: area/documentation, kind/enhancement, priority/high, backport/release-1.0, backport/release-1.1, backport/release-1.2

#3289 chore: skip ci for prs opened against the newdocs branch
  .github/workflows/ci.yaml
Labels: area/documentation, kind/chore, area/devx, area/ci-process, priority/high

#3281 docs: add faqs
  docs/docs/60-new-docs/30-faqs.md
Labels: area/documentation

#3305 docs: make step ordering alphabetical
  docs/docs/60-new-docs/60-user-guide/60-reference-docs/30-promotion-steps/argocd-update.md
  docs/docs/60-new-docs/60-user-guide/60-reference-docs/30-promotion-steps/compose-output.md
  docs/docs/60-new-docs/60-user-guide/60-reference-docs/30-promotion-steps/copy.md
  docs/docs/60-new-docs/60-user-guide/60-reference-docs/30-promotion-steps/delete.md
  docs/docs/60-new-docs/60-user-guide/60-reference-docs/30-promotion-steps/git-clear.md
  docs/docs/60-new-docs/60-user-guide/60-reference-docs/30-promotion-steps/git-clone.md
  docs/docs/60-new-docs/60-user-guide/60-reference-docs/30-promotion-steps/git-commit.md
  docs/docs/60-new-docs/60-user-guide/60-reference-docs/30-promotion-steps/git-open-pr.md
  docs/docs/60-new-docs/60-user-guide/60-reference-docs/30-promotion-steps/git-push.md
  docs/docs/60-new-docs/60-user-guide/60-reference-docs/30-promotion-steps/git-wait-for-pr.md
  docs/docs/60-new-docs/60-user-guide/60-reference-docs/30-promotion-steps/helm-template.md
  docs/docs/60-new-docs/60-user-guide/60-reference-docs/30-promotion-steps/helm-update-chart.md
  docs/docs/60-new-docs/60-user-guide/60-reference-docs/30-promotion-steps/helm-update-image.md
  docs/docs/60-new-docs/60-user-guide/60-reference-docs/30-promotion-steps/http.md
  docs/docs/60-new-docs/60-user-guide/60-reference-docs/30-promotion-steps/json-update.md
  docs/docs/60-new-docs/60-user-guide/60-reference-docs/30-promotion-steps/kustomize-build.md
  docs/docs/60-new-docs/60-user-guide/60-reference-docs/30-promotion-steps/kustomize-set-image.md
  docs/docs/60-new-docs/60-user-guide/60-reference-docs/30-promotion-steps/yaml-update.md
Labels: area/documentation

#3306 docs: basic installation helm
  docs/docs/60-new-docs/40-operator-guide/10-basic-installation.md
Labels: area/documentation, kind/enhancement, priority/high

#3301 docs: add kargo core concepts
  docs/docs/60-new-docs/30-faqs.md
  docs/docs/60-new-docs/60-user-guide/10-core-concepts.md
  docs/docs/60-new-docs/60-user-guide/10-core-concepts/img/kargo-freight.png
  docs/docs/60-new-docs/60-user-guide/10-core-concepts/img/kargo-projects.png
  docs/docs/60-new-docs/60-user-guide/10-core-concepts/img/kargo-stages.png
  docs/docs/60-new-docs/60-user-guide/10-core-concepts/img/kargo-warehouses.png
  docs/docs/60-new-docs/60-user-guide/10-core-concepts/index.md
Labels: area/documentation, kind/enhancement, priority/high

#3300 docs: add Promotion related reference documents
  docs/docs/60-new-docs/60-user-guide/60-reference-docs/15-promotion-templates.md
  docs/docs/60-new-docs/60-user-guide/60-reference-docs/20-expressions.md
  docs/docs/60-new-docs/60-user-guide/60-reference-docs/20-promotion-tasks.md
  docs/docs/60-new-docs/60-user-guide/60-reference-docs/30-promotion-steps/argocd-update.md
  docs/docs/60-new-docs/60-user-guide/60-reference-docs/30-promotion-steps/compose-output.md
  docs/docs/60-new-docs/60-user-guide/60-reference-docs/30-promotion-steps/http.md
  docs/docs/60-new-docs/60-user-guide/60-reference-docs/35-promotion-tasks.md
  docs/docs/60-new-docs/60-user-guide/60-reference-docs/40-expressions.md
Labels: area/documentation, kind/enhancement, priority/high

#3309 docs: document patterns for addressing common use cases
  docs/docs/60-new-docs/30-faqs.md
  docs/docs/60-new-docs/60-user-guide/30-patterns.md
  docs/docs/60-new-docs/60-user-guide/30-patterns/img/a-b-testing.png
  docs/docs/60-new-docs/60-user-guide/30-patterns/img/assembly.png
  docs/docs/60-new-docs/60-user-guide/30-patterns/img/common-case.png
  docs/docs/60-new-docs/60-user-guide/30-patterns/img/config-updater.png
  docs/docs/60-new-docs/60-user-guide/30-patterns/img/control-flow.png
  docs/docs/60-new-docs/60-user-guide/30-patterns/img/fan-out-in.png
  docs/docs/60-new-docs/60-user-guide/30-patterns/img/grouped-services.png
  docs/docs/60-new-docs/60-user-guide/30-patterns/img/image-updater.png
  docs/docs/60-new-docs/60-user-guide/30-patterns/img/multiple-warehouses.png
  docs/docs/60-new-docs/60-user-guide/30-patterns/img/ordered-services.png
  docs/docs/60-new-docs/60-user-guide/30-patterns/img/parallel-pipelines.png
  docs/docs/60-new-docs/60-user-guide/30-patterns/img/pre-pipelines.png
  docs/docs/60-new-docs/60-user-guide/30-patterns/img/tangled.png
  docs/docs/60-new-docs/60-user-guide/30-patterns/index.md
Labels: area/documentation, kind/enhancement, priority/high

#3312 docs: cherry-pick version drop down into newdocs branch
  docs/docusaurus.config.js
  docs/src/components/VersionDropdown.css
  docs/src/components/VersionDropdown.js
  docs/src/theme/NavbarItem/ComponentTypes.js
Labels: area/documentation, kind/enhancement, priority/high

#3313 fix: Indent typo in 15-concepts.md
  docs/docs/15-concepts.md
Labels: kind/bug, area/documentation, priority/normal, backport/release-1.1, backport/release-1.2

#3326 fix(directives): HTTP repo cache `helm-chart-update`
  internal/directives/helm_chart_updater.go
  internal/directives/helm_chart_updater_test.go
Labels: kind/bug, area/controller, backport/release-1.2

#3333 docs: enrich step examples
  docs/docs/60-new-docs/50-user-guide/60-reference-docs/30-promotion-steps/compose-output.md
  docs/docs/60-new-docs/50-user-guide/60-reference-docs/30-promotion-steps/copy.md
  docs/docs/60-new-docs/50-user-guide/60-reference-docs/30-promotion-steps/delete.md
  docs/docs/60-new-docs/50-user-guide/60-reference-docs/30-promotion-steps/git-clear.md
  docs/docs/60-new-docs/50-user-guide/60-reference-docs/30-promotion-steps/git-clone.md
  docs/docs/60-new-docs/50-user-guide/60-reference-docs/30-promotion-steps/git-commit.md
  docs/docs/60-new-docs/50-user-guide/60-reference-docs/30-promotion-steps/git-open-pr.md
  docs/docs/60-new-docs/50-user-guide/60-reference-docs/30-promotion-steps/git-push.md
  docs/docs/60-new-docs/50-user-guide/60-reference-docs/30-promotion-steps/git-wait-for-pr.md
  docs/docs/60-new-docs/50-user-guide/60-reference-docs/30-promotion-steps/helm-template.md
  docs/docs/60-new-docs/50-user-guide/60-reference-docs/30-promotion-steps/helm-update-chart.md
  docs/docs/60-new-docs/50-user-guide/60-reference-docs/30-promotion-steps/http.md
  docs/docs/60-new-docs/50-user-guide/60-reference-docs/30-promotion-steps/json-update.md
  docs/docs/60-new-docs/50-user-guide/60-reference-docs/30-promotion-steps/kustomize-build.md
  docs/docs/60-new-docs/50-user-guide/60-reference-docs/30-promotion-steps/kustomize-set-image.md
  docs/docs/60-new-docs/50-user-guide/60-reference-docs/30-promotion-steps/yaml-update.md
Labels: area/documentation, kind/enhancement, priority/high

#3337 docs: tiny nits in promotion step references
  docs/docs/60-new-docs/50-user-guide/60-reference-docs/30-promotion-steps/git-clone.md
  docs/docs/60-new-docs/50-user-guide/60-reference-docs/30-promotion-steps/git-open-pr.md
  docs/docs/60-new-docs/50-user-guide/60-reference-docs/30-promotion-steps/git-wait-for-pr.md
  docs/docs/60-new-docs/50-user-guide/60-reference-docs/30-promotion-steps/json-update.md
Labels: area/documentation, kind/chore, priority/high

#3334 docs: add intros to some of the larger sections
  docs/docs/60-new-docs/40-operator-guide/40-security/index.md
  docs/docs/60-new-docs/40-operator-guide/index.md
  docs/docs/60-new-docs/50-user-guide/20-how-to-guides/30-managing-user-permissions.md
  docs/docs/60-new-docs/50-user-guide/20-how-to-guides/_category_.json
  docs/docs/60-new-docs/50-user-guide/50-security/10-openid-connect.md
  docs/docs/60-new-docs/50-user-guide/50-security/index.md
  docs/docs/60-new-docs/50-user-guide/index.md
  docs/docs/60-new-docs/60-contributor-guide/index.md
Labels: area/documentation, kind/enhancement, priority/high

#3331 refactor: change generic secret label
  api/service/v1alpha1/service.proto
  api/v1alpha1/labels.go
  internal/api/create_project_secret_v1alpha1.go
  internal/api/delete_project_secret_v1alpha1.go
  internal/api/delete_project_secret_v1alpha1_test.go
  internal/api/get_analysis_template_config_map_v1alpha1.go
  internal/api/get_analysis_template_secret_v1alpha1.go
  internal/api/list_analysis_template_config_maps_v1alpha1.go
  internal/api/list_analysis_template_secrets_v1alpha1.go
  internal/api/list_project_secrets_v1alpha1.go
  internal/api/list_project_secrets_v1alpha1_test.go
  internal/api/update_project_secret_v1alpha1.go
  internal/api/update_project_secret_v1alpha1_test.go
  internal/directives/simple_engine_promote.go
  internal/directives/simple_engine_promote_test.go
  pkg/api/service/v1alpha1/service.pb.go
  pkg/api/service/v1alpha1/svcv1alpha1connect/service.connect.go
  ui/src/gen/service/v1alpha1/service-KargoService_connectquery.ts
  ui/src/gen/service/v1alpha1/service_pb.ts
Labels: kind/refactor, priority/high, area/controller, area/api

#3339 docs: improve Argo CD integration document
  docs/docs/60-new-docs/50-user-guide/20-how-to-guides/25-argo-cd-integration.md
  docs/docs/60-new-docs/50-user-guide/60-reference-docs/30-promotion-steps/argocd-update.md
Labels: area/documentation, backport/release-1.2

#3346 fix(cmd): improve Argo integration checks
  cmd/controlplane/api.go
  cmd/controlplane/controller.go
  cmd/controlplane/utils.go
Labels: kind/bug, area/controller, area/ux, backport/release-1.2

#3348 docs: operator > security > secure configuration
  docs/docs/60-new-docs/40-operator-guide/40-security/10-secure-configuration.md
Labels: area/documentation, kind/enhancement, priority/high, backport/release-1.2

#3352 docs: add operator guide > security > oidc
  docs/docs/60-new-docs/40-operator-guide/40-security/20-openid-connect.md
Labels: area/documentation, kind/enhancement, area/security, priority/high, backport/release-1.2

#3358 docs: fix incorrect callback url in oidc docs
  docs/docs/60-new-docs/40-operator-guide/40-security/20-openid-connect.md
Labels: kind/bug, area/documentation, area/security, priority/high, backport/release-1.2

#3353 docs: add common chart configuration options
  docs/docs/60-new-docs/40-operator-guide/20-advanced-installation/30-common-configurations.md
Labels: area/documentation, kind/enhancement, backport/release-1.2

#3359 fix(ui): tolerate entra id RFC8414 deviation
  ui/src/features/auth/oidc-login.tsx
  ui/src/features/auth/token-renew.tsx
Labels: kind/bug, area/security, area/ui, priority/normal, backport/release-1.2

#3319 chore(cli): fix update command example
  internal/cli/cmd/update/update.go
Labels: kind/bug, priority/normal, area/cli, backport/release-1.2

#3363 fix: fix faulty logic for handling possible double-encoding of github app private key
  internal/credentials/kubernetes/github/app.go
  internal/credentials/kubernetes/github/app_test.go
Labels: kind/bug, priority/high, area/controller, backport/release-1.1, backport/release-1.2

#3356 docs: cli instructions doc
  docs/docs/60-new-docs/20-quickstart/img/cli-installation.png
  docs/docs/60-new-docs/20-quickstart/index.md
  docs/docs/60-new-docs/50-user-guide/20-how-to-guides/05-installing-kargo-cli.md
  docs/docs/60-new-docs/50-user-guide/20-how-to-guides/img/cli-installation.png
Labels: area/documentation, kind/enhancement, priority/high, backport/release-1.2

#3335 docs: Added Advanced installation with Argo CD doc
  docs/docs/60-new-docs/40-operator-guide/20-advanced-installation/20-advanced-with-argocd.md
Labels: area/documentation, kind/enhancement, priority/high, backport/release-1.2

#3383 docs: add instructions for generating password and signing key to the basic install instructions
  docs/docs/60-new-docs/40-operator-guide/10-basic-installation.md
Labels: area/documentation, area/security, kind/refactor, priority/normal, backport/release-1.2

#3173 chore: enforce LF line endings in git
  .gitattributes
Labels: kind/chore, area/devx, priority/normal

#3382 docs: update quickstart to use promo tasks
  docs/docs/60-new-docs/20-quickstart/index.md
Labels: area/documentation, kind/refactor, priority/normal, backport/release-1.2

#3386 docs: add operator-focused and user-focused access control docs
  docs/docs/60-new-docs/40-operator-guide/40-security/20-openid-connect.md
  docs/docs/60-new-docs/40-operator-guide/40-security/30-access-controls.md
  docs/docs/60-new-docs/50-user-guide/20-how-to-guides/30-managing-user-permissions.md
  docs/docs/60-new-docs/50-user-guide/50-security/20-access-controls.md
  docs/docs/60-new-docs/50-user-guide/50-security/20-access-controls/img/edit-role.png
  docs/docs/60-new-docs/50-user-guide/50-security/20-access-controls/img/project.png
  docs/docs/60-new-docs/50-user-guide/50-security/20-access-controls/img/roles.png
  docs/docs/60-new-docs/50-user-guide/50-security/20-access-controls/index.md
Labels: area/documentation, kind/enhancement, priority/high, backport/release-1.2

#3329 docs: working with warehouses
  docs/docs/60-new-docs/50-user-guide/20-how-to-guides/16-working-with-warehouses.md
  docs/docs/60-new-docs/50-user-guide/30-patterns/index.md
Labels: area/documentation, kind/enhancement, priority/high, backport/release-1.2

#3392 fix: vertical view for secrets and filter credentials by label
  internal/api/list_credentials_v1alpha1.go
  ui/src/features/project/credentials/credentials-list.tsx
Labels: kind/bug, area/ui, priority/normal, area/api, backport/release-1.2

#3394 fix(ui): show raw stage manifest
  ui/src/features/stage/stage-details.tsx
Labels: kind/bug, area/ui, priority/normal, backport/release-1.2

#3393 fix(ui): warehouse error in details page instead of tooltip
  ui/src/features/project/pipelines/nodes/repo-node.tsx
  ui/src/features/project/pipelines/warehouse/warehouse-details.tsx
  ui/src/features/project/pipelines/warehouse/warehouse-error.ts
Labels: kind/bug, area/ui, priority/normal

#3399 docs: ui instructions for working with freight
  docs/docs/60-new-docs/50-user-guide/20-how-to-guides/15-working-with-freight.md
  docs/docs/60-new-docs/50-user-guide/20-how-to-guides/img/freight-alias-2.png
  docs/docs/60-new-docs/50-user-guide/20-how-to-guides/img/freight-alias.png
  docs/docs/60-new-docs/50-user-guide/20-how-to-guides/img/freight-approval-2.png
  docs/docs/60-new-docs/50-user-guide/20-how-to-guides/img/freight-approval.png
  docs/docs/60-new-docs/50-user-guide/20-how-to-guides/img/freight-promotion-2.png
  docs/docs/60-new-docs/50-user-guide/20-how-to-guides/img/freight-promotion.png
  docs/docs/60-new-docs/50-user-guide/20-how-to-guides/img/freight-status.png
Labels: area/documentation, kind/enhancement, priority/high, backport/release-1.2

#3408 feat: support Expression Language in Stage verification args
  internal/controller/stages/regular_stages.go
  internal/directives/promotions.go
  internal/expressions/function/functions.go
  internal/expressions/function/functions_test.go
  internal/rollouts/analysis_run_builder.go
  internal/rollouts/analysis_run_builder_test.go
  internal/rollouts/options.go
  internal/rollouts/options_test.go
Labels: kind/enhancement, priority/normal, area/controller

#3407 docs: add verification documentation
  docs/docs/60-new-docs/50-user-guide/20-how-to-guides/14-working-with-stages.md
  docs/docs/60-new-docs/50-user-guide/20-how-to-guides/16-verification.md
  docs/docs/60-new-docs/50-user-guide/20-how-to-guides/20-managing-credentials.md
  docs/docs/60-new-docs/50-user-guide/20-how-to-guides/img/analysisrun.png
  docs/docs/60-new-docs/50-user-guide/60-reference-docs/50-analysis-templates.md
  docs/docs/60-new-docs/80-release-notes/97-v1.2.0.md
Labels: area/documentation, kind/enhancement, priority/high, backport/release-1.2

#3395 docs: promotion instructions to "working with stages"
  docs/docs/60-new-docs/50-user-guide/20-how-to-guides/14-working-with-stages.md
  docs/docs/60-new-docs/50-user-guide/20-how-to-guides/img/promote-freight-to-a-stage-2.png
  docs/docs/60-new-docs/50-user-guide/20-how-to-guides/img/promote-freight-to-a-stage.png
Labels: area/documentation, kind/enhancement, priority/high, backport/release-1.2

#3409 docs: add instructions for interacting w projects
  docs/docs/60-new-docs/50-user-guide/20-how-to-guides/11-working-with-projects.md
  docs/docs/60-new-docs/50-user-guide/20-how-to-guides/14-working-with-stages.md
  docs/docs/60-new-docs/50-user-guide/20-how-to-guides/img/create-project-2.png
  docs/docs/60-new-docs/50-user-guide/20-how-to-guides/img/create-project-3.png
  docs/docs/60-new-docs/50-user-guide/20-how-to-guides/img/create-project.png
  docs/docs/60-new-docs/50-user-guide/20-how-to-guides/img/delete-project-2.png
  docs/docs/60-new-docs/50-user-guide/20-how-to-guides/img/delete-project.png
Labels: area/documentation, kind/enhancement, priority/high, backport/release-1.2

#3416 docs: expr-lang support for verification args
  docs/docs/60-new-docs/50-user-guide/20-how-to-guides/16-verification.md
  docs/docs/60-new-docs/50-user-guide/60-reference-docs/40-expressions.md
Labels: area/documentation, kind/enhancement
