Repository akuity/kargo, pull requests merged in 2025-06, with the labels that each got.

#4216 feat(ui): dump all claims from identity token on user details page
  ui/src/features/auth/jwt-utils.ts
  ui/src/pages/user.tsx
Labels: kind/refactor, area/ui, priority/normal, backport/release-1.5

#4307 fix: missing forward slash
  internal/controller/management/projectconfigs/project_configs.go
Labels: kind/bug, priority/normal, area/external-webhooks

#4257 feat: commits in git clone output
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/git-clone.md
  internal/promotion/runner/builtin/git_cloner.go
  internal/promotion/runner/builtin/git_cloner_test.go
  internal/promotion/runner/builtin/schemas/git-clone-config.json
  pkg/x/promotion/runner/builtin/zz_config_types.go
  ui/src/gen/directives/git-clone-config.json
Labels: kind/enhancement, priority/high, area/controller

#4290 feat(ui): more freight details in promotion space
  ui/src/features/project/pipelines/promotion/freight-details.tsx
Labels: area/ui, priority/normal, area/usability, backport/release-1.5

#4291 feat(ui): freight history improvements
  ui/src/features/project/pipelines/freight/short-version-utils.ts
  ui/src/features/project/pipelines/promotion/freight-details.tsx
  ui/src/features/stage/stage-details.tsx
  ui/src/features/stage/tabs/freight-history/freight-history.tsx
  ui/src/features/stage/tabs/freight-history/use-promotions-by-freight-collection.ts
Labels: kind/enhancement, area/ui, priority/normal

#4317 feat(ui): quick promote from upstream
  ui/src/features/project/pipelines/nodes/stage-node.tsx
  ui/src/features/project/pipelines/nodes/use-get-upstream-freight.ts
Labels: kind/enhancement, area/ui, priority/normal

#4336 fix(ui): convoluted edges for large graphs
  ui/src/features/project/pipelines/graph/use-pipeline-graph.ts
Labels: kind/bug, area/ui, priority/normal, area/usability, backport/release-1.5

#4181 refactor(runner): promotion engine improvements
  internal/indexer/indexer.go
  internal/promotion/promotion.go
  internal/promotion/promotion_test.go
  internal/promotion/runner/builtin/init.go
  internal/promotion/runner/builtin/output_composer.go
  internal/promotion/simple_engine.go
  internal/promotion/simple_engine_test.go
  pkg/promotion/promotion.go
Labels: kind/refactor, priority/normal, area/controller

#4193 feat: support filtering Git commits and tags using expressions
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/warehouse_types.go
  charts/kargo/resources/crds/kargo.akuity.io_warehouses.yaml
  docs/docs/50-user-guide/20-how-to-guides/30-working-with-warehouses.md
  internal/controller/git/client_opts.go
  internal/controller/git/work_tree.go
  internal/controller/warehouses/git.go
  internal/controller/warehouses/git_test.go
  ui/src/gen/api/v1alpha1/generated_pb.ts
  ui/src/gen/schema/warehouses.kargo.akuity.io_v1alpha1.json
Labels: kind/enhancement, priority/normal, area/controller

#4342 docs: add tip about expr-lang playground
  docs/docs/50-user-guide/60-reference-docs/40-expressions.md
Labels: area/documentation, kind/chore, priority/normal, backport/release-1.5

#3927 feat(runner): add `untar` Promotion step
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/untar.md
  internal/promotion/runner/builtin/init.go
  internal/promotion/runner/builtin/schemas/untar-config.json
  internal/promotion/runner/builtin/tar_extractor.go
  internal/promotion/runner/builtin/tar_extractor_test.go
  pkg/x/promotion/runner/builtin/zz_config_types.go
  ui/src/gen/directives/untar-config.json
Labels: kind/enhancement, priority/normal, area/controller

#4332 feat: add gitlab webhook receiver support
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/project_config_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/kargo/resources/crds/kargo.akuity.io_clusterconfigs.yaml
  charts/kargo/resources/crds/kargo.akuity.io_projectconfigs.yaml
  charts/kargo/resources/crds/kargo.akuity.io_projects.yaml
  internal/webhook/external/gitlab.go
  internal/webhook/external/gitlab_test.go
  ui/src/gen/api/v1alpha1/generated_pb.ts
  ui/src/gen/schema/clusterconfigs.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/projectconfigs.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/projects.kargo.akuity.io_v1alpha1.json
Labels: priority/normal, area/external-webhooks

#4353 feat: add ghcr.io package event support to github webhook receiver
  internal/webhook/external/github.go
  internal/webhook/external/github_test.go
Labels: kind/enhancement, priority/high, area/external-webhooks

#4377 fix: Updates label selector in deployment
  charts/kargo/templates/management-controller/deployment.yaml
Labels: kind/refactor, priority/normal, area/charts

#4365 feat: support fallback to local cluster when searching for cred secrets
  cmd/controlplane/controller.go
  internal/credentials/kubernetes/database.go
  internal/credentials/kubernetes/database_test.go
Labels: kind/enhancement, priority/high, area/controller

#4380 feat(ui): Add subpage extension hook
  ui/src/app.tsx
  ui/src/config/paths.ts
  ui/src/extensions/extensions-context.ts
  ui/src/extensions/pages/app-extensions.tsx
  ui/src/extensions/types.ts
  ui/src/features/common/layout/main-layout.tsx
Labels: kind/enhancement, area/ui, priority/normal

#4392 feat: set `ObservedGeneration` for ClusterConfig and PromotionConfig
  api/v1alpha1/cluster_config_types.go
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/project_config_types.go
  charts/kargo/resources/crds/kargo.akuity.io_clusterconfigs.yaml
  charts/kargo/resources/crds/kargo.akuity.io_projectconfigs.yaml
  internal/controller/management/clusterconfigs/cluster_configs.go
  internal/controller/management/projectconfigs/project_configs.go
  ui/src/gen/api/v1alpha1/generated_pb.ts
  ui/src/gen/schema/clusterconfigs.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/projectconfigs.kargo.akuity.io_v1alpha1.json
Labels: kind/enhancement, priority/normal, area/controller

#4390 fix: sharded kargo setup analysisRun indexer
  internal/controller/stages/regular_stages.go
Labels: kind/bug, priority/high, area/controller, backport/release-1.5

#4398 refactor: DRY up webhook receivers
  internal/webhook/external/bitbucket.go
  internal/webhook/external/bitbucket_test.go
  internal/webhook/external/dockerhub.go
  internal/webhook/external/dockerhub_test.go
  internal/webhook/external/github.go
  internal/webhook/external/github_test.go
  internal/webhook/external/gitlab.go
  internal/webhook/external/gitlab_test.go
  internal/webhook/external/quay.go
  internal/webhook/external/quay_test.go
  internal/webhook/external/receiver.go
  internal/webhook/external/refresh.go
  internal/webhook/external/refresh_test.go
  internal/webhook/external/router.go
Labels: kind/refactor, priority/high, area/external-webhooks

#4412 fix(ui): image annotations in assembled Freight
  ui/src/features/assemble-freight/assemble-freight.tsx
Labels: kind/bug, area/ui, priority/high, backport/release-1.5

#4381 docs: webhook receivers
  docs/docs/40-operator-guide/20-advanced-installation/30-common-configurations.md
  docs/docs/40-operator-guide/35-cluster-configuration.md
  docs/docs/50-user-guide/20-how-to-guides/30-working-with-warehouses.md
  docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/_category_.json
  docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/bitbucket.md
  docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/dockerhub.md
  docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/generic.md
  docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/ghcr.md
  docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/github.md
  docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/gitlab.md
  docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/index.md
  docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/quay.md
Labels: area/documentation, kind/enhancement, priority/high

#4404 feat(ui): refresh stage in promotion modal
  ui/src/features/project/pipelines/promotion/get-promotion-stage.ts
  ui/src/features/project/pipelines/promotion/promotion.tsx
Labels: kind/enhancement, area/ui, priority/normal

#4415 fix(chart): add clusterconfig permissions to API
  charts/kargo/templates/api/cluster-roles.yaml
Labels: kind/bug, priority/high, area/charts, area/api-server

#4423 feat(ui): ClusterConfig
  ui/src/features/settings/cluster-config/cluster-config-yaml-example.ts
  ui/src/features/settings/cluster-config/cluster-config.tsx
  ui/src/features/settings/cluster-config/transport.ts
  ui/src/pages/settings.tsx
  ui/src/utils/decode-raw-data.ts
Labels: kind/enhancement, area/ui, priority/high

#4411 docs: github webhook receivers
  docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/github/img/apps/ping-response.png
  docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/github/img/apps/register.png
  docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/github/img/apps/subscribe.png
  docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/github/img/webhooks/add-webhook-form.png
  docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/github/img/webhooks/ping-response.png
  docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/github/img/webhooks/recent-deliveries.png
  docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/github/img/webhooks/settings.png
  docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/github/img/webhooks/webhooks.png
  docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/github/index.md
Labels: area/documentation, kind/enhancement, priority/high, area/external-webhooks

#4424 fix(chart): add project patch permissions to management SA
  charts/kargo/templates/management-controller/cluster-roles.yaml
Labels: kind/bug, priority/high, area/charts

#4429 docs: remove some temporal references
  docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/github/index.md
Labels: area/documentation, kind/chore

#4436 fix(ui): stage colors are not present on freights
  ui/src/features/stage/utils/index.ts
Labels: kind/bug, area/ui, priority/normal, backport/release-1.5

#4426 feat(ui): refresh ProjectConfig
  ui/src/features/project/settings/views/project-config/project-config.tsx
  ui/src/features/project/settings/views/project-config/refresh.tsx
Labels: kind/enhancement, area/ui, priority/high

#4422 feat: make image/oci webhook receivers also work for charts
  internal/helm/helm.go
  internal/helm/helm_test.go
  internal/webhook/external/dockerhub.go
  internal/webhook/external/dockerhub_test.go
  internal/webhook/external/github.go
  internal/webhook/external/github_test.go
  internal/webhook/external/quay.go
  internal/webhook/external/quay_test.go
  internal/webhook/external/receiver.go
  internal/webhook/external/refresh.go
Labels: kind/enhancement, priority/high, area/external-webhooks, backport/release-1.6

#4417 docs: gitlab webhook receivers
  docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/bitbucket/index.md
  docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/dockerhub/index.md
  docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/github/index.md
  docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/gitlab.md
  docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/gitlab/img/add-webhook-form.png
  docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/gitlab/img/settings.png
  docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/gitlab/img/test-button.png
  docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/gitlab/img/webhooks.png
  docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/gitlab/index.md
  internal/webhook/external/gitlab.go
Labels: area/documentation, kind/enhancement, priority/high, area/external-webhooks

#4451 chore: build w/ `-trimpath` and `-ldflags -w`
  Dockerfile
Labels: kind/chore, area/ci-process, area/release-process, priority/normal, go, backport/release-1.6

#4463 chart: fix bug in kargo.baseURL helper
  charts/kargo/templates/_helpers.tpl
Labels: kind/bug, priority/urgent, area/charts, backport/release-1.6

#4371 feat(ui): stage list view
  ui/src/features/project/pipelines/freight/freight-card.tsx
  ui/src/features/project/pipelines/freight/source-catalogue-utils.ts
  ui/src/features/project/pipelines/graph-filters.tsx
  ui/src/features/project/pipelines/graph/use-events-watcher.ts
  ui/src/features/project/pipelines/list/applied-filters.tsx
  ui/src/features/project/pipelines/list/columns/action-column.tsx
  ui/src/features/project/pipelines/list/columns/health-column.tsx
  ui/src/features/project/pipelines/list/columns/last-promotion-column.tsx
  ui/src/features/project/pipelines/list/columns/phase-column.tsx
  ui/src/features/project/pipelines/list/columns/stage-column.tsx
  ui/src/features/project/pipelines/list/columns/version-column.tsx
  ui/src/features/project/pipelines/list/context/filter-context.ts
  ui/src/features/project/pipelines/list/list-view.tsx
  ui/src/features/project/pipelines/list/use-applied-filters.ts
  ui/src/features/project/pipelines/nodes/stage-meta-utils.ts
  ui/src/features/project/pipelines/nodes/stage-node.tsx
  ui/src/features/project/pipelines/pipelines.tsx
Labels: kind/enhancement, area/ui, priority/normal, backport/release-1.6

#4472 fix(chart): add clusterconfig permissions to clusterroles
  charts/kargo/templates/users/cluster-roles.yaml
Labels: kind/bug, area/security, priority/high, area/charts, backport/release-1.6

#4245 feat(runner): allow building dependencies before Helm template
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/helm-template.md
  go.mod
  go.sum
  internal/helm/dependency.go
  internal/helm/dependency_manager.go
  internal/helm/dependency_manager_test.go
  internal/helm/dependency_test.go
  internal/helm/fake_registry_test.go
  internal/helm/registry.go
  internal/helm/registry_test.go
  internal/helm/testdata/charts/demo-0.1.0.tgz
  internal/helm/testdata/charts/examplechart-0.1.0.tgz
  internal/io/fs/copy.go
  internal/io/fs/copy_test.go
  internal/io/fs/error.go
  internal/io/fs/error_test.go
  internal/io/fs/path.go
  internal/io/fs/path_test.go
  internal/io/fs/validate.go
  internal/io/fs/validate_test.go
  internal/promotion/runner/builtin/file_copier.go
  internal/promotion/runner/builtin/file_copier_test.go
  internal/promotion/runner/builtin/file_deleter.go
  internal/promotion/runner/builtin/helm_chart_updater.go
  internal/promotion/runner/builtin/helm_chart_updater_test.go
  internal/promotion/runner/builtin/helm_template_runner.go
  internal/promotion/runner/builtin/helm_template_runner_test.go
  internal/promotion/runner/builtin/init.go
  internal/promotion/runner/builtin/kustomize_builder.go
  internal/promotion/runner/builtin/kustomize_builder_test.go
  internal/promotion/runner/builtin/schemas/helm-template-config.json
  internal/yaml/update.go
  pkg/x/promotion/runner/builtin/zz_config_types.go
  ui/src/gen/directives/helm-template-config.json
Labels: kind/enhancement, priority/normal, area/controller, backport/release-1.6

#4477 docs: rename jfrog webhook receiver as artifactory webhook receiver
  docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/artifactory.md
  docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/jfrog.md
Labels: area/documentation, kind/refactor, priority/high, backport/release-1.6

#4469 feat(ui): Add Promotion Tab extension hook
  ui/src/extensions/extensions-context.ts
  ui/src/extensions/types.ts
  ui/src/features/project/pipelines/promotion/freight-details.tsx
  ui/src/features/project/pipelines/promotion/promote.tsx
Labels: kind/enhancement, area/ui, priority/normal, backport/release-1.6

#4475 chart: add kargo-user sa/clusterrole/clusterrolebinding
  charts/kargo/README.md
  charts/kargo/templates/users/cluster-role-bindings.yaml
  charts/kargo/templates/users/cluster-roles.yaml
  charts/kargo/templates/users/service-accounts.yaml
  charts/kargo/values.yaml
Labels: kind/enhancement, area/security, priority/high, area/charts, backport/release-1.6

#4484 fix(ui): object was being rendered directly on the User pagen User page
  ui/src/pages/user.tsx
Labels: kind/bug, area/ui, priority/normal, backport/release-1.6

#4499 fix(chart): grant mgmt controller permission to delete namespaces
  charts/kargo/templates/management-controller/cluster-roles.yaml
Labels: kind/bug, area/security, priority/urgent, area/charts, backport/release-1.6

#4500 fix: fix reference to incorrect config field in dockerhub receiver
  internal/webhook/external/dockerhub.go
Labels: kind/bug, priority/urgent, area/external-webhooks, area/management-controller, backport/release-1.6

#4502 docs: proper webhook event type for GitHub
  docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/github/index.md
Labels: kind/bug, area/documentation, priority/high, backport/release-1.6

#4492 chore(helm): drop dependency on ORAS v1
  go.mod
  go.sum
  internal/helm/helm.go
Labels: kind/chore, priority/normal, area/controller

#4515 feat(ui): Enable freight alias by default
  ui/src/features/project/pipelines/pipelines.tsx
Labels: kind/enhancement, area/ui, priority/normal, backport/release-1.6

#4524 fix: replace release trigger from created to published
  .github/workflows/release.yaml
Labels: kind/bug, area/release-process, priority/low
