Repository akuity/kargo, pull requests merged in 2025-07, with the labels that each got.

#2916 feat: Close security gaps OIDC implementation to make it work with Okta
  internal/server/option/auth.go
  ui/src/features/auth/oidc-login.tsx
Labels: kind/enhancement, area/security, area/ui, priority/low, area/cli, kind/proposal

#4563 fix(controller): wait for cache syncs
  cmd/controlplane/controller.go
Labels: kind/bug, priority/normal, area/controller, backport/release-1.6

#4544 fix(runner)!: improve error handling `http` step
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/http.md
  internal/promotion/runner/builtin/http_requester.go
  internal/promotion/runner/builtin/http_requester_test.go
Labels: kind/bug, priority/high, area/controller

#4571 docs: rename label to 'Pro'
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/jira.md
  docs/docusaurus.config.js
  docs/src/css/custom.css
  docs/src/theme/DocSidebarItem/index.js
  docs/tags.js
Labels: area/documentation, kind/refactor, priority/normal, backport/release-1.6

#4569 chore: deal with deprecation of `sigs.k8s.io/yaml/goyaml.v3`
  internal/promotion/promotion.go
  internal/promotion/runner/builtin/kustomize_image_setter.go
  internal/promotion/runner/builtin/kustomize_image_setter_test.go
  internal/yaml/decode.go
  internal/yaml/decode_test.go
  internal/yaml/update.go
  internal/yaml/update_test.go
  internal/yaml/yaml.go
  internal/yaml/yaml_test.go
Labels: kind/chore, priority/normal, dependencies, go

#4589 feat(ui): gitea webhook receiver
  ui/src/features/project/settings/views/project-config/webhook/webhook-receivers.tsx
Labels: area/ui, priority/high, area/external-webhooks

#4588 feat(ui): artifactory whr
  ui/src/features/project/settings/views/project-config/webhook/webhook-receivers.tsx
Labels: kind/enhancement, area/ui, priority/high, area/external-webhooks

#4587 feat(ui): azure webhook receiver
  ui/src/features/project/settings/views/project-config/webhook/webhook-receivers.tsx
Labels: kind/enhancement, area/ui, priority/high, area/external-webhooks

#4599 fix(webhook): prevent panic on Freight validation
  internal/webhook/kubernetes/freight/webhook.go
  internal/webhook/kubernetes/freight/webhook_test.go
Labels: kind/bug, priority/normal, area/kubernetes-webhooks, backport/release-1.6

#4531 feat: add StartedAt field to Promotion status
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/promotion_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/kargo/resources/crds/kargo.akuity.io_promotions.yaml
  charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
  internal/controller/promotions/promotions.go
  ui/src/gen/api/v1alpha1/generated_pb.ts
  ui/src/gen/schema/promotions.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
Labels: kind/enhancement, priority/normal, area/controller, area/crds

#4533 feat(mgmt-controller): rely on GC of NS through owner ref and finalizer
  charts/kargo/templates/management-controller/cluster-roles.yaml
  internal/controller/management/projects/projects.go
  internal/controller/management/projects/projects_test.go
Labels: area/security, priority/normal, area/charts, area/management-controller

#4522 feat: azure webhook receiver
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/project_config_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/kargo/resources/crds/kargo.akuity.io_clusterconfigs.yaml
  charts/kargo/resources/crds/kargo.akuity.io_projectconfigs.yaml
  charts/kargo/resources/crds/kargo.akuity.io_projects.yaml
  internal/webhook/external/azure.go
  internal/webhook/external/azure_test.go
  internal/webhook/external/quay_test.go
  internal/webhook/kubernetes/external/validation.go
  ui/src/features/project/settings/views/project-config/webhook/webhook-receivers.tsx
  ui/src/gen/api/v1alpha1/generated_pb.ts
  ui/src/gen/schema/clusterconfigs.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/projectconfigs.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/projects.kargo.akuity.io_v1alpha1.json
Labels: kind/enhancement, priority/high, area/external-webhooks

#4638 feat(ui): Add Stage data to the promote tab ext
  ui/src/extensions/types.ts
  ui/src/features/project/pipelines/promotion/promote.tsx
Labels: kind/enhancement, area/ui, priority/normal

#4663 chore: Bump grpc-health-probe to v0.4.39
  Dockerfile
Labels: dependencies, docker, backport/release-1.6

#4671 refactor(controller): comprehensive refactoring of aritfact selection logic for broader reuse outside discovery
  internal/controller/git/commit/base_selector.go
  internal/controller/git/commit/base_selector_test.go
  internal/controller/git/commit/common.go
  internal/controller/git/commit/common_test.go
  internal/controller/git/commit/lexical_selector.go
  internal/controller/git/commit/lexical_selector_test.go
  internal/controller/git/commit/newest_from_branch_selector.go
  internal/controller/git/commit/newest_from_branch_selector_test.go
  internal/controller/git/commit/newest_tag_selector.go
  internal/controller/git/commit/newest_tag_selector_test.go
  internal/controller/git/commit/registry.go
  internal/controller/git/commit/registry_test.go
  internal/controller/git/commit/selector.go
  internal/controller/git/commit/semver_selector.go
  internal/controller/git/commit/semver_selector_test.go
  internal/controller/git/commit/tag_based_selector.go
  internal/controller/git/commit/tag_based_selector_test.go
  internal/controller/git/mock_repo.go
  internal/controller/warehouses/git.go
  internal/controller/warehouses/git_test.go
  internal/controller/warehouses/helm.go
  internal/controller/warehouses/helm_test.go
  internal/controller/warehouses/images.go
  internal/controller/warehouses/images_test.go
  internal/controller/warehouses/warehouses.go
  internal/controller/warehouses/warehouses_test.go
  internal/helm/chart/base_selector.go
  internal/helm/chart/base_selector_test.go
  internal/helm/chart/http_selector.go
  internal/helm/chart/http_selector_test.go
  internal/helm/chart/oci_selector.go
  internal/helm/chart/oci_selector_test.go
  internal/helm/chart/selector.go
  internal/helm/helm.go
  internal/helm/helm_test.go
  internal/image/base_selector.go
  internal/image/base_selector_test.go
  internal/image/digest_selector.go
  internal/image/digest_selector_test.go
  internal/image/image.go
  internal/image/image_test.go
  internal/image/lexical_selector.go
  internal/image/lexical_selector_test.go
  internal/image/newest_build_selector.go
  internal/image/newest_build_selector_test.go
  internal/image/repository_client.go
  internal/image/repository_client_test.go
  internal/image/selector.go
  internal/image/selector_docker_hub_test.go
  internal/image/selector_ghcr_test.go
  internal/image/selector_registry.go
  internal/image/selector_registry_test.go
  internal/image/selector_test.go
  internal/image/semver_selector.go
  internal/image/semver_selector_test.go
  internal/image/tag_based_selector.go
  internal/image/tag_based_selector_test.go
Labels: kind/chore, kind/refactor, priority/high, area/controller

#4498 feat: artifactory(jfrog) webhook receiver
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/project_config_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/kargo/resources/crds/kargo.akuity.io_clusterconfigs.yaml
  charts/kargo/resources/crds/kargo.akuity.io_projectconfigs.yaml
  charts/kargo/resources/crds/kargo.akuity.io_projects.yaml
  internal/webhook/external/artifactory.go
  internal/webhook/external/artifactory_test.go
  internal/webhook/external/common_test.go
  internal/webhook/kubernetes/external/validation.go
  ui/src/features/project/settings/views/project-config/webhook/webhook-receivers.tsx
  ui/src/gen/api/v1alpha1/generated_pb.ts
  ui/src/gen/schema/clusterconfigs.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/projectconfigs.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/projects.kargo.akuity.io_v1alpha1.json
Labels: kind/enhancement, priority/high, area/external-webhooks

#4672 feat(ui): add a new Tabs component to sync tab state with URL query param
  ui/src/features/common/tabs-with-url.tsx
  ui/src/features/project/pipelines/promotion/freight-details.tsx
Labels: kind/enhancement, area/ui, priority/normal

#4541 refactor: deprecate `SemverConstraint` field and introduce generic `constraint` field
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/warehouse_types.go
  charts/kargo/resources/crds/kargo.akuity.io_warehouses.yaml
  docs/docs/50-user-guide/20-how-to-guides/30-working-with-warehouses.md
  internal/controller/warehouses/helm.go
  internal/controller/warehouses/images.go
  internal/image/digest_selector.go
  internal/image/semver_selector.go
  internal/webhook/kubernetes/warehouse/webhook.go
  internal/webhook/kubernetes/warehouse/webhook_test.go
  ui/src/gen/api/v1alpha1/generated_pb.ts
  ui/src/gen/schema/warehouses.kargo.akuity.io_v1alpha1.json
Labels: kind/bug, kind/chore, kind/refactor, priority/high, area/controller

#4683 feat(ui): accurate auto promotion label in stages
  ui/src/features/project/pipelines/pipelines.tsx
  ui/src/features/project/pipelines/use-stage-auto-promotion-map.ts
Labels: kind/bug, area/ui, priority/normal

#4520 fix: application recorded in promotion event's annotation may be incorrect
  internal/event/promotion.go
  internal/event/promotion_test.go
Labels: kind/bug, priority/high, needs/area

#4675 feat(ui): dynamic image history view
  ui/src/features/project/pipelines/image-history/get-stages.ts
  ui/src/features/project/pipelines/image-history/header-button.tsx
  ui/src/features/project/pipelines/image-history/images.tsx
  ui/src/features/project/pipelines/image-history/process-tag-map.ts
  ui/src/features/project/pipelines/image-history/sort-tags.ts
  ui/src/features/project/pipelines/image-history/stage-box.tsx
  ui/src/features/project/pipelines/image-history/types.ts
  ui/src/features/project/pipelines/image-history/use-promotion-history.ts
  ui/src/features/project/pipelines/images.tsx
  ui/src/features/project/pipelines/pipelines.tsx
Labels: kind/enhancement, area/ui, priority/normal

#4461 docs: gitea webhook receiver
  docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/gitea/img/created.png
  docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/gitea/img/dropdown.png
  docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/gitea/img/form.png
  docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/gitea/img/recent-deliveries.png
  docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/gitea/img/response.png
  docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/gitea/img/settings.png
  docs/docs/50-user-guide/60-reference-docs/80-webhook-receivers/gitea/index.md
Labels: area/documentation, kind/enhancement, priority/high, area/external-webhooks

#4682 fix(chart): use .Values.image.pullSecrets in garbage collector CronJob
  charts/kargo/templates/garbage-collector/cron-job.yaml
Labels: kind/enhancement, priority/normal, area/charts

#4704 fix: take greater care when examining media types
  internal/webhook/external/azure.go
  internal/webhook/external/azure_test.go
  internal/webhook/external/dockerhub.go
  internal/webhook/external/dockerhub_test.go
  internal/webhook/external/github.go
  internal/webhook/external/github_test.go
  internal/webhook/external/media_types.go
  internal/webhook/external/media_types_test.go
Labels: kind/bug, priority/high, area/external-webhooks

#4715 chore(manual backport release-1.6): fix: take greater care when examining media types (#4704)
  internal/webhook/external/dockerhub.go
  internal/webhook/external/dockerhub_test.go
  internal/webhook/external/github.go
  internal/webhook/external/github_test.go
  internal/webhook/external/media_types.go
  internal/webhook/external/media_types_test.go
Labels: kind/bug, priority/normal, area/external-webhooks

#4710 chore(api)!: remove deprecated ProjectSpec
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/project_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/kargo/resources/crds/kargo.akuity.io_projects.yaml
  docs/docs/80-release-notes/100-deprecations.md
  internal/api/annotations.go
  internal/controller/management/projects/projects.go
  internal/controller/management/projects/projects_test.go
  internal/webhook/kubernetes/project/webhook.go
  internal/webhook/kubernetes/project/webhook_test.go
  ui/src/features/project/pipelines/pipelines.tsx
  ui/src/features/project/pipelines/use-stage-auto-promotion-map.ts
  ui/src/gen/api/v1alpha1/generated_pb.ts
  ui/src/gen/schema/projects.kargo.akuity.io_v1alpha1.json
Labels: kind/chore, priority/normal, area/kubernetes-webhooks, area/crds, area/management-controller

#4700 feat(ui): warehouse details view improvement
  ui/src/features/assemble-freight/artifact-menu-item.tsx
  ui/src/features/assemble-freight/commit-table.tsx
  ui/src/features/project/pipelines/warehouse/repo-subscriptions.tsx
Labels: kind/bug, area/ui, priority/normal

#4716 feat(ui): pipeline filters in URL query
  ui/src/features/project/pipelines/pipelines.tsx
  ui/src/features/project/pipelines/url-params/use-freight-timeline-controller-store.ts
Labels: kind/enhancement, area/ui, priority/normal

#4687 feat: support client id when authenticating to github as a github app
  docs/docs/50-user-guide/50-security/30-managing-credentials.md
  internal/credentials/kubernetes/github/app.go
  internal/credentials/kubernetes/github/app_test.go
  internal/credentials/kubernetes/github/app_token_source.go
  internal/credentials/kubernetes/github/app_token_source_test.go
Labels: area/documentation, kind/enhancement, kind/refactor, priority/normal, area/controller

#4708 feat(controller): allow a controller for a specific shard to also be the default controller
  charts/kargo/README.md
  charts/kargo/templates/controller/configmap.yaml
  charts/kargo/values.yaml
  cmd/controlplane/controller.go
  internal/controller/labels.go
  internal/controller/labels_test.go
  internal/controller/predicates.go
  internal/controller/predicates_test.go
  internal/controller/promotions/promotions.go
  internal/controller/stages/control_flow_stages.go
  internal/controller/stages/event_handlers_test.go
  internal/controller/stages/regular_stages.go
  internal/controller/warehouses/warehouses.go
  internal/indexer/indexer.go
  internal/indexer/indexer_test.go
Labels: kind/enhancement, priority/high, area/controller, area/charts

#4721 chore(backport release-1.6): fix(runner): JSON response `http` without header
  internal/promotion/runner/builtin/http_requester.go
  internal/promotion/runner/builtin/http_requester_test.go
Labels: kind/bug, kind/enhancement, priority/high, area/controller

#4725 fix(ui): managedFields visible even if hide managed fields is enabled
  ui/src/features/common/code-editor/yaml-editor-lazy.tsx
Labels: kind/bug, area/ui, priority/normal

#4677 fix: check shard before warehouse + stage reconciles
  internal/controller/predicates.go
  internal/controller/predicates_test.go
  internal/controller/stages/control_flow_stages.go
  internal/controller/stages/control_flow_stages_test.go
  internal/controller/stages/regular_stages.go
  internal/controller/stages/regular_stages_test.go
  internal/controller/warehouses/warehouses.go
  internal/controller/warehouses/warehouses_test.go
Labels: kind/bug, priority/normal, area/controller

#4728 chore: address nits `http-download` step
  internal/promotion/runner/builtin/http_downloader.go
  internal/promotion/runner/builtin/http_downloader_test.go
Labels: kind/chore, kind/refactor, priority/normal, area/controller

#4701 refactor: terminal error on step configuration validation
  internal/promotion/runner/builtin/argocd_updater.go
  internal/promotion/runner/builtin/argocd_updater_test.go
  internal/promotion/runner/builtin/file_copier.go
  internal/promotion/runner/builtin/file_copier_test.go
  internal/promotion/runner/builtin/file_deleter.go
  internal/promotion/runner/builtin/file_deleter_test.go
  internal/promotion/runner/builtin/git_cloner.go
  internal/promotion/runner/builtin/git_cloner_test.go
  internal/promotion/runner/builtin/git_commiter.go
  internal/promotion/runner/builtin/git_commiter_test.go
  internal/promotion/runner/builtin/git_pr_opener.go
  internal/promotion/runner/builtin/git_pr_opener_test.go
  internal/promotion/runner/builtin/git_pr_waiter.go
  internal/promotion/runner/builtin/git_pr_waiter_test.go
  internal/promotion/runner/builtin/git_pusher.go
  internal/promotion/runner/builtin/git_pusher_test.go
  internal/promotion/runner/builtin/git_tree_clearer.go
  internal/promotion/runner/builtin/git_tree_clearer_test.go
  internal/promotion/runner/builtin/helm_chart_updater.go
  internal/promotion/runner/builtin/helm_chart_updater_test.go
  internal/promotion/runner/builtin/helm_template_runner.go
  internal/promotion/runner/builtin/helm_template_runner_test.go
  internal/promotion/runner/builtin/http_downloader.go
  internal/promotion/runner/builtin/http_downloader_test.go
  internal/promotion/runner/builtin/http_requester.go
  internal/promotion/runner/builtin/http_requester_test.go
  internal/promotion/runner/builtin/json_parser.go
  internal/promotion/runner/builtin/json_parser_test.go
  internal/promotion/runner/builtin/json_updater.go
  internal/promotion/runner/builtin/json_updater_test.go
  internal/promotion/runner/builtin/kustomize_builder.go
  internal/promotion/runner/builtin/kustomize_builder_test.go
  internal/promotion/runner/builtin/kustomize_image_setter.go
  internal/promotion/runner/builtin/kustomize_image_setter_test.go
  internal/promotion/runner/builtin/output_composer.go
  internal/promotion/runner/builtin/tar_extractor.go
  internal/promotion/runner/builtin/tar_extractor_test.go
  internal/promotion/runner/builtin/validation.go
  internal/promotion/runner/builtin/validation_test.go
  internal/promotion/runner/builtin/yaml_parser.go
  internal/promotion/runner/builtin/yaml_parser_test.go
  internal/promotion/runner/builtin/yaml_updater.go
  internal/promotion/runner/builtin/yaml_updater_test.go
Labels: kind/refactor, priority/normal, area/controller
