Repository akuity/kargo, pull requests merged in 2025-08, with the labels that each got.

#4736 fix(ui): infinite render in yaml view
  ui/src/features/common/code-editor/yaml-editor-lazy.tsx
Labels: kind/bug, area/ui, priority/high

#4731 fix(ui): assemble multiple Helm chart from same repo
  ui/src/features/assemble-freight/artifact-menu-item.tsx
  ui/src/features/assemble-freight/assemble-freight.tsx
  ui/src/features/assemble-freight/unique-subscription-key.ts
Labels: kind/bug, area/ui, priority/normal, backport/release-1.6

#4740 fix(api/webhook): move part of Stage step validation to webhook
  api/v1alpha1/generated.proto
  api/v1alpha1/stage_types.go
  charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
  internal/webhook/kubernetes/stage/webhook.go
  internal/webhook/kubernetes/stage/webhook_test.go
  ui/src/gen/api/v1alpha1/generated_pb.ts
  ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
Labels: kind/bug, priority/high, area/kubernetes-webhooks, area/crds, backport/release-1.6

#4679 feat: add `oci-download` step
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/oci-download.md
  internal/io/io.go
  internal/io/io_test.go
  internal/promotion/runner/builtin/init.go
  internal/promotion/runner/builtin/oci_downloader.go
  internal/promotion/runner/builtin/oci_downloader_test.go
  internal/promotion/runner/builtin/schemas/oci-download-config.json
  pkg/x/promotion/runner/builtin/zz_config_types.go
  ui/src/gen/directives/oci-download-config.json
Labels: kind/enhancement, priority/normal, area/controller

#4734 enable project create/delete "self-service"
  Tiltfile
  charts/kargo/README.md
  charts/kargo/templates/api/configmap.yaml
  charts/kargo/templates/management-controller/cluster-roles.yaml
  charts/kargo/templates/users/cluster-role-bindings.yaml
  charts/kargo/templates/users/cluster-roles.yaml
  charts/kargo/templates/users/service-accounts.yaml
  charts/kargo/values.yaml
  internal/controller/management/projects/projects.go
  internal/controller/management/projects/projects_test.go
  internal/kubernetes/naming.go
  internal/server/common.go
  internal/server/create_or_update_resource_v1alpha1.go
  internal/server/create_resource_v1alpha1.go
  internal/server/kubernetes/client.go
  internal/strings/strings.go
  internal/strings/strings_test.go
Labels: kind/enhancement, area/security, priority/high, area/controller, area/charts, area/api-server

#4743 refactor: misc. webhook receiver test cleanup
  internal/webhook/external/artifactory_test.go
  internal/webhook/external/azure_test.go
  internal/webhook/external/bitbucket_test.go
  internal/webhook/external/dockerhub_test.go
  internal/webhook/external/gitea.go
  internal/webhook/external/gitea_test.go
  internal/webhook/external/github.go
  internal/webhook/external/github_test.go
  internal/webhook/external/gitlab.go
  internal/webhook/external/gitlab_test.go
  internal/webhook/external/quay_test.go
  internal/webhook/external/refresh_test.go
Labels: kind/chore, kind/refactor, priority/high, area/external-webhooks

#4742 fix: shorten Stage label value exceeding max length
  api/v1alpha1/annotations.go
  internal/controller/stages/control_flow_stages.go
  internal/controller/stages/regular_stages.go
  internal/controller/stages/regular_stages_test.go
  internal/kubernetes/naming.go
  internal/server/get_analysisrun_logs_v1alpha1.go
  internal/server/get_analysisrun_logs_v1alpha1_test.go
Labels: kind/bug, priority/normal, area/controller, backport/release-1.7

#4759 chore(ui): decrease tag size in promo step alias
  ui/src/features/stage/promotion-step.tsx
Labels: kind/bug, area/ui, priority/high, backport/release-1.7

#4760 fix: ensure kargo viewer sa is not created if api is disabled
  charts/kargo/templates/users/service-accounts.yaml
Labels: kind/bug, priority/high, area/charts, backport/release-1.7

#4757 docs: add v1.7.0 to release notes
  docs/docs/100-roadmap.md
  docs/docs/80-release-notes/100-deprecations.md
  docs/docs/80-release-notes/92-v1.7.0.md
Labels: area/documentation, backport/release-1.7

#4764 feat(ui): pipeline filters must persist even if not in URL query
  ui/src/features/project/pipelines/pipelines.tsx
  ui/src/features/project/pipelines/url-params/use-freight-timeline-controller-store.ts
  ui/src/features/project/pipelines/use-persist-filters.ts
Labels: area/ui, priority/normal, area/usability, backport/release-1.7

#4768 fix(chart): Fixup indentation level for imagePullSecrets in garbage-collector CronJob
  charts/kargo/templates/garbage-collector/cron-job.yaml
Labels: kind/bug, area/charts, backport/release-1.7

#4767 feat: support status operation expressions in config context
  docs/docs/50-user-guide/60-reference-docs/40-expressions.md
  internal/expressions/function/functions.go
  internal/promotion/promotion.go
  internal/promotion/promotion_test.go
Labels: kind/enhancement

#4785 feat(ui): fix position of actions in secrets table
  ui/src/features/project/settings/views/credentials/credentials.tsx
  ui/src/features/settings/cluster-secret/cluster-secret.tsx
Labels: area/ui, priority/normal, area/usability, backport/release-1.7

#4791 fix(image): do not apply lexical sort after semver
  internal/image/semver_selector.go
Labels: kind/bug, priority/high, area/controller, backport/release-1.7

#4817 chore(docs): jfrog-evidence section updates and fix jira markdown table
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/jira.md
  docs/enterprise-features.json
  docs/tags.js
Labels: backport/release-1.7

#4840 chore(ui): do not show managedFields
  ui/src/features/common/analysis-modal/analysis-modal.tsx
  ui/src/features/common/code-editor/yaml-editor-lazy.tsx
  ui/src/features/common/manifest-preview.tsx
  ui/src/features/project/pipelines/promotion/promotion.tsx
  ui/src/features/project/pipelines/warehouse/tabs/settings/warehouse-edit-form.tsx
  ui/src/features/project/pipelines/warehouse/warehouse-details.tsx
  ui/src/features/project/settings/views/analysis-templates/edit-analysis-template-modal.tsx
  ui/src/features/project/settings/views/config-maps/upsert-config-maps.tsx
  ui/src/features/project/settings/views/general/general-settings.tsx
  ui/src/features/project/settings/views/project-config/project-config.tsx
  ui/src/features/project/settings/views/promotion-tasks/edit-promotion-task-modal.tsx
  ui/src/features/settings/analysis-templates/edit-cluster-analysis-template-modal.tsx
  ui/src/features/settings/cluster-config/cluster-config.tsx
  ui/src/features/settings/cluster-promotion-tasks/edit-cluster-promotion-task-modal.tsx
  ui/src/features/stage/stage-details.tsx
  ui/src/features/stage/tabs/settings/stage-edit-form.tsx
Labels: kind/refactor, area/ui, priority/normal, backport/release-1.7

#4827 docs: missing mention of variables at stage level
  docs/docs/50-user-guide/20-how-to-guides/40-working-with-stages.md
  docs/docs/50-user-guide/60-reference-docs/40-expressions.md
Labels: kind/bug, area/documentation, priority/normal, backport/release-1.7

#4841 fix: Added `patch` action for promotions in adminRole
  internal/controller/management/projects/projects.go
Labels: kind/bug, priority/normal, area/management-controller

#4852 fix: account for normalization when matching regex to urls
  internal/credentials/kubernetes/database.go
  internal/credentials/kubernetes/database_test.go
Labels: kind/bug, priority/normal, area/controller

#4853 feat: allow option to opt out of cluster secrets namespace creation
  charts/kargo/README.md
  charts/kargo/templates/cluster-secrets-namespace/namespace.yaml
  charts/kargo/values.yaml
Labels: kind/enhancement, priority/normal, area/controller

#4865 chore: manual cherry pick #4723 -- Add semverDiff function for semantic version comparison in expressions
  docs/docs/50-user-guide/60-reference-docs/40-expressions.md
  internal/controller/stages/regular_stages.go
  internal/expressions/function/functions.go
  internal/expressions/function/functions_test.go
  internal/promotion/promotion.go
Labels: area/documentation, kind/enhancement, priority/high, area/controller

#4857 docs: replace `semver` with `constraint`
  docs/docs/20-quickstart/index.md
  docs/docs/50-user-guide/20-how-to-guides/30-working-with-warehouses.md
Labels: area/documentation, backport/release-1.7

#4855 docs: how to access `vars` & `outputs` in `http` step's success/failure expressions
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/http.md
Labels: area/documentation, backport/release-1.7

#4896 fix(ui): image history section overlap issue
  ui/src/features/project/pipelines/pipelines.tsx
Labels: kind/bug, area/ui, area/regression, backport/release-1.7

#4847 feat(event)!: Adds concrete event types
  api/v1alpha1/event.go
  cmd/controlplane/api.go
  cmd/controlplane/controller.go
  go.mod
  internal/api/event.go
  internal/argocd/namespace.go
  internal/cli/cmd/server/server.go
  internal/controller/argocd/api/v1alpha1/audit_events.go
  internal/controller/promotions/promotions.go
  internal/controller/promotions/promotions_test.go
  internal/controller/stages/control_flow_stages.go
  internal/controller/stages/control_flow_stages_test.go
  internal/controller/stages/regular_stages.go
  internal/controller/stages/regular_stages_test.go
  internal/event/promotion.go
  internal/event/promotion_test.go
  internal/health/checker/builtin/argocd.go
  internal/indexer/indexer.go
  internal/indexer/indexer_test.go
  internal/promotion/promotion.go
  internal/promotion/runner/builtin/argocd_updater.go
  internal/rollouts/analysis_run_builder.go
  internal/server/approve_freight_v1alpha1.go
  internal/server/approve_freight_v1alpha1_test.go
  internal/server/get_analysisrun_logs_v1alpha1.go
  internal/server/get_config_v1alpha1.go
  internal/server/promote_downstream_v1alpha1_test.go
  internal/server/promote_to_stage_v1alpha1.go
  internal/server/promote_to_stage_v1alpha1_test.go
  internal/server/server.go
  internal/server/server_test.go
  internal/webhook/kubernetes/freight/webhook.go
  internal/webhook/kubernetes/freight/webhook_test.go
  internal/webhook/kubernetes/promotion/webhook.go
  internal/webhook/kubernetes/promotion/webhook_test.go
  pkg/argocd/namespace.go
  pkg/event/custom.go
  pkg/event/event.go
  pkg/event/event_test.go
  pkg/event/freight.go
  pkg/event/freight_test.go
  pkg/event/kubernetes/kubernetes.go
  pkg/event/kubernetes/kubernetes_test.go
  pkg/event/kubernetes/sender.go
  pkg/event/promotion.go
  pkg/event/promotion_test.go
  pkg/event/sender.go
  pkg/expressions/json_templates.go
  pkg/expressions/json_templates_test.go
  pkg/go.mod
  pkg/go.sum
Labels: kind/enhancement, kind/refactor, priority/high

#4918 docs: update the project naming convention
  docs/docs/50-user-guide/20-how-to-guides/70-argo-cd-integration.md
Labels: kind/bug, area/documentation, kind/refactor, priority/high, backport/release-1.7

#4940 docs: fix discord invite link to the permalink
  .github/ISSUE_TEMPLATE/config.yml
  README.md
Labels: kind/bug, area/documentation, priority/normal

#4958 chore: manual backports of #4790 and #4901
  .github/workflows/release.yaml
  Makefile
  buf.gen.yaml
  docs/api/docs.templ
  docs/docs/90-api-documentation.md
  hack/codegen/proto.sh
  hack/tools.mk
Labels: area/documentation, kind/enhancement, kind/chore, area/release-process, priority/normal
