Repository akuity/kargo, pull requests merged in 2025-02, with the labels that each got.

#3417 docs: user-focused and ops-focused cred management docs
  docs/docs/60-new-docs/40-operator-guide/40-security/40-managing-credentials.md
  docs/docs/60-new-docs/50-user-guide/20-how-to-guides/20-managing-credentials.md
  docs/docs/60-new-docs/50-user-guide/50-security/30-managing-credentials.md
Labels: area/documentation, area/security, kind/refactor, priority/high

#3391 feat(ui): migrate custom graph solution to `xyflow`
  ui/package.json
  ui/pnpm-lock.yaml
  ui/src/features/project/pipelines/context/pipeline-context.ts
  ui/src/features/project/pipelines/context/use-pipeline-context.tsx
  ui/src/features/project/pipelines/graph.tsx
  ui/src/features/project/pipelines/nodes/custom-node.module.less
  ui/src/features/project/pipelines/nodes/custom-node.tsx
  ui/src/features/project/pipelines/nodes/freight-indicators.tsx
  ui/src/features/project/pipelines/nodes/freight-label.tsx
  ui/src/features/project/pipelines/nodes/repo-node.module.less
  ui/src/features/project/pipelines/nodes/repo-node.tsx
  ui/src/features/project/pipelines/nodes/stage-node-footer.tsx
  ui/src/features/project/pipelines/nodes/stage-node.module.less
  ui/src/features/project/pipelines/nodes/stage-node.tsx
  ui/src/features/project/pipelines/nodes/subscription-node.tsx
  ui/src/features/project/pipelines/nodes/warehouse-node.tsx
  ui/src/features/project/pipelines/pipelines.tsx
  ui/src/features/project/pipelines/types.ts
  ui/src/features/project/pipelines/utils/graph.ts
  ui/src/features/project/pipelines/utils/index-cache.ts
  ui/src/features/project/pipelines/utils/use-pipeline-graph.ts
  ui/src/features/project/pipelines/utils/use-pipelines-infinite-canvas.ts
Labels: kind/enhancement, area/ui, priority/high, area/usability

#3377 chore!: remove scheduled deprecations
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/argocd-update.md
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/git-clone.md
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/git-open-pr.md
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/git-wait-for-pr.md
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/helm-update-chart.md
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/helm-update-image.md
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/kustomize-set-image.md
  docs/old-docs/35-references/10-promotion-steps.md
  internal/directives/argocd_revisions.go
  internal/directives/argocd_revisions_test.go
  internal/directives/argocd_updater.go
  internal/directives/argocd_updater_test.go
  internal/directives/git_cloner.go
  internal/directives/git_cloner_test.go
  internal/directives/git_pr_opener.go
  internal/directives/git_pr_opener_test.go
  internal/directives/git_pr_waiter.go
  internal/directives/git_pr_waiter_test.go
  internal/directives/helm_chart_updater.go
  internal/directives/helm_chart_updater_test.go
  internal/directives/helm_common.go
  internal/directives/helm_image_updater.go
  internal/directives/helm_image_updater_test.go
  internal/directives/kustomize_image_setter.go
  internal/directives/kustomize_image_setter_test.go
  internal/directives/origins.go
  internal/directives/origins_test.go
  internal/directives/schemas/argocd-update-config.json
  internal/directives/schemas/git-clone-config.json
  internal/directives/schemas/git-open-pr-config.json
  internal/directives/schemas/git-wait-for-pr-config.json
  internal/directives/schemas/helm-update-chart-config.json
  internal/directives/schemas/helm-update-image-config.json
  internal/directives/schemas/kustomize-set-image-config.json
  internal/directives/yaml_updater_test.go
  internal/directives/zz_config_types.go
  ui/src/features/promotion-directives/registry/use-discover-registries.ts
  ui/src/gen/directives/argocd-update-config.json
  ui/src/gen/directives/git-clone-config.json
  ui/src/gen/directives/git-open-pr-config.json
  ui/src/gen/directives/git-wait-for-pr-config.json
  ui/src/gen/directives/helm-update-chart-config.json
  ui/src/gen/directives/helm-update-image-config.json
  ui/src/gen/directives/kustomize-set-image-config.json
Labels: kind/chore, area/controller, area/api

#3434 fix(docs): indentation and broken href
  docs/docs/50-user-guide/60-reference-docs/15-promotion-templates.md
  docs/docs/50-user-guide/60-reference-docs/20-promotion-tasks.md
Labels: kind/bug, area/documentation, priority/high, backport/release-1.2

#3441 feat(chart): add NOTES.txt
  charts/kargo/templates/NOTES.txt
  charts/kargo/templates/_helpers.tpl
Labels: area/documentation, priority/high, area/charts, backport/release-1.2

#3430 docs: misc docs cleanup and login instructions
  docs/docs/40-operator-guide/10-basic-installation.md
  docs/docs/40-operator-guide/20-advanced-installation/10-advanced-with-helm.md
  docs/docs/50-user-guide/05-installing-the-cli/img/cli-installation.png
  docs/docs/50-user-guide/05-installing-the-cli/index.md
  docs/docs/50-user-guide/20-how-to-guides/10-logging-in/img/logging-in.png
  docs/docs/50-user-guide/20-how-to-guides/10-logging-in/img/projects.png
  docs/docs/50-user-guide/20-how-to-guides/10-logging-in/img/splash.png
  docs/docs/50-user-guide/20-how-to-guides/10-logging-in/index.md
  docs/docs/50-user-guide/20-how-to-guides/20-working-with-projects.md
  docs/docs/50-user-guide/20-how-to-guides/30-managing-user-permissions.md
  docs/docs/50-user-guide/20-how-to-guides/30-working-with-warehouses.md
  docs/docs/50-user-guide/20-how-to-guides/40-working-with-stages.md
  docs/docs/50-user-guide/20-how-to-guides/50-working-with-freight.md
  docs/docs/50-user-guide/20-how-to-guides/60-verification.md
  docs/docs/50-user-guide/20-how-to-guides/70-argo-cd-integration.md
  docs/docs/50-user-guide/30-patterns/index.md
  docs/docs/50-user-guide/60-reference-docs/40-expressions.md
  docs/old-docs/15-concepts.md
Labels: area/documentation, kind/enhancement, kind/refactor, priority/high

#3445 fix(chart): set `divisor` for `resourceFieldRef`s
  charts/kargo/templates/api/deployment.yaml
  charts/kargo/templates/controller/deployment.yaml
  charts/kargo/templates/dex-server/deployment.yaml
  charts/kargo/templates/garbage-collector/cron-job.yaml
  charts/kargo/templates/management-controller/deployment.yaml
  charts/kargo/templates/webhooks-server/deployment.yaml
Labels: kind/bug, priority/normal, area/charts, backport/release-1.2

#3456 feat: surface likely oidc misconfiguration through ui
  internal/api/option/auth.go
  internal/api/option/auth_test.go
  internal/api/option/option.go
Labels: kind/enhancement, area/security, area/ui, priority/high, area/api, backport/release-1.2

#3458 fix(docs): quickstart guide example
  docs/docs/20-quickstart/index.md
Labels: kind/bug, area/documentation, backport/release-1.2

#3462 docs: add examples page
  docs/docs/40-operator-guide/20-advanced-installation/30-common-configurations.md
  docs/docs/50-user-guide/40-examples.md
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/git-commit.md
  docs/src/components/Home/index.tsx
  docs/todo-docs/50-user-guide/40-examples.md
Labels: area/documentation, kind/enhancement, priority/high, backport/release-1.2

#3464 fix: short term fix for deep copy failing on http status code
  internal/directives/http_requester.go
  internal/directives/http_requester_test.go
Labels: kind/bug, priority/high, area/controller, backport/release-1.2

#3486 fix(ui): empty freight value in column
  ui/src/features/stage/stage-details.tsx
  ui/src/features/stage/verifications.tsx
Labels: kind/bug, area/ui, priority/normal, backport/release-1.2

#3480 fix: set region on default config for AWS creds
  internal/credentials/kubernetes/ecr/managed_identity.go
Labels: kind/bug, area/security, priority/normal, area/controller, backport/release-1.2

#3496 fix: improve debug information `http` step
  internal/directives/http_requester.go
  internal/directives/http_requester_test.go
Labels: kind/bug, kind/enhancement, priority/normal, area/controller, backport/release-1.2

#3498 feat!: make `delete` directive non-strict by default
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/delete.md
  internal/directives/file_deleter.go
  internal/directives/file_deleter_test.go
  internal/directives/schemas/delete-config.json
  internal/directives/zz_config_types.go
  ui/src/gen/directives/delete-config.json
Labels: kind/enhancement, priority/normal, area/controller, backport/release-1.2

#3461 feat: add proxy settings to git client
  internal/controller/git/base_repo.go
Labels: kind/enhancement, priority/normal, area/controller

#3516 fix: invalid type conversion for the `git-wait-for-pr` step
  internal/expressions/json_templates.go
Labels: kind/bug, priority/normal, area/controller, backport/release-1.2

#3522 chore(backport release-1.2): chore(deps): bump Go and Node versions
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  Dockerfile
  Dockerfile.dev
  go.mod
Labels: kind/chore, priority/high, dependencies, go, docker, javascript

#3523 chore(deps): bump gRPC health probe to v0.4.37
  Dockerfile
Labels: kind/chore, priority/high, dependencies, docker, backport/release-1.2

#2673 feat: Adding ClusterAnalysisTemplate support for Stage verifications
  Makefile
  api/service/v1alpha1/service.proto
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/stage_types.go
  charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
  charts/kargo/templates/api/cluster-role.yaml
  charts/kargo/templates/controller/cluster-roles.yaml
  charts/kargo/templates/users/cluster-roles.yaml
  internal/api/delete_clusteranalysistemplate_v1alpha1.go
  internal/api/delete_clusteranalysistemplate_v1alpha1_test.go
  internal/api/get_clusteranalysistemplate_v1alpha1.go
  internal/api/get_clusteranalysistemplate_v1alpha1_test.go
  internal/api/list_clusteranalysistemplates_v1alpha1.go
  internal/api/list_clusteranalysistemplates_v1alpha1_test.go
  internal/api/server.go
  internal/api/testdata/clusteranalysistemplate.yaml
  internal/controller/rollouts/api/v1alpha1/analysis_helpers.go
  internal/controller/rollouts/api/v1alpha1/analysis_helpers_test.go
  internal/controller/rollouts/api/v1alpha1/analysis_types.go
  internal/controller/rollouts/api/v1alpha1/generated.pb.go
  internal/controller/rollouts/api/v1alpha1/generated.proto
  internal/controller/rollouts/api/v1alpha1/groupversion_info.go
  internal/controller/rollouts/api/v1alpha1/zz_generated.deepcopy.go
  internal/rollouts/analysis_run_builder.go
  internal/rollouts/analysis_run_builder_test.go
  internal/rollouts/analysis_template.go
  internal/rollouts/analysis_template_test.go
  pkg/api/service/v1alpha1/service.pb.go
  pkg/api/service/v1alpha1/svcv1alpha1connect/service.connect.go
  ui/src/app.tsx
  ui/src/config/paths.ts
  ui/src/config/themeConfig.ts
  ui/src/features/common/layout/main-layout.tsx
  ui/src/features/settings/analysis-templates/analysis-templates.tsx
  ui/src/features/settings/analysis-templates/create-cluster-analysis-template-modal.tsx
  ui/src/features/settings/analysis-templates/edit-cluster-analysis-template-modal.tsx
  ui/src/features/utils/cluster-analysis-template-example.ts
  ui/src/gen/rollouts/api/v1alpha1/generated_pb.ts
  ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
  ui/src/gen/service/v1alpha1/service-KargoService_connectquery.ts
  ui/src/gen/service/v1alpha1/service_pb.ts
  ui/src/gen/v1alpha1/generated_pb.ts
  ui/src/pages/settings.tsx
  ui/src/utils/decode-raw-data.ts
Labels: kind/enhancement, area/ui, priority/normal, area/controller, area/api, area/crds

#3257 feat: add ability to control semantics for Freight being made available to a Stage
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/stage_helpers.go
  api/v1alpha1/stage_types.go
  api/v1alpha1/warehouse_helpers.go
  api/v1alpha1/warehouse_helpers_test.go
  charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
  ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
  ui/src/gen/v1alpha1/generated_pb.ts
Labels: kind/enhancement, priority/normal, area/controller

#3320 feat(gitprovider): setup gitea provider
  go.mod
  go.sum
  internal/directives/git_pr_opener.go
  internal/directives/schemas/git-open-pr-config.json
  internal/directives/schemas/git-wait-for-pr-config.json
  internal/directives/zz_config_types.go
  internal/gitprovider/gitea/gitea.go
  internal/gitprovider/gitea/gitea_test.go
  ui/src/gen/directives/git-open-pr-config.json
  ui/src/gen/directives/git-wait-for-pr-config.json
Labels: kind/enhancement, priority/normal, area/controller

#3327 feat: json-parse promotion step
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/json-parse.md
  internal/directives/json_parser.go
  internal/directives/json_parser_test.go
  internal/directives/schemas/json-parse-config.json
  internal/directives/zz_config_types.go
  ui/src/gen/directives/json-parse-config.json
Labels: kind/enhancement, priority/high, area/controller

#3530 fix(gitprovider): use provided scheme for API calls
  internal/gitprovider/gitea/gitea.go
  internal/gitprovider/gitea/gitea_test.go
  internal/gitprovider/github/github.go
  internal/gitprovider/github/github_test.go
  internal/gitprovider/gitlab/gitlab.go
  internal/gitprovider/gitlab/gitlab_test.go
Labels: kind/bug, kind/enhancement, priority/normal, area/controller

#3536 docs: documentation for new features
  docs/docs/50-user-guide/20-how-to-guides/40-working-with-stages.md
  docs/docs/50-user-guide/20-how-to-guides/60-verification.md
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/git-open-pr.md
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/git-wait-for-pr.md
Labels: area/documentation, kind/enhancement, priority/high

#3539 feat: allow opt-in to credentials over HTTP
  charts/kargo/README.md
  charts/kargo/templates/controller/configmap.yaml
  charts/kargo/values.yaml
  internal/credentials/kubernetes/database.go
  internal/credentials/kubernetes/database_test.go
Labels: kind/enhancement, area/security, priority/high, area/controller

#3485 feat: conditional step execution
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/promotion_types.go
  charts/kargo/resources/crds/kargo.akuity.io_clusterpromotiontasks.yaml
  charts/kargo/resources/crds/kargo.akuity.io_promotions.yaml
  charts/kargo/resources/crds/kargo.akuity.io_promotiontasks.yaml
  charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
  docs/docs/50-user-guide/60-reference-docs/15-promotion-templates.md
  internal/controller/promotions/promotions.go
  internal/directives/promotions.go
  internal/directives/promotions_test.go
  internal/directives/simple_engine_promote.go
  internal/directives/simple_engine_promote_test.go
  ui/src/features/stage/create-stage.tsx
  ui/src/gen/schema/clusterpromotiontasks.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/promotions.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/promotiontasks.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
  ui/src/gen/v1alpha1/generated_pb.ts
Labels: kind/enhancement, priority/normal, area/controller, area/api

#3550 fix(api): make `availabilityStrategy` optional
  api/v1alpha1/generated.proto
  api/v1alpha1/stage_types.go
  charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
  ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
  ui/src/gen/v1alpha1/generated_pb.ts
Labels: kind/bug, priority/high, area/api, backport/release-1.3

#3558 fix: make stage health unknown when last promotion failed
  internal/controller/stages/regular_stages.go
  internal/controller/stages/regular_stages_test.go
Labels: kind/bug, priority/normal, area/controller, backport/release-1.3

#3561 docs: improve description JSON/YAML parse
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/json-parse.md
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/yaml-parse.md
Labels: area/documentation, kind/chore, priority/normal, backport/release-1.3

#3560 chore(directives): deprecate `messageFromSteps`
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/git-commit.md
  internal/directives/schemas/git-commit-config.json
  internal/directives/zz_config_types.go
  ui/src/gen/directives/git-commit-config.json
Labels: kind/chore, priority/high, area/controller, area/api, backport/release-1.3

#3566 docs: update docs to use official kargo-helm example repo
  docs/docs/50-user-guide/40-examples.md
Labels: area/documentation, kind/chore, priority/normal, backport/release-1.3

#3565 docs: add v1.3.0 release notes
  docs/docs/80-release-notes/100-deprecations.md
  docs/docs/80-release-notes/96-v1.3.0.md
Labels: area/documentation, kind/chore, priority/normal, backport/release-1.3

#3573 fix: improve construction of HTTP transports
  internal/api/dex/proxy.go
  internal/api/option/auth.go
  internal/cli/client/client.go
  internal/cli/cmd/login/login.go
  internal/gitprovider/gitea/gitea.go
  internal/gitprovider/github/github.go
  internal/gitprovider/gitlab/gitlab.go
Labels: kind/bug, area/security, priority/normal, area/controller, backport/release-1.3

#3578 fix: require tag or digest for kustomize-set-image
  internal/directives/kustomize_image_setter_test.go
  internal/directives/schemas/kustomize-set-image-config.json
Labels: kind/bug, priority/normal, area/controller, backport/release-1.3

#3581 docs: note kustomize-set-image tag/digest requirement
  docs/docs/80-release-notes/96-v1.3.0.md
Labels: kind/bug, area/documentation, priority/high, backport/release-1.3
