Repository akuity/kargo, pull requests merged in 2025-05, with the labels that each got.

#3965 docs: correctly document `requiredSoakTime` field
  docs/docs/50-user-guide/20-how-to-guides/60-verification.md
Labels: area/documentation, backport/release-1.4

#3968 chore: pipeline view updates
  ui/src/features/project/pipelines/freight/filter-timerange-utils.ts
  ui/src/features/project/pipelines/freight/freight-card.tsx
  ui/src/features/project/pipelines/graph-filters.tsx
  ui/src/features/project/pipelines/nodes/stage-node.tsx
  ui/src/features/project/pipelines/nodes/warehouse-node.tsx
Labels: area/ui, priority/normal, area/usability

#3945 feat: allow conditional step execution as a function of promotion status
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/promotion_types.go
  api/v1alpha1/promotion_types_test.go
  charts/kargo/resources/crds/kargo.akuity.io_clusterpromotiontasks.yaml
  charts/kargo/resources/crds/kargo.akuity.io_promotions.yaml
  charts/kargo/resources/crds/kargo.akuity.io_promotiontasks.yaml
  charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
  go.sum
  internal/controller/promotions/promotions.go
  internal/expressions/function/functions.go
  internal/promotion/promotion.go
  internal/promotion/promotion_test.go
  internal/promotion/simple_engine.go
  internal/promotion/simple_engine_test.go
  ui/src/features/stage/create-stage.tsx
  ui/src/features/stage/promotion-steps-wizard/promotion-step-form.tsx
  ui/src/features/stage/promotion-steps-wizard/types.ts
  ui/src/features/stage/promotion-steps-wizard/use-promotion-wizard-steps-state.ts
  ui/src/gen/api/v1alpha1/generated_pb.ts
  ui/src/gen/schema/clusterpromotiontasks.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/promotions.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/promotiontasks.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
Labels: kind/enhancement, priority/high, area/controller

#3971 fix(ui): When moving a cursor, buttons in nodes don't work
  ui/src/features/project/pipelines/graph/custom-node.tsx
  ui/src/features/project/pipelines/nodes/stacked-nodes.tsx
  ui/src/features/project/pipelines/nodes/stage-node.tsx
Labels: kind/bug, area/ui, priority/normal

#3974 chore: pipeline view updates
  ui/src/features/project/pipelines/freight/filter-timerange-utils.ts
  ui/src/features/project/pipelines/graph/stack-nodes.ts
  ui/src/features/project/pipelines/nodes/stage-node.tsx
  ui/src/features/project/pipelines/promotion/promotion.tsx
  ui/src/features/stage/tabs/freight-history/freight-history.tsx
  ui/src/features/stage/tabs/freight-history/use-get-freight-map.ts
  ui/src/features/stage/verifications.tsx
  ui/src/utils/decode-raw-data.ts
Labels: area/ui, priority/normal

#3975 feat(ui): Freightline/Promotion UI improvements
  ui/src/features/project/pipelines/freight/freight-card.tsx
  ui/src/features/project/pipelines/freight/freight-timeline.tsx
  ui/src/features/project/pipelines/freight/promotion-mode-header.tsx
Labels: kind/enhancement, area/ui, priority/normal

#3986 chore: minor project governance updates
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/governance.yml
Labels: kind/chore, priority/normal

#3987 fix: typo on verifications and correct cluster promo tasks message
  ui/src/features/settings/cluster-promotion-tasks/cluster-promotion-tasks.tsx
  ui/src/pages/settings.tsx
Labels: kind/bug, area/ui, backport/release-1.5

#3990 chore(ui): show collapsed freights
  ui/src/features/project/pipelines/freight/freight-card.tsx
  ui/src/features/project/pipelines/freight/freight-timeline.tsx
Labels: area/ui, priority/high, area/regression, backport/release-1.5

#3985 feat: add external webhooks server component
  Makefile
  Tiltfile
  charts/kargo/README.md
  charts/kargo/templates/_helpers.tpl
  charts/kargo/templates/common/cert-issuer.yaml
  charts/kargo/templates/external-webhooks-server/cert.yaml
  charts/kargo/templates/external-webhooks-server/cluster-role-binding.yaml
  charts/kargo/templates/external-webhooks-server/cluster-role.yaml
  charts/kargo/templates/external-webhooks-server/configmap.yaml
  charts/kargo/templates/external-webhooks-server/deployment.yaml
  charts/kargo/templates/external-webhooks-server/ingress-cert.yaml
  charts/kargo/templates/external-webhooks-server/ingress.yaml
  charts/kargo/templates/external-webhooks-server/service-account.yaml
  charts/kargo/templates/external-webhooks-server/service.yaml
  charts/kargo/templates/kubernetes-webhooks-server/cert.yaml
  charts/kargo/templates/kubernetes-webhooks-server/cluster-role-binding.yaml
  charts/kargo/templates/kubernetes-webhooks-server/cluster-role.yaml
  charts/kargo/templates/kubernetes-webhooks-server/configmap.yaml
  charts/kargo/templates/kubernetes-webhooks-server/deployment.yaml
  charts/kargo/templates/kubernetes-webhooks-server/service-account.yaml
  charts/kargo/templates/kubernetes-webhooks-server/service.yaml
  charts/kargo/templates/kubernetes-webhooks-server/webhooks.yaml
  charts/kargo/values.yaml
  cmd/controlplane/external_webhooks.go
  cmd/controlplane/kubernetes_webhooks.go
  cmd/controlplane/root.go
  docs/docs/60-contributor-guide/10-hacking-on-kargo.md
  hack/tilt/values.dev.yaml
  internal/webhook/external/config.go
  internal/webhook/external/server.go
  internal/webhook/external/server_test.go
  internal/webhook/kubernetes/admission.go
  internal/webhook/kubernetes/admission_test.go
  internal/webhook/kubernetes/config.go
  internal/webhook/kubernetes/config_test.go
  internal/webhook/kubernetes/freight/aliases.go
  internal/webhook/kubernetes/freight/webhook.go
  internal/webhook/kubernetes/freight/webhook_test.go
  internal/webhook/kubernetes/project.go
  internal/webhook/kubernetes/project/webhook.go
  internal/webhook/kubernetes/project/webhook_test.go
  internal/webhook/kubernetes/projectconfig/webhook.go
  internal/webhook/kubernetes/projectconfig/webhook_test.go
  internal/webhook/kubernetes/promotion/webhook.go
  internal/webhook/kubernetes/promotion/webhook_test.go
  internal/webhook/kubernetes/promotiontask/webhook.go
  internal/webhook/kubernetes/promotiontask/webhook_test.go
  internal/webhook/kubernetes/stage/webhook.go
  internal/webhook/kubernetes/stage/webhook_test.go
  internal/webhook/kubernetes/warehouse/webhook.go
  internal/webhook/kubernetes/warehouse/webhook_test.go
Labels: kind/enhancement, priority/high, area/external-webhooks

#3969 feat: add indexer func for warehouses by subscription repo url
  cmd/controlplane/external_webhooks.go
  internal/indexer/indexer.go
  internal/indexer/indexer_test.go
Labels: kind/enhancement, priority/low, go, area/external-webhooks

#4002 docs: document always(), failure(), and success()
  docs/docs/50-user-guide/60-reference-docs/15-promotion-templates.md
Labels: area/documentation, kind/chore, priority/high, backport/release-1.5

#4005 chore: lock 1.4 docs into 1.4 charts, scripts, etc.
  docs/docs/20-quickstart/index.md
  docs/docs/40-operator-guide/10-basic-installation.md
  docs/docs/40-operator-guide/20-advanced-installation/10-advanced-with-helm.md
  docs/docs/40-operator-guide/20-advanced-installation/20-advanced-with-argocd.md
  docs/docs/50-user-guide/05-installing-the-cli/index.md
  hack/quickstart/install.sh
  hack/quickstart/k3d.sh
  hack/quickstart/kind.sh
Labels: area/documentation, kind/chore, area/release-process, priority/high

#4001 feat: improve step alias error messages
  api/v1alpha1/promotion_types.go
  internal/kargo/promotion_builder.go
  internal/kargo/promotion_builder_test.go
  internal/promotion/simple_engine.go
  internal/promotion/simple_engine_test.go
Labels: kind/enhancement, priority/normal, area/ux, backport/release-1.5

#4015 docs: aws credentials Secret requires awsRegion field
  docs/docs/50-user-guide/50-security/30-managing-credentials.md
Labels: area/documentation, backport/release-1.4, backport/release-1.5

#4025 fix(ui): Invisible filters cover pipeline view
  ui/src/features/project/pipelines/freight/freight-timeline-filters.tsx
  ui/src/features/project/pipelines/pipelines.tsx
Labels: kind/bug, area/ui, priority/high, backport/release-1.5

#3995 docs: add timeout info to argocd-update step
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/argocd-update.md
Labels: area/documentation, kind/chore, priority/normal

#3992 docs: fix errant reference to magical behavior of kustomize-set-image
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/kustomize-set-image.md
Labels: kind/bug, area/documentation, priority/high, backport/release-1.4, backport/release-1.5

#4032 fix(ui): Remove misleading information in new promotion view
  ui/src/features/project/pipelines/promotion/promote.tsx
  ui/src/features/project/pipelines/promotion/promotion-graph.tsx
  ui/src/features/project/pipelines/promotion/promotion.tsx
Labels: kind/bug, area/ui, priority/high, backport/release-1.5

#4036 feat: ProjectConfig ui and API
  api/service/v1alpha1/service.pb.go
  api/service/v1alpha1/service.proto
  api/service/v1alpha1/svcv1alpha1connect/service.connect.go
  charts/kargo/templates/api/cluster-role.yaml
  internal/server/get_project_config_v1alpha1.go
  internal/server/get_project_config_v1alpha1_test.go
  ui/src/config/transport.ts
  ui/src/features/common/code-editor/yaml-editor-lazy.tsx
  ui/src/features/project/list/utils/project-yaml-example.ts
  ui/src/features/project/settings/project-settings.tsx
  ui/src/features/project/settings/views/general/general-settings.tsx
  ui/src/features/project/settings/views/project-config/project-config.tsx
  ui/src/features/project/settings/views/project-config/transport.ts
  ui/src/gen/api/service/v1alpha1/service-KargoService_connectquery.ts
  ui/src/gen/api/service/v1alpha1/service_pb.ts
  ui/src/utils/decode-raw-data.ts
Labels: kind/enhancement, area/ui, area/api-server, needs/priority, backport/release-1.5

#4038 docs: update 20-openid-connect.md
  docs/docs/40-operator-guide/40-security/20-openid-connect.md
Labels: kind/bug, area/documentation, priority/normal, backport/release-1.4, backport/release-1.5

#4047 chore(controller): remove redundant condition in http step logic
  internal/promotion/runner/builtin/http_requester.go
Labels: kind/chore, kind/refactor, priority/normal, area/controller

#4041 docs: Improve GCP WIF section
  docs/docs/40-operator-guide/40-security/40-managing-credentials.md
Labels: kind/bug, area/documentation, priority/high, backport/release-1.5

#4067 feat(cli): add commands for getting and deleting project config
  api/service/v1alpha1/service.pb.go
  api/service/v1alpha1/service.proto
  api/service/v1alpha1/svcv1alpha1connect/service.connect.go
  internal/cli/cmd/delete/delete.go
  internal/cli/cmd/delete/project_config.go
  internal/cli/cmd/get/get.go
  internal/cli/cmd/get/project_config.go
  internal/server/delete_project_config_v1alpha1.go
  ui/src/gen/api/service/v1alpha1/service-KargoService_connectquery.ts
  ui/src/gen/api/service/v1alpha1/service_pb.ts
Labels: kind/enhancement, priority/high, area/cli, area/api-server, backport/release-1.5

#4063 chore(backport release-1.5): chore(deps): bump actions/setup-go from 5.4.0 to 5.5.0
  .github/workflows/release.yaml
Labels: dependencies, github_actions

#4064 chore(deps): update non-k8s dependencies
  go.mod
  go.sum
Labels: dependencies, go, backport/release-1.5

#4065 chore(deps): update Kubernetes libraries to 1.33
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  internal/controller/controllertest/testing.go
  internal/controller/management/projects/event_handlers_test.go
  internal/controller/stages/event_handlers_test.go
  pkg/go.mod
  pkg/go.sum
  ui/src/gen/k8s.io/api/batch/v1/generated_pb.ts
  ui/src/gen/k8s.io/api/core/v1/generated_pb.ts
Labels: kind/chore, priority/normal, dependencies, go

#4071 fix(cli): fix get + delete projectconfig commands
  internal/cli/cmd/delete/project_config.go
  internal/cli/cmd/get/project_config.go
Labels: kind/bug, priority/high, area/cli, backport/release-1.5

#4070 fix(api-server): add projectconfig to types understood by rbac policy normalization logic
  internal/server/rbac/policy_rules.go
Labels: kind/bug, priority/high, area/api-server, backport/release-1.5

#4076 fix(ui): App crashes when we open verifications tab
  ui/src/features/stage/stage-details.tsx
  ui/src/features/stage/verifications.tsx
Labels: kind/bug, area/ui, priority/high, backport/release-1.5

#4083 fix(git): get full commit message body
  internal/controller/git/repo_test.go
  internal/controller/git/work_tree.go
  internal/promotion/runner/builtin/git_commiter_test.go
  internal/promotion/runner/builtin/git_pr_opener.go
Labels: kind/bug, priority/high, area/controller, backport/release-1.5

#4091 fix(ui): downstream promotion must be verified in current stage
  ui/src/features/project/pipelines/freight/freight-timeline.tsx
  ui/src/features/project/pipelines/freight/use-promotion-eligible-freight.ts
Labels: kind/bug, area/ui, priority/high, backport/release-1.5

#4093 Update text about GitFlow
  docs/docs/50-user-guide/30-patterns/index.md
Labels: area/documentation, kind/refactor, priority/normal, backport/release-1.4, backport/release-1.5

#4098 feat(expr): add `unsafeQuote` function
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/http.md
  docs/docs/50-user-guide/60-reference-docs/40-expressions.md
  internal/expressions/json_templates.go
  internal/expressions/json_templates_test.go
Labels: kind/enhancement, priority/normal, area/controller

#4086 feat(runner): support custom PR description
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/git-open-pr.md
  internal/promotion/runner/builtin/git_pr_opener.go
  internal/promotion/runner/builtin/git_pr_opener_test.go
  internal/promotion/runner/builtin/schemas/git-open-pr-config.json
  pkg/x/promotion/runner/builtin/zz_config_types.go
  ui/src/gen/directives/git-open-pr-config.json
Labels: kind/enhancement, priority/normal, area/controller

#4101 fix(ui): use new output payload for git-open-pr deeplink
  ui/src/plugins/pr-plugin/deep-link/promotion-step.tsx
  ui/src/plugins/pr-plugin/deep-link/promotion.tsx
  ui/src/plugins/pr-plugin/get-pr-link.ts
Labels: kind/bug, area/ui, priority/normal, backport/release-1.5

#4100 fix(controller): make yaml-update quote numeric-looking strings as necessary
  internal/promotion/runner/builtin/helm_chart_updater.go
  internal/promotion/runner/builtin/schemas/yaml-update-config.json
  internal/promotion/runner/builtin/yaml_updater.go
  internal/promotion/runner/builtin/yaml_updater_test.go
  internal/yaml/quote.go
  internal/yaml/quote_test.go
  internal/yaml/yaml.go
  internal/yaml/yaml_test.go
  pkg/x/promotion/runner/builtin/zz_config_types.go
  ui/src/gen/directives/yaml-update-config.json
Labels: kind/bug, priority/high, area/controller, backport/release-1.5

#4079 feat(ui): soak time
  ui/src/features/project/pipelines/freight/duration-to-seconds.ts
  ui/src/features/project/pipelines/freight/freight-card.tsx
  ui/src/features/project/pipelines/freight/freight-timeline.tsx
  ui/src/features/project/pipelines/freight/get-soak-time.ts
  ui/src/features/project/pipelines/freight/use-soak-time-counter.ts
  ui/src/features/project/pipelines/freight/use-soak-time.ts
  ui/src/features/project/pipelines/pipelines.tsx
  ui/src/features/utils/cache/freight.ts
Labels: kind/enhancement, area/ui, priority/normal, backport/release-1.5

#4062 docs: clarify that secrets must be labeled a certain way to be available in expressions
  docs/docs/50-user-guide/60-reference-docs/40-expressions.md
Labels: kind/bug, area/documentation, priority/normal, backport/release-1.5

#3997 chore: document accepted values for certain crd fields
  api/v1alpha1/generated.proto
  api/v1alpha1/stage_types.go
  api/v1alpha1/warehouse_types.go
  charts/kargo/resources/crds/kargo.akuity.io_stages.yaml
  charts/kargo/resources/crds/kargo.akuity.io_warehouses.yaml
  internal/image/selector.go
  ui/src/gen/api/v1alpha1/generated_pb.ts
  ui/src/gen/schema/stages.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/warehouses.kargo.akuity.io_v1alpha1.json
Labels: area/documentation, kind/chore, priority/normal, area/crds

#4107 docs: fix error in quickstart promo task definition
  docs/docs/20-quickstart/index.md
Labels: kind/bug, area/documentation, priority/high

#4137 docs: include releaseName field in helm-template example
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/helm-template.md
Labels: kind/bug, area/documentation, backport/release-1.5

#4117 fix(ui): map promotion policies from projectconfig
  ui/src/features/project/pipelines/nodes/stage-node.tsx
  ui/src/features/project/pipelines/pipelines.tsx
  ui/src/features/project/pipelines/use-stage-auto-promotion-map.ts
Labels: kind/bug, area/ui, priority/high, backport/release-1.5

#4119 fix(ui): valid short version
  ui/src/features/project/pipelines/freight/short-version-utils.ts
Labels: kind/bug, area/ui, priority/normal, backport/release-1.5

#4120 fix(ui): freight assembly tables keep resetting to page 1
  ui/src/features/assemble-freight/assemble-freight.tsx
  ui/src/features/assemble-freight/chart-table.tsx
  ui/src/features/assemble-freight/commit-table.tsx
  ui/src/features/assemble-freight/image-table.tsx
Labels: kind/bug, area/ui, priority/normal, backport/release-1.5

#3998 docs: add documentation for kargo-specific annotations and labels
  docs/docs/50-user-guide/60-reference-docs/70-annotations.md
Labels: area/documentation, kind/enhancement, priority/normal, backport/release-1.4, backport/release-1.5

#4160 fix(controller): fix bug in requeue interval calculation logic
  cmd/controlplane/controller.go
  internal/controller/promotions/promotions.go
  internal/controller/promotions/promotions_test.go
  internal/promotion/mock_step_runner.go
  internal/promotion/promotion_test.go
  internal/promotion/registry_test.go
  internal/promotion/runner/builtin/argocd_updater.go
  internal/promotion/runner/builtin/git_pr_waiter.go
  internal/promotion/runner/builtin/git_pr_waiter_test.go
  internal/promotion/runner/builtin/init.go
  internal/promotion/runner/builtin/output_composer.go
  internal/promotion/simple_engine_test.go
  pkg/promotion/mock_step_runner.go
  pkg/promotion/promotion.go
Labels: kind/bug, priority/high, area/controller, backport/release-1.5

#4159 docs: update git-open-pr step
  docs/docs/50-user-guide/60-reference-docs/30-promotion-steps/git-open-pr.md
  internal/promotion/runner/builtin/output_composer.go
Labels: kind/bug, area/documentation, priority/high, backport/release-1.5

#4163 fix(controller): fix two bugs in evaluation of status() func in expressions
  internal/expressions/function/functions.go
  internal/expressions/function/functions_test.go
  internal/promotion/promotion.go
Labels: kind/bug, priority/high, area/controller, backport/release-1.5

#4178 feat(ui): Add layout extensions
  ui/src/extensions/extensions-context.ts
  ui/src/extensions/types.ts
  ui/src/features/common/layout/main-layout.tsx
Labels: kind/enhancement, area/ui, priority/normal

#4168 fix(controller): make stage spec.vars referenceable from verifications
  internal/controller/stages/regular_stages.go
  internal/rollouts/analysis_run_builder_test.go
  internal/rollouts/options.go
  internal/rollouts/options_test.go
Labels: kind/bug, priority/high, area/controller, backport/release-1.5

#4198 docs: improve styling of landing page
  docs/src/components/Home/index.module.scss
  docs/src/components/Home/index.tsx
  docs/static/img/3d-mascotte.png
Labels: area/documentation, kind/enhancement, priority/low, backport/release-1.5

#4203 docs: switch to Algolia for search
  docs/docusaurus.config.js
  docs/package.json
  docs/pnpm-lock.yaml
  docs/src/components/Home/index.tsx
Labels: area/documentation, kind/enhancement, priority/normal, backport/release-1.5

#4192 fix(indexer): enrich context ArgoCD App indexer
  internal/indexer/indexer.go
  internal/indexer/indexer_test.go
Labels: kind/bug, priority/high, area/controller, backport/release-1.5

#4050 fix(api): verify RepoURL validation
  api/testing/regexp.go
  api/v1alpha1/generated.proto
  api/v1alpha1/promotion_types.go
  api/v1alpha1/regexp_test.go
  api/v1alpha1/stage_types.go
  api/v1alpha1/warehouse_types.go
  internal/controller/git/work_tree_test.go
  ui/src/gen/api/v1alpha1/generated_pb.ts
Labels: kind/enhancement, area/devx, priority/normal, area/controller, area/api-server

#4164 docs: make quickstart match the v1.5 UI
  docs/docs/20-quickstart/img/cli-installation.png
  docs/docs/20-quickstart/img/kargo-dashboard-projects.png
  docs/docs/20-quickstart/img/kargo-dashboard-promotion.png
  docs/docs/20-quickstart/img/kargo-freight-timeline.png
  docs/docs/20-quickstart/img/kargo-freight-verified copy.png
  docs/docs/20-quickstart/img/kargo-freight-verified.png
  docs/docs/20-quickstart/img/kargo-frieght-timeline.png
  docs/docs/20-quickstart/img/kargo-projects.png
  docs/docs/20-quickstart/img/kargo-promote-confirm.png
  docs/docs/20-quickstart/img/kargo-promote-option-2.png
  docs/docs/20-quickstart/img/kargo-promote-option.png
  docs/docs/20-quickstart/img/kargo-promotion-view.png
  docs/docs/20-quickstart/img/kargo-stage-arrow-button.png
  docs/docs/20-quickstart/img/kargo-stage-view.png
  docs/docs/20-quickstart/index.md
Labels: area/documentation, priority/high, backport/release-1.5

#4200 fix(ui): Replace icon in stage details button
  ui/src/features/project/pipelines/nodes/stage-node.tsx
Labels: kind/refactor, area/ui, priority/low, backport/release-1.5

#4169 fix(runner): step panic recovery within engine
  internal/controller/promotions/promotions_test.go
  internal/promotion/simple_engine.go
  internal/promotion/simple_engine_test.go
  pkg/promotion/mock_step_runner.go
Labels: kind/bug, priority/high, area/controller, backport/release-1.5

#4207 fix(docs): center landing page and styling tweaks
  docs/docs/10-home.mdx
  docs/src/components/Home/index.module.scss
Labels: area/documentation, area/ui, priority/normal, backport/release-1.5

#4155 fix(ui): git provider deeplink and cred form schema
  ui/src/features/freight/freight-status-list.tsx
  ui/src/features/project/pipelines/freight/freight-card.tsx
  ui/src/features/project/settings/views/credentials/create-credentials-modal.tsx
  ui/src/plugins/pr-plugin/deep-link/promotion-step.tsx
  ui/src/plugins/pr-plugin/get-pr-link.ts
Labels: kind/bug, area/ui, priority/normal, backport/release-1.5

#4175 chore(ui): replace old promotion modal and add abort promotion in new one
  ui/src/features/project/pipelines/promotion/promotion.tsx
  ui/src/features/stage/promotion-details-modal.tsx
  ui/src/features/stage/promotions.tsx
Labels: kind/enhancement, area/ui, priority/normal, backport/release-1.5

#4212 chore(backport release-1.5): fix(runner): step panic recovery within engine
  internal/controller/promotions/promotions_test.go
  internal/promotion/simple_engine.go
  internal/promotion/simple_engine_test.go
  pkg/promotion/mock_step_runner.go
Labels: kind/bug, priority/high, area/controller

#4199 feat: add watchFreights API endpoint
  api/service/v1alpha1/service.pb.go
  api/service/v1alpha1/service.proto
  api/service/v1alpha1/svcv1alpha1connect/service.connect.go
  internal/server/watch_freight_v1alpha1.go
  ui/src/gen/api/service/v1alpha1/service_pb.ts
Labels: kind/bug, priority/high, area/api-server, backport/release-1.5

#4222 docs: remove auto-refresh notice to show new freight
  docs/docs/20-quickstart/index.md
Labels: area/documentation, kind/chore, priority/normal

#4185 chore: docusaurus version 3.7.0
  docs/package.json
  docs/plugins/gtag/package.json
  docs/plugins/gtag/pnpm-lock.yaml
  docs/pnpm-lock.yaml
Labels: area/documentation, kind/chore, priority/low, dependencies, backport/release-1.5

#4224 feat(ui): watch freights
  ui/src/features/project/pipelines/freight/freight-timeline.tsx
  ui/src/features/project/pipelines/pipelines.tsx
  ui/src/features/project/pipelines/use-watch-freight.ts
  ui/src/features/utils/cache/freight.ts
Labels: kind/bug, area/ui, priority/high, backport/release-1.5

#4230 refactor: fix env var with a poorly chosen name
  cmd/controlplane/api.go
  cmd/controlplane/external_webhooks.go
Labels: kind/refactor, priority/normal, area/api-server, area/external-webhooks

#4248 docs(ui): arrow icon -> staggered icon
  docs/docs/20-quickstart/img/kargo-dashboard-projects.png
  docs/docs/20-quickstart/img/kargo-promote-option.png
  docs/docs/20-quickstart/img/kargo-stage-arrow-button.png
  docs/docs/20-quickstart/img/kargo-stage-staggered-bars-button.png
  docs/docs/20-quickstart/index.md
Labels: area/documentation, kind/chore, priority/high, backport/release-1.5

#4218 chore(deps): update controller-runtime to v0.21.0
  go.mod
  go.sum
  internal/controller/controllertest/testing.go
  internal/controller/management/projects/event_handlers_test.go
  internal/controller/management/projects/projects.go
  internal/controller/management/projects/projects_test.go
  internal/controller/stages/control_flow_stages.go
  internal/controller/stages/control_flow_stages_test.go
  internal/controller/stages/event_handlers_test.go
  internal/controller/stages/regular_stages.go
  internal/controller/stages/regular_stages_test.go
Labels: priority/normal, dependencies, go

#4261 fix(controller): properly deregister Stage from Freight
  internal/controller/stages/regular_stages.go
  internal/controller/stages/regular_stages_test.go
Labels: kind/bug, priority/high, area/controller, backport/release-1.5

#4000 feat: webhook receivers
  api/go.mod
  api/go.sum
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/project_config_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  charts/kargo/resources/crds/kargo.akuity.io_projectconfigs.yaml
  charts/kargo/resources/crds/kargo.akuity.io_projects.yaml
  charts/kargo/templates/_helpers.tpl
  charts/kargo/templates/external-webhooks-server/cert.yaml
  charts/kargo/templates/external-webhooks-server/cluster-role.yaml
  charts/kargo/templates/external-webhooks-server/deployment.yaml
  charts/kargo/templates/management-controller/cluster-roles.yaml
  charts/kargo/templates/management-controller/configmap.yaml
  cmd/controlplane/external_webhooks.go
  cmd/controlplane/management_controller.go
  go.mod
  go.sum
  internal/controller/management/projectconfigs/project_configs.go
  internal/controller/management/projectconfigs/project_configs_test.go
  internal/gitprovider/github/github.go
  internal/gitprovider/github/github_test.go
  internal/http/errors.go
  internal/http/errors_test.go
  internal/http/http.go
  internal/http/http_test.go
  internal/indexer/indexer.go
  internal/indexer/indexer_test.go
  internal/io/io.go
  internal/io/io_test.go
  internal/webhook/external/github.go
  internal/webhook/external/github_test.go
  internal/webhook/external/path.go
  internal/webhook/external/refresh.go
  internal/webhook/external/refresh_test.go
  internal/webhook/external/server.go
  internal/webhook/external/server_test.go
  pkg/go.mod
  pkg/go.sum
  ui/src/gen/api/v1alpha1/generated_pb.ts
  ui/src/gen/schema/projectconfigs.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/projects.kargo.akuity.io_v1alpha1.json
Labels: kind/enhancement, priority/high, area/controller, area/crds

#4270 fix(ui): soak time issue
  ui/src/features/project/pipelines/freight/duration-to-seconds.ts
  ui/src/features/project/pipelines/freight/freight-timeline.tsx
  ui/src/features/project/pipelines/freight/use-soak-time-counter.ts
  ui/src/features/project/pipelines/freight/use-soak-time.ts
Labels: kind/bug, area/ui, priority/high, backport/release-1.5

#4264 feat(chart): allow labels and annotations on all serviceaccounts
  charts/kargo/README.md
  charts/kargo/templates/api/service-account.yaml
  charts/kargo/templates/controller/service-account.yaml
  charts/kargo/templates/dex-server/service-account.yaml
  charts/kargo/templates/external-webhooks-server/service-account.yaml
  charts/kargo/templates/garbage-collector/service-account.yaml
  charts/kargo/templates/kubernetes-webhooks-server/service-account.yaml
  charts/kargo/templates/management-controller/service-account.yaml
  charts/kargo/values.yaml
Labels: kind/enhancement, priority/normal, area/charts

#4276 feat: validate webhook receiver name uniqueness + add webhook receiver name to hashed path
  api/v1alpha1/generated.proto
  api/v1alpha1/project_config_types.go
  charts/kargo/resources/crds/kargo.akuity.io_projectconfigs.yaml
  charts/kargo/resources/crds/kargo.akuity.io_projects.yaml
  internal/controller/management/projectconfigs/project_configs.go
  internal/controller/management/projectconfigs/project_configs_test.go
  internal/webhook/external/github_test.go
  internal/webhook/external/path.go
  internal/webhook/external/server_test.go
  internal/webhook/kubernetes/projectconfig/webhook.go
  internal/webhook/kubernetes/projectconfig/webhook_test.go
  ui/src/gen/api/v1alpha1/generated_pb.ts
  ui/src/gen/schema/projectconfigs.kargo.akuity.io_v1alpha1.json
  ui/src/gen/schema/projects.kargo.akuity.io_v1alpha1.json
Labels: kind/enhancement, kind/refactor, priority/normal, area/kubernetes-webhooks, area/external-webhooks, area/management-controller

#4278 feat: add ping event support
  internal/webhook/external/github.go
  internal/webhook/external/github_test.go
Labels: kind/enhancement, priority/normal, area/external-webhooks
